### ISSUE TITLE
Test Bug

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#1]
aoshdfo iasdf kjaspoifj apwiehfasdh apwefn pasjf oawiejf

**Comment by austintruchan** [comment]
That looks like a really bad bug

**Comment by austintruchan** [comment]
Someone should fix that

**Comment by watrall** [comment]
you need to fix it.




Austin Truchan wrote:

**Comment by fritosxii** [comment]
I have fixed this issue
