### ISSUE TITLE
Unable to open links in new tabs. 

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#10]
Trying to open links in kora in a new tab, causes the original tab to go to that link as well, along with the new tab that was created.

**Comment by fritosxii** [comment]
@austintruchan Can you provide more info? Is it a safari thing? Provide a couple examples that do this

**Comment by austintruchan** [comment]
This seems to only happen on the card links. If you open in a new tab, In my case holding command and clicking the link, the new tab is open, however the original tab goes to that link as well.

This has something to do with the way bogdan fixed an issue with these links previously. Before bogdans fix, links were too easily clickable when scrolling on touch screen devices. I don't think we should revert bogdans fix, in order to fix this though.

**Comment by austintruchan** [comment]
Also this is a safari thing. Works fine in chrome.

**Comment by austintruchan** [comment]
This seems to be working, and from testing, doesn't seem to manipulate bogdans scrolling fix.
