### ISSUE TITLE
Create New Record - Multiple Pages - Using pagination should bring you to the top of the next or previous page you click on

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#104]
At the moment, it saves your scroll height, so when you go to the next page, you're at the bottom of the next page, and have to scroll up to go to the top.

**Comment by suuuth** [comment]
on branch `suth-#104`

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41618725-fde30bac-73d1-11e8-9b85-681606744b12.png)
