### ISSUE TITLE
Document - Create New Field & Single Field - Apply Small description below the Allowed File Type field

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#106]
This small description explains that "If you leave this field blank, all file types will be allowed."

Small description text will be styled like all other small description texts for field inputs.

**Comment by Dev34** [comment]
Create New Field Page: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields/create/7?
Single Field Page: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields/18/options

**Comment by austintruchan** [comment]
When you showed me this, it looked good. I don't see it now, but assuming its in a branch. But I believe its still probably good, where ever it is.
