### ISSUE TITLE
Solution for Pages with Many Tabs

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#108]
Specifically for pages like Create New Record - depending on how many pages that form has, the create new record page could have many tabs. 

Here is my proposed solution: https://projects.invisionapp.com/d/main#/console/11107725/241459336/preview

To have the tabs stay on one line, to be scrollable, and to have a button that pushes the tabs over to reveal more. 

Functionality for this can be seen on What America Ate: http://whatamericaate.org/newRecipes.php

**Comment by austintruchan** [comment]
This is good.

I would also reduce the size of the arrows a tad, then have them grow in size hover, like the arrows on the project / form / field cards.

**Comment by suuuth** [comment]
Instead of changing the scale value on hover, the icons now change font-size.

This seems to prevent exposing the gradient background of the element

**Comment by austintruchan** [comment]
Cool. Cool.

**Comment by austintruchan** [comment]
Once anthony approves the code, we will have to go through and add this to the various pages where this functionality is needed.
