### ISSUE TITLE
Global Search tabs

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#109]
Create the Record/Project/Form/Field tabs

The jump to links that are in the global search bar, those would appear in those sections as there respective cards (i.e. like project cards). Unlike the record results tab, there would be no pagination of close/open filtering, just "Showing n Projects" and the project card list

**Comment by fritosxii** [comment]
We also want to add a loading icon instead of the list disappearing and reappearing with no context when typing

**Comment by austintruchan** [comment]
Consult Austin about loading icon and how this should work.

**Comment by suuuth** [comment]
Branch: `suth-109`

**Comment by suuuth** [comment]
I think this is ready for initial review.  Added tabs to the globalsearch results page that allows the user to switch between viewing records, forms, fields, and projects.  Let me know what you think @austintruchan

**Comment by austintruchan** [comment]
I've tried searching multiple things, unfortunately I am not seeing these tabs. Is there a certain search I can enter to see them?

**Comment by austintruchan** [comment]
NVM. I'm dumb.

**Comment by austintruchan** [comment]
- [ ] Increase the margin top of the tabs to be 60px instead of 40px.

- [ ] For the tabs on mobile, have them remain on the same line and fall off the edge and be horizontally scrollable. Same thing we do with the form pages when editing or creating a record, including the arrows.

**Comment by suuuth** [comment]
Margins increased, tabs applied for mobile widths, tabs styled to match body of page ( color and opacity adjustments to left and right chevrons )

all set for review

**Comment by austintruchan** [comment]
- [ ] Move the scroll arrow down a bit so it looks like this: 
<img width="178" alt="screen shot 2019-03-08 at 10 31 43 am" src="https://user-images.githubusercontent.com/5408529/54037967-6a3baa00-418d-11e9-9d33-5ab0616d02cf.png">

- [ ] I realize for the field, form and project tabs, can we have the actual field, form and project cards that are expandable and collapsable?

**Comment by suuuth** [comment]
Scroll chevron positions have been adjusted to be more vertically centered.  Field, form, and projects are now displayed as cards.  Ready for another review.

**Comment by austintruchan** [comment]
Looks good.

- [ ] On mobile, I think you could reduce the spacing between the tabs and the following header by about 40px.
<img width="419" alt="Screen Shot 2019-03-18 at 10 17 44 AM" src="https://user-images.githubusercontent.com/5408529/54536465-26a02780-4967-11e9-8db6-bd6505638325.png">

**Comment by austintruchan** [comment]
This is good to go, just needs to be merged.
