### ISSUE TITLE
Unique id generation from copied forms

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#110]
Can you change the behavior of forms generated from a preset to have them generate unique form ids as formname_project#_form# and AND field ids asfieldname_project#_form#_field# ?? 

Right now it appears to just copy the unique id and append a 1 or _1 onto the end. 

I'd suggest the same method for unique project ids as projectname_project# but you may have a reason for the crazy identifier there? Ex. UbOqni649EmiHHTN1vF7gvYj

**Comment by fritosxii** [comment]
So we can only do one less level than what you want. i.e. project, form_pid_, and field_pid_fid_. A random number will be added on afterwards still if they conflict with another object, as uniqueness is the priority
