### ISSUE TITLE
Parentheses before field on create a record form 

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#112]
https://kora3.matrix.msu.edu/projects/8/forms/15/records/create

Extra space and left parentheses " (" before Age on the form listed above. Age is a number field.

**Comment by Dev34** [comment]
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/records/create

Looks like the extra parenthesis was meant to encapsulate some sort of units data, but the call made to retrieve that data does not appear to work, so it has been removed.

**Comment by Dev34** [comment]
This is on the parenthesis-fix-#112 branch

**Comment by austintruchan** [comment]
I was no longer able to see the extra space and the parenthesis for the number field when creating a new record. Passing to anthony for code review.

**Comment by austintruchan** [comment]
Great. I can see the change. Passing to anthony for code review.
