### ISSUE TITLE
Sign Up Success Spelling

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#124]
Should be "Activate Account" not "Active Account"
<img width="609" alt="screen shot 2018-05-22 at 12 20 01 pm" src="https://user-images.githubusercontent.com/5408529/40375777-8bc5f688-5dba-11e8-9c34-f0ecebfa3a14.png">

**Comment by Dev34** [comment]
![signup](https://user-images.githubusercontent.com/12753141/40503787-4b65bcc8-5f5d-11e8-9cea-12c212f88254.PNG)
Corrected spelling for 'Activate'.
Doesn't really need design review, but if you want to try it: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/register

**Comment by mikelsav** [comment]
Fixed
