### ISSUE TITLE
Remove Background Gradient

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#125]
From all pages, lets remove the background gradient of "linear-gradient(180deg, #fbfbfc 0%, #f5f6f7 20%)" and have it just be #f5f6f7.

I have decided this, because on longer pages, the gradient causes the page to be too light, as the 20% point of the page goes so far down. 

Update the variable for this accordingly.

**Comment by austintruchan** [comment]
Still seeing the gradient on your dev. Should I be looking on a certain branch?

**Comment by suuuth** [comment]
these changes were undone late last week due to personal issues between myself and git.  we have sorted out our differences and this should be fixed again @austintruchan

**Comment by austintruchan** [comment]
Checked on the main project page on your dev and still am seeing the gradient. Send me a mattermost when its ready to be reviewed, or if there is a specific branch I should look in.
