### ISSUE TITLE
Edit token modal checkboxes not highlighted after editing, cancelling, then editing again

### ISSUE THREAD

**Issue by Dev34** [matrix-msu/Kora3#130]

**Comment by Dev34** [comment]
The checkboxes now recalculate if they need to be checked and apply that state instead of always triggering a click event, so the issue is fixed.
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/tokens

**Comment by austintruchan** [comment]
Still seeing the issue. Should I look in a certain branch?

**Comment by Dev34** [comment]
This is on the edit-token-modal-checkbox-fix branch

**Comment by austintruchan** [comment]
Great. This seems to work. Passing to anthony for code review.
