### ISSUE TITLE
Create New Record - Document Field - Need Error Message for when document file is not accepted.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#139]
Currently it just displays the full progress bar, and is confusing as to whether it works or not.

**Comment by fritosxii** [comment]
This will get done with all the record validation stuff.

**Comment by fritosxii** [comment]
Documents know have better error reporting. 

You can view that here, as well as validation for most field types
http://robbie-72.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/21/forms/165/records/create

**Comment by austintruchan** [comment]
I see the error "The uploaded file exceeds the post_max_size directive in php.ini" for everything I upload. Even like a 1mb pdf

I would change that error text to "The uploaded file exceeds the maximum file size" to be more friendlier.

**Comment by fritosxii** [comment]
Added the directive "CONTACT SYSTEM ADMINISTRATOR: " before error messages that require server level action

**Comment by austintruchan** [comment]
Fine
