### ISSUE TITLE
Addition of Loading Icon / Loading Indication

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#14]
Design and implementation of a loading icon / indicator will need to be added.

**Comment by fritosxii** [comment]
- [ ] Add to project/form deletes

- [ ] Add to record operations

- [ ] Add to register

- [ ] Basically, if it's ajax related, probably?

**Comment by fritosxii** [comment]
[new-preloader.zip](https://github.com/matrix-msu/Kora3/files/1963881/new-preloader.zip)

**Comment by Dev34** [comment]
Added loading icon to project and form deletions.

For record operations I added the loader to 'Create New Test Records' and 'Delete All Test Records', but I'm guessing there are other places where you want this added.

All AJAX requests now trigger the loading icon, except cases where the url contains the string 'validate'. This way form validations don't trigger the loading icon. I don't actively use all parts of Kora, so there are likely some cases where you'd rather not have the loading icon pop-up. I can fix these individually.

For register do you want the loading icon for the 'Sign Up' button? I can't get past the first register page so if there are places I need to add loading icon to for register process, it would help to know what text the button has so I can find it in code.

This is on the loader-#14 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Aww man, looks like the right colors didn't export when I originally exported that code.

For the outer ring: #283C46
Middle Ring: #007C83
Inner Ring: #04B6AF

Lets also add a white circle background to the loading icon to distinguish it some more. 
Maybe make the entire loading icon a bit smaller too if possible. 

Updated this comp as an example: https://projects.invisionapp.com/d/main#/console/11107725/235927992/preview

**Comment by austintruchan** [comment]
Once we get the styling of the loading icon set, we can craft a list of all the places the loading icon should go. This will probably be an ever growing list that will grow and grow over time.

**Comment by Dev34** [comment]
Swapped out the colors, added a white background, and made the icon smaller.
For testing purposes, you can execute 'display_loader();' in the console (Chrome DevTools) which will cause the loading icon to display indefinitely. A page refresh or 'hide_loader();' will hide it again. 

Please compile the CSS before reviewing.
This is on the loader-#14 branch (pushed to GitHub)

**Comment by Dev34** [comment]
Added the white space around the outside ring.
Added the drop-shadow on the white background.

Please compile the CSS before reviewing.
This is on the loader-#14 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looking good!

- [ ] Instead of left:50%; for the positioning of the loader, do margin: auto; so it remains completely center at all widths. 

- [ ] Use Top: 40%; instead of 50%.

Go ahead and create a merge request after that is completed.

**Comment by Dev34** [comment]
Changes have been made and a pull request has been opened.

**Comment by fritosxii** [comment]
I'm building a brand new page. The loading icon comes up on an Ajax request without me assigning this functionality to it. This error comes up on the completion of the ajax request.

Side note: is this functionality set up only for ajax requests? Will it work for loading web pages?

![screen shot 2018-08-17 at 9 22 34 am](https://user-images.githubusercontent.com/4040076/44268362-47e93b80-a1ff-11e8-8acc-cb528a8cef80.png)

**Comment by fritosxii** [comment]
@Dev34 Note: this issue could be on my end and my JS breaking could be breaking the icon. That said, do you use length for anything in the JS for the loader?

**Comment by fritosxii** [comment]
Nvm, the error went away when I refreshed the Javascript.

**Comment by Dev34** [comment]
@fritosxii The loading icon is currently set up for all AJAX requests except for validation requests which it filters out. I think Austin was planning on giving me a list of places in Kora where he wants it.
Also if you're referring to displaying the icon on a page load, then yes I think I can make that happen.

**Comment by fritosxii** [comment]
@Dev34 Awesome! Yeah, i think it might be useful, especially for larger page loads!
