### ISSUE TITLE
Deleting the last remaining form page causes that form to error out forever

### ISSUE THREAD

**Issue by Dev34** [matrix-msu/Kora3#141]
Remove the delete button from the last remaining form page to stop them from deleting it.

**Comment by austintruchan** [comment]
I wouldn't remove the delete button, I would just lower the opacity on the button a bit and put the "not-allowed" cursor on it.

**Comment by Dev34** [comment]
Lowered opacity on the button and accompanying tooltip, and added the not-allowed cursor. Also disabled Delete Page modal if there is 1 form page left.

http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/14/forms/27

This is on the delete-fix-#141 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
If possible, I would also remove the tooltip and the hover rotation of the icon as well.

**Comment by Dev34** [comment]
Removed tooltip and hover rotation of the icon.

This is on the delete-fix-#141 branch (pushed to GitHub)
Also please run 'compass compile' before reviewing

**Comment by austintruchan** [comment]
Ok. If possible, lets also remove the hover effect as well.

**Comment by Dev34** [comment]
Removed the hover effect.

This is on the delete-fix-#141 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looks good!
