### ISSUE TITLE
Solution for Long Project / Form Names and edit button

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#143]
Project and Form names shouldn't interfere with the positioning of the edit button. I would make the width of the project / form name shorter, so as to no touch the edit button div, and push it down the head.
<img width="952" alt="screen shot 2018-06-04 at 11 40 10 am" src="https://user-images.githubusercontent.com/5408529/40927231-349457d8-67ec-11e8-8ece-a522e7933be4.png">

**Comment by suuuth** [comment]
on branch: suth-143

**Comment by austintruchan** [comment]
This is better. I would shorten the width of the title just enough so the text never comes in contact with the edit button.

**Comment by suuuth** [comment]
added 30px of padding-right to prevent contact between text and icon

**Comment by austintruchan** [comment]
Hmmm. Not seeing this being a thing either :(

**Comment by suuuth** [comment]
Increased padding of span element containing title text.  Should be plenty of space between the title text and the icon.

**Comment by austintruchan** [comment]
<img width="395" alt="screen shot 2018-06-25 at 2 55 46 pm" src="https://user-images.githubusercontent.com/5408529/41869724-df83f738-7887-11e8-8a73-af412f3d1313.png">

Unfortunately am still seeing an overlap of the icon and the text. This is on chrome with cache reset on suth-143

**Comment by austintruchan** [comment]
Thats better!
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42172969-9a879f0e-7deb-11e8-846b-4e0426ffdd91.png)
