### ISSUE TITLE
Fix all floating update buttons on respective edit pages when side bar menu open

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#15]
Fixed Update project button on edit project page with side bar menu open

**Comment by austintruchan** [comment]
This seems to be fixed by bogdan on some pages, however, not all pages are working appropriately. The single field page seems to work well for reference, while the edit project page does not.

**Comment by Dev34** [comment]
This goes hand-in-hand with my bug fix for https://github.com/matrix-msu/Kora3/issues/3, which I why I assigned myself this task and expanded it to include all the floating buttons.

**Comment by bogdanpozderca** [comment]
Already taking care of it

**Comment by austintruchan** [comment]
@bogdanpozderca Did you take care of this? If so, please push and or pass it back.

**Comment by austintruchan** [comment]
@bogdanpozderca Did you take care of this? If so, please push and or pass it back.

**Comment by austintruchan** [comment]
@bogdanpozderca Did you take care of this? If so, please push and or pass it back.

**Comment by austintruchan** [comment]
@bogdanpozderca Did you take care of this? If so, please push and or pass it back.

**Comment by austintruchan** [comment]
@bogdanpozderca Did you take care of this? If so, please push and or pass it back.

**Comment by Dev34** [comment]
This appears to have been fixed. Closing issue.
