### ISSUE TITLE
toggling sidebar off at certain widths does not bring page functionality back

### ISSUE THREAD

**Issue by suuuth** [matrix-msu/Kora3#154]
Toggling the sidebar on at widths between 886px and 870px prevents page scrolling, as intended.  However toggling sidebar off does not bring this page scrolling back.  Toggling the sidebar on also brings up an overlay `div.blanket` element, which does not cover field cards, and this blanket does not toggle off upon toggling the sidebar off.

Noticed on Form page.

**Comment by suuuth** [comment]
getBrowserWidth() was not getting browser width + scrollbar width.  So at certain browser widths, the user opens the sidemenu, which (because of the lower false width value) would then hide the scrollbar.  This would then cause the browser's width to be calculated to its true value, which would then prevent unsetting the inline set on `<div.blanket>` and `<body>` elements

**Comment by suuuth** [comment]
on branch `suth-#154`

**Comment by austintruchan** [comment]
So, what exactly am I reviewing here? You may have to show me @suuuth

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41678087-18569c30-7498-11e8-84b1-1392a5ee3118.png)
