### ISSUE TITLE
Attempted to build a new kora3 image.  Php syntax errored.

### ISSUE THREAD

**Issue by goekesmi** [matrix-msu/Kora3#157]
https://github.com/matrix-msu/Kora3/blob/83f4df9c238e8bf3ab524ff927efd8fab600f416/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php#L242

[root@252b4d08-76f0-c870-9b35-bc95fc5e7702 /home/node/website]# php index.php 
PHP Parse error:  syntax error, unexpected '?' in /home/node/Kora3/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 242

**Comment by fritosxii** [comment]
Using php7?

**Comment by goekesmi** [comment]
Nope.  Using PHP 5.6, which was the requirement last I checked.  Is PHP7 now required?

**Comment by fritosxii** [comment]
It now requires a minimum of 7.1 I believe. Works on 7.2

**Comment by goekesmi** [comment]
I have an instance up and running on php 7.2.

Probably worth putting in the documentation.
