### ISSUE TITLE
Display the project that a form preset belongs to

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#158]
When creating a form from a preset, the project name is not specified. Please specify the project as well as the form name.

**Comment by suuuth** [comment]
on branch `suth-#158`

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofdisapproval](https://user-images.githubusercontent.com/5408529/41729049-450a8e54-7546-11e8-8178-ef0ccedfc1d2.png)

**Comment by austintruchan** [comment]
Flip it so that Project name appears first, and then form name.

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41872275-5da605fa-788f-11e8-8680-1fd4f3844ffe.png)
