### ISSUE TITLE
Multi Select Dropdown Empty State

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#16]
Would be nice if when there is no options to select, that there is some text like "No more options to select..." instead of just nothing appearing.

**Comment by suuuth** [comment]
branch `suth-#16`

**Comment by austintruchan** [comment]
Where exactly should I look exactly? I found some empty multiselect dropdowns but they did not have any empty state text.

**Comment by suuuth** [comment]
- 1 multi-select on create-project page, this is populated and has pre-set placeholder text
- 2 multi-selects on new-form page, both are populated with pre-set placeholder text (form-admins and select-a-preset)
-new-field
 - 1 multi-select on
    - new-schedule-field
      - not populated, meant to be populated by user with button directly below, however this populating 
        feature does not work on my dev
    - new-document-field - this is populated and has relative placeholder text
    - new-gallery-field - this is populated and has relative placeholder text
    - new-playlist-field - this is populated and has relative placeholder text
    - new-video-field - this is populated and has relative placeholder text
    - new-3dModel-field - this is populated and has relative placeholder text
    - new-GeoLocator-field
      - not populated, meant to be populated by user with button directly below, however this populating 
        feature does not work on my dev
 - 2 multi-selects on
    - new-list-field
      - both are empty, the first multi-select is meant to allow the user to create options to populate both 
        this multi-select and the next
    - new-MultiSelectList-field
      - both are empty, the first multi-select is meant to allow the user to create options to populate both 
        this multi-select and the next
    - new-GeneratedList-field
      - both are empty, the first multi-select is meant to allow the user to create options to populate both 
        this multi-select and the next

if there are any empty/broken multi-select lists that I have missed that you happen to see @austintruchan please let me know.

**Comment by suuuth** [comment]
Applied a fix for multi-selects on:
- new-list-field
- new-multiSelectList-field
- new-generatedList-field

**Comment by austintruchan** [comment]
You might have to show me what you did. I'm not seeing things unfortunately.

**Comment by austintruchan** [comment]
Great! This seems to work well! 

But i'm sad about safari. I definitely think we should find a solution for safari. Maybe not now, but definitely something to come back to. The file uploaders are designed to encourage drag and drop, and I'm sure will cause confusion for the many users that do use safari (apparently its the second most widely used browser behind chrome) as to why the things that look like they will accept a dropped file, just dont.

**Comment by suuuth** [comment]
We could implement a visual change when Safari is detected to avoid this confusion you are talking about.  This would ideally be a temporary fix for until safari-drag-n-drop is figured out

**Comment by austintruchan** [comment]
Whoops. Meant to comment this on the drag and drop issue. I thought it got deleted.

**Comment by suuuth** [comment]
maybe this is a safari issue?  Will re-check

**Comment by suuuth** [comment]
this is a pure js fix, so you should definitely be seeing this.  Will show you tomorrow if there is time

**Comment by suuuth** [comment]
okay I think I got it this time.  Remember this is on `create new field`->set field type to `list`, `generated list`, or `multiselect list` -> click `view advanced field options` -> click on the `default` field dropdown

let me know if I should add this elsewhere on the site too

**Comment by austintruchan** [comment]
Looks good for when there are initially no options to select. I would also like that text to appear after the user had selected all the options when there are options to select as well. So user selects all the options, and then they try to select another option, but would now see "No more options to select" text.

**Comment by suuuth** [comment]
all the things
- [ ] `create new project` admin selection
- [ ] `create new form` admin selection
- [ ] `form permissions` user selection for new permissions group
- [ ] `form permissions` add users to existing group
- [ ] `create new record` multi select list
- [ ] `create new record` occupation field
- [ ] `create new record` schedule field
- [ ] `create new record` associator field (page 6)
- [ ] `create new record` associator results field (page 6)
- [ ] `create new token` project selection

I think this is all the things.  If i've missed some things, please let me know

**Comment by fritosxii** [comment]
On any empty state multi-select, spam clicking it continues to populate the list.

<img width="967" alt="screen shot 2018-07-26 at 1 59 37 pm" src="https://user-images.githubusercontent.com/4040076/43279566-64ea609e-90dc-11e8-81d4-73b20dff35d6.png">

**Comment by suuuth** [comment]
fixing on
- [ ] `create new project` admin selection
- [ ] `create new form` admin selection
- [ ] `form permissions` user selection for new permissions group
- [ ] `form permissions` add users to existing group
- [ ] `create new record` multi select list
- [ ] `create new record` occupation field
- [ ] `create new record` schedule field
- [ ] `create new record` associator field (page 6)
- [ ] `create new record` associator results field (page 6)
- [ ] `create new token` project selection

**Comment by austintruchan** [comment]
Seems okay!
