### ISSUE TITLE
Edit user not working

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#165]
This page previously worked. Does not now. Probably a routing issue. Make sure in User Management, that respective links point to the view/edit pages.

**Comment by suuuth** [comment]
in `routes.php` we have 
```
Route::get('/user/{uid}/{section?}', 'Auth\UserController@index');
    Route::get('/user/{uid}/edit', 'Auth\UserController@editProfile');
```
the latter is never called, clicking the `edit-profile` icon link on the profile page still causes this UserController@index to be called

**Comment by suuuth** [comment]
adding `print($section);` to this `UserController.php`, then clicking the `edit-profile` link causes editprofile to be printed.

editprofile is being treated as if it is a section of index rather than its own page

**Comment by suuuth** [comment]
simply reordering ```
Route::get('/user/{uid}/{section?}', 'Auth\UserController@index');
Route::get('/user/{uid}/edit', 'Auth\UserController@editProfile');
```
to ```
Route::get('/user/{uid}/edit', 'Auth\UserController@editProfile');
Route::get('/user/{uid}/{section?}', 'Auth\UserController@index');
```
fixes this issue

**Comment by fritosxii** [comment]
Makes sense. for each route type like get or post, you need to have static urls above variable ones

**Comment by fritosxii** [comment]
Since this is a back-end fix and no new design was added. Feel free to make the pull request and move it to code review

**Comment by suuuth** [comment]
ok!
