### ISSUE TITLE
My Preferences page

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#171]
https://projects.invisionapp.com/d/main#/console/11107725/242678599/preview

Need to build out this page and add functionality.

**Comment by suuuth** [comment]
will be on branch suth-preferences

**Comment by austintruchan** [comment]
Woah, actually hold up! I believe @mikelsav made progress on this page already. I don't know where he left off though.

**Comment by austintruchan** [comment]
The functionality for the preferences still definitely needs to be set up though.

**Comment by austintruchan** [comment]
- Need a disappearing notification saying "Preferences Successfully Updated!"

- When I set the projects tab selection to custom, and I go to projects, the custom tab is selected, however the arrows that should be apparent on each project card are not there on page load. Switching to alphabetical and back to custom brings the arrows back, but they should be there on load.
- Same for Single project tab selection

- We actually will have the Keep side menu open on wider screens section removed entirely.

**Comment by austintruchan** [comment]
Oh no! I am getting this message when trying to get to the preferences page
<img width="1232" alt="screen shot 2018-09-26 at 4 13 12 pm" src="https://user-images.githubusercontent.com/5408529/46106583-1ae95a80-c1a7-11e8-84d7-72684c9225ae.png">

**Comment by suuuth** [comment]
Fixed!

**Comment by austintruchan** [comment]
Nice! Seems to be working!
