### ISSUE TITLE
Stock placeholder text

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#175]
I believe all pages have some description, besides token management.

From Austin - "I would write a brief description, but lack the technicality and understanding of tokens to properly convey their meaning in simplistic terms"
- [ ] Token Management

**Comment by austintruchan** [comment]
- [ ] Backup Management "Creating a Backup file will create a saved restore point on the server to revert back to. You can download this file afterwards and save it somewhere safe. You can include a name or short description, the start date and time will be added for you. Depending on the size of your database, this may take a few minutes to finish."
