### ISSUE TITLE
Geolocator plugin issues

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#178]
Nomatinim plugin not working as desired for converting from lat/lon to address

**Comment by Dev34** [comment]
app('geocoder')->reverse(latitude, longitude) is always returning an empty collection. 
This plugin makes use of env('GOOGLE_MAPS_API_KEY') which isn't currently defined in .env. This _might_ be causing the issue.

**Comment by fritosxii** [comment]
Waiting on result of [this issue](https://github.com/geocoder-php/GeocoderLaravel/issues/129)

**Comment by fritosxii** [comment]
Ok, now I have nominatim installed properly, now I have to update the Kora side of things to make it work

**Comment by fritosxii** [comment]
Nominatim calls are up to date. GEO WORKS!!!!
