### ISSUE TITLE
Jump to Field in Breadcrumb Navigation seems to have double spacing

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#181]
The space between fields in the jump to field dropdown should be equal to that of the spacings of the jump to project and jump to form dropdowns.

**Comment by suuuth** [comment]
on branch `suth-181`

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42114063-abb2e8b0-7bbb-11e8-91ef-27f592a75836.png)
