### ISSUE TITLE
Pagination broken 

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#190]
e.k3/projects/11/forms/9/records

Pagination is broken. Selecting "Next Page" button or the next page # directs me back to the main project list.

**Comment by fritosxii** [comment]
Duplicate of #166

**Comment by fritosxii** [comment]
This won't actually be fixed by #166. There is an https issue

**Comment by fritosxii** [comment]
Laravel url function and pagination url functions now force https in production
