### ISSUE TITLE
Add # of Records to "View & Search Form Records" Button on the Single Form Page

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#194]
Would be a simple, glanceable way to see if, and how many records exist while on the single form page.

Just need to change the title of the button to read "View & Search Form Records (28)" where (28) is the dynamic number of records that exists for the form.

**Comment by suuuth** [comment]
can be seen on branch `suth-194`

**Comment by austintruchan** [comment]
<img width="870" alt="screen shot 2018-07-09 at 1 34 40 pm" src="https://user-images.githubusercontent.com/5408529/42466430-e834e43c-837c-11e8-90c5-ec62372cc9d3.png">

At the smallest width that these buttons can sit by side while the sidemenu is open, the new numbers will feel crunched, especially if the record number is in the thousands. Is it possible to break the buttons to two lines a little earlier while the sidebar is open?

**Comment by suuuth** [comment]
Are you talking about breaking the buttons to be on top of each other, or breaking the text within the buttons to 2-lined text?

**Comment by austintruchan** [comment]
Talking about having the buttons on top of eachother
