### ISSUE TITLE
Form Validation - Subtle Improvement

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#195]
Upon hitting the big green submit button, sometimes a form won't submit. Well, this is because you've filled out the form wrong. However its sometimes not immediately clear that this is the case, and it seems like the button just doesn't work (especially when the fields that contain errors are up at the top of the page where you can't see them).

My subtle improvement suggestion is to smooth scroll the user up to the top most field that contains an error as the user hits the submit button. This will allow for some clarification as to why the submit button isn't working, especially if the errors are higher up the page and out of view.

**Comment by suuuth** [comment]
applied a fix to the `create-field` page on branch `suth-195`

if this fix looks good then I'll go ahead and add it to:
- [ ] edit-form
- [ ] create-form
- [ ] edit-field
- [x] create-field
- [ ] create-project
- [ ] edit-project

any other pages I've missed that would need this subtle improvement?

**Comment by austintruchan** [comment]
Thats perfect. But I noticed in safari that it just jumps and it doesn't smooth scroll though :(

**Comment by suuuth** [comment]
safari is my favorite thing ever

**Comment by austintruchan** [comment]
dude can you believe I actually use it as my main browser?

**Comment by suuuth** [comment]
I believe I fixed the safari issue, and went ahead and applied this to every page in the checklist.  Let me know if safari is still an issue

**Comment by austintruchan** [comment]
This works on safari now. I would say the scroll speed could be increased though.

**Comment by suuuth** [comment]
No problem.  Animation duration changed from 2500ms to 1000ms

**Comment by austintruchan** [comment]
lets try 200ms

**Comment by suuuth** [comment]
changed it to 200ms

**Comment by austintruchan** [comment]
lol. I don't think I updated when I checked the 1000ms. 200ms seems to fast, Lets see 500ms.

I also noticed that there is a small delay before the page starts to scroll up on safari and on chrome. Any way to remove that small delay?

**Comment by suuuth** [comment]
Now 500ms.  The small delay is from the ajax call - which then triggers this error-scroll-up function.  Unfortunately I can't speed that up.

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42577557-9a5c9cd8-84f2-11e8-8258-d682f967d51c.png)
