### ISSUE TITLE
Fixed Submit Button + Sidebar on Mobile

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#196]
![png image](https://user-images.githubusercontent.com/5408529/42463723-e8f2dda0-8374-11e8-96c2-f419906915ec.png)

The fixed button ideally should appear behind the sidebar on mobile, as right now it obstructs the use of the bottom sidebar links.

**Comment by suuuth** [comment]
branch `suth-196`

**Comment by austintruchan** [comment]
Seems good!
