### ISSUE TITLE
Update back button to be Fixed, and to scroll down with the user. & Remove Back button on Mobile

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#197]
- [x] Update  back button to be Fixed, and to scroll down with the user. 

- [x] Remove  Back button on Mobile widths

**Comment by suuuth** [comment]
on branch `suth-197`

back button removed at `720px` screen width
back button now has `position: fixed`

**Comment by austintruchan** [comment]
Looks good. I would say we could have it be removed at the 480px mark, and not the 720px mark.

**Comment by suuuth** [comment]
adjusted the breakpoint to be at 480px

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42656040-03dd980c-85ec-11e8-8c2d-2728cd9dd318.png)
