### ISSUE TITLE
Single Project and Single Form Filter position Oddities on mobile

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#198]
![png image 2](https://user-images.githubusercontent.com/5408529/42467500-15acbd38-8380-11e8-80ad-5b884d6c27a2.png)

- [x] Single Project page has the filtering section scrollable

![png image 3](https://user-images.githubusercontent.com/5408529/42467501-15bb69c8-8380-11e8-8366-178cc0b9466c.png)

- [x] Single form page doesn't have the icons and text perfectly horizontally aligned. 
- [x] Space below filtering here could be reduced a tad.

**Comment by suuuth** [comment]
branch `suth-198`

**Comment by austintruchan** [comment]
I think looks good for the most part.

On wider widths on the single form page, field sort options are now too close to the first page though.
<img width="930" alt="screen shot 2018-07-12 at 4 46 52 pm" src="https://user-images.githubusercontent.com/5408529/42658452-5ba997f0-85f3-11e8-9424-31883c687d62.png">
