### ISSUE TITLE
Single Form Pages - Potential Mobile Layout Updates 

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#199]
As of now, the form pages on mobile are pretty compact. Lets see if there is anything we can do to make this mobile layout to look more like the comp, and allow for more room: https://projects.invisionapp.com/d/main#/console/11107725/244345655/preview

Essentially we need to reduce the spacings around the pages, and around the fields to allow for more room.

I noticed the comp removes the arrows for organizing pages and fields, But lets keep those in.

How it is now: 
![png image 4](https://user-images.githubusercontent.com/5408529/42467723-ae8a44ee-8380-11e8-9ef6-3e35cc84b5e8.png)

**Comment by suuuth** [comment]
branch `suth-199`

**Comment by suuuth** [comment]
adjusted margins and padding below screen width of 480px

**Comment by austintruchan** [comment]
Looks good. You could probably start this new layout around 700px - 650px even.

**Comment by suuuth** [comment]
now breaks at 720px

**Comment by austintruchan** [comment]
Ok. At the 720px break, can we get the form page to expand to be full width too, like it does at at 480px?

Also be weary how these changes effect the layout of the field option checkboxes. Looks to a bit of an issue with the sidebar open at some widths.

On mobile there is a lot of space below the checkboxes, and above the delete button within the field card. Can we reduce this space a bit?

**Comment by suuuth** [comment]
That change would affect quite a few things across the site, everything with the `center` class.  I'll check to see if it breaks anything on other pages, but just a heads up.

**Comment by suuuth** [comment]
- [ ] note checkbox layout on small widths
- [ ] reduce space below checkboxes and above delete-field button

**Comment by austintruchan** [comment]
I see. I played around with it in browser... Not a super practical way, but applying margin-left: -5%; and
margin-right: -5%; to the .page class could potentially get the desired result without affecting the parent class?

**Comment by suuuth** [comment]
adjusting margin values would not affect the width value of the element, however I think I can use the `pages` class to apply a fix for the width

**Comment by austintruchan** [comment]
Okay! This is better. 

- [ ] I  noticed that on smaller widths there now exists a gap between the field sort options and the first page.

- [ ] Anyway we can have these page functionality work when the layout becomes too thin while the sidebar is also open? Looks like from 1155px and down while the sidebar is open.

**Comment by austintruchan** [comment]
Alrighty I think this is good!
