### ISSUE TITLE
Specialty Field Displays - New/Edit Field and New/Edit Record Views

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#2]
- [x] Geolocator New Field - https://projects.invisionapp.com/d/main#/console/11107725/249998346/preview

- [x] Geolocator New Record - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Schedule New Field - https://projects.invisionapp.com/d/main#/console/11107725/277700684/preview

- [x] Schedule New Record - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Date New Field - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Date New Record - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Associator New Field - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Associator New Record - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] List New Field - https://projects.invisionapp.com/d/main#/console/11107725/249998350/preview
Especially the ability to reorder lists.

- [x] List New Record - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Combo List Field - https://projects.invisionapp.com/d/main#/console/11107725/292425673/preview

- [x] Combo List New Record - https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

- [x] Files Fields (Same for Field and Record Views)- https://projects.invisionapp.com/d/main#/console/11107725/250270205/inspect  
  - [x] Document
  - [x] Video
  - [x] Audio / Playlist
  - [x] Image / Gallery  
  - [x] 3D Model

**Comment by austintruchan** [comment]
I would also add to this list: the 3d object field. I think at the very least we could throw the current 3d object plugin display inside of the container that the other fields have so the 3d object field has some visual consistency. Let me know if this doesn't make sense, @mikelsav

**Comment by austintruchan** [comment]
- [ ] Also some subtle updates to the audio player field display, to include timestamps: https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview

**Comment by mikelsav** [comment]
Combo List currently in progress

**Comment by austintruchan** [comment]
Wow, great update Nick. What all have you completed so far? Anything I can test yet?

**Comment by mikelsav** [comment]
Still working on Lists on the Create Field page http://robbie-72.matrix.msu.edu/~nicholas.mikelsavage/Kora3/public/projects/199/forms/248/fields/create/380
- Cards are moving around, ability to add a card works
- Need to add ability to delete a card, and then plug in the backend functionality

**Comment by austintruchan** [comment]
## List Field

- [ ] List option boxes look too tall, should only be 50px high

- [ ] List options should be closer together, only 15px apart.

- [ ] Make sure arrows, text and trash icon are all vertically centered within the list option block.

- [ ] "Type here and hit the enter..." text should be accent green, ubuntu-medium.

- [ ] "Add" should be fully opaque, ubuntu-medium

- [ ] On smaller widths, stop "Add" from falling off the right of the input. I would always have fixed in position to that right side. I would have the placeholder text slide behind "Add". I would add a background behind "Add" to stop the placeholder text from overlapping with "Add"

- [ ] I know you set it aside, but don't forget that list options should be drag and droppable to be reordered.

**Comment by mikelsav** [comment]
@austintruchan  http://robbie-72.matrix.msu.edu/~nicholas.mikelsavage/Kora3/public/projects/199/forms/248/fields/create/380 List is implemented on this page, tomorrow I will implement it with the other pages (edit field & new/edit record)

**Comment by austintruchan** [comment]
@mikelsav 
## List Field
- [ ] Arrows and text for the list items could be moved up a couple pixels so they are more vertically centered.

- [ ] Delete list option tooltip doesn't show up for created list items.

- [ ] Lets increase the opacity of the placeholder text for "Type here and hit enter..." to 70%

**Comment by mikelsav** [comment]
Lists are complete until bugs are found. Changes pushed

**Comment by fritosxii** [comment]
Taking over the List portion. Adding the list builder to options pages for Multi-Select, Generated List, and the appropriate sub fields in Combo List.

Also making sure Field Value Presets work with the new list builder input

**Comment by austintruchan** [comment]
> Taking over the List portion. Adding the list builder to options pages for Multi-Select, Generated List, and the appropriate sub fields in Combo List.
> 
> Also making sure Field Value Presets work with the new list builder input

I highly doubt this

**Comment by fritosxii** [comment]
Lists now work for all list types. Field Value Presets can also be applied to and created from the list builder.

Here's a multi-select list example
http://robbie-72.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/1/forms/97/fields/5864/options

**Comment by mikelsav** [comment]
Document inputs complete

**Comment by mikelsav** [comment]
All File Inputs ready for review
- Anthony will need to help me out with uploading videos
- Austin can you review documents/audio/video/gallery once Anthony is done

**Comment by austintruchan** [comment]
- [ ] Dragging and dropping a file onto a document field works! however, if there are other document fields on the same page, they too try to upload the same file. In this example, I added the screenshot to the document field at the top, but all the fields tried to upload that same file. 
<img width="776" alt="screen shot 2018-11-26 at 1 41 16 pm" src="https://user-images.githubusercontent.com/5408529/49034929-4bd31500-f181-11e8-90a7-0a664bb0f054.png">

**Comment by austintruchan** [comment]
- [ ] Single select dropdown with grouped options, make sure the group title is ubuntu-medium
<img width="837" alt="screen shot 2018-12-03 at 11 10 56 am" src="https://user-images.githubusercontent.com/5408529/49385826-41b69680-f6ec-11e8-8f12-734f1cf1f2ff.png">

**Comment by austintruchan** [comment]
## List

- [ ] For these list options, lets update the width of the whole container to not expand beyond the edges of the other inputs (I know its like this in the comps, and I'm sorry, but at this point it has been implemented like this everywhere else).

- [ ] Reduce the space below "Add List Options..." by 10px when no options have been added yet if possible.

- [ ] Add tooltip of removing the option

- [ ] Update dropdshadow of this group to what is on the comp: https://projects.invisionapp.com/d/main#/console/11107725/249998350/preview

<img width="991" alt="screen shot 2018-12-03 at 11 20 07 am" src="https://user-images.githubusercontent.com/5408529/49386835-6a3f9000-f6ee-11e8-9afc-f797d687cb64.png">

**Comment by austintruchan** [comment]
## Date
- [ ] can we make the default date input on the create field page be the 3column input? 

- [ ] On create record, if possible, can we add space between the date field inputs when they are stacked?
<img width="602" alt="screen shot 2018-12-03 at 11 39 40 am" src="https://user-images.githubusercontent.com/5408529/49388572-35cdd300-f6f2-11e8-9dfe-ad78e7b2b691.png">

**Comment by austintruchan** [comment]
## Create Schedule Field

- [ ] For consistency with date field, have start year and end year in two columns.
<img width="1037" alt="screen shot 2018-12-03 at 2 33 18 pm" src="https://user-images.githubusercontent.com/5408529/49397011-7a646900-f708-11e8-928a-1ed489089d2f.png">

## Edit Schedule FIeld
- [ ] For consistency with date field, have start year and end year in two columns.

- [ ] Need the up down styled arrows for start year and end year: 
<img width="912" alt="screen shot 2018-12-03 at 2 32 29 pm" src="https://user-images.githubusercontent.com/5408529/49397101-b26bac00-f708-11e8-8c0b-a57a3209d8bf.png">

**Comment by austintruchan** [comment]
## 3d Model

The styling of the color selection inputs is slightly different on the new field and Edit field. They look good on the Edit field.

New Field:
<img width="900" alt="screen shot 2018-12-03 at 2 41 23 pm" src="https://user-images.githubusercontent.com/5408529/49397456-a3392e00-f709-11e8-85fa-3449ae014f51.png">

Edit Field:
<img width="911" alt="screen shot 2018-12-03 at 2 41 09 pm" src="https://user-images.githubusercontent.com/5408529/49397464-a8967880-f709-11e8-9880-fa1b5321a3b9.png">

- [ ] Update new field to look like edit field

**Comment by austintruchan** [comment]
## Association 

- [ ] Update dropshadows of Association field groups. Should be 0 5px 15px 0 rgba(21,39,48,0.03). All field groups should have this same dropshadow. 

<img width="938" alt="screen shot 2018-12-03 at 2 45 36 pm" src="https://user-images.githubusercontent.com/5408529/49397727-6a4d8900-f70a-11e8-8956-ee05911c966f.png">

**Comment by austintruchan** [comment]
## Text!

- [ ] Default values for the text field don't seem to be saving. Please test.

**Comment by austintruchan** [comment]
## Number

- [ ] Editing record displays single interval numbers like this? Remove decimals.
<img width="925" alt="screen shot 2018-12-03 at 3 11 27 pm" src="https://user-images.githubusercontent.com/5408529/49398928-c6fe7300-f70d-11e8-9b6f-59af142a5da3.png">

**Comment by austintruchan** [comment]
- [ ] Seeing big box shadow on the associator search configuration block when creating a new field.

**Comment by austintruchan** [comment]
## Date

- [ ] When side bar is open, date columns get a little wonky at certain widths: 
<img width="1043" alt="screen shot 2018-12-03 at 6 30 29 pm" src="https://user-images.githubusercontent.com/5408529/49408324-cd024d00-f729-11e8-9500-aa9c94d76bcf.png">

**Comment by austintruchan** [comment]
- [ ] Make sure date field in the single column has box shadows 
<img width="659" alt="screen shot 2018-12-04 at 12 54 04 pm" src="https://user-images.githubusercontent.com/5408529/49462333-caeccc80-f7c3-11e8-955c-9f2f8375cfd8.png">
