### ISSUE TITLE
Record Result Pages - Tooltips say Expand, Collapse, and Delete "Fields" instead of "Records"

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#206]
Project results, form results, and search results. 

Tooltips should say Delete Record, Expand All Records, and Collapse All Records, instead of Fields.

**Comment by suuuth** [comment]
branch `suth-206`

**Comment by austintruchan** [comment]
I see the change on the form results page, but not on the project, or search results pages.

**Comment by suuuth** [comment]
Which page are you referring to when you write `project results`?  Could I perhaps get a link?  Or directions how to navigate to this page?

**Comment by suuuth** [comment]
is it this one `Kora3/public/keywordSearch/project/199`?

**Comment by austintruchan** [comment]
I think so, if you go the Project Records link found in the single project dropdown.

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42766798-5f0350aa-88e9-11e8-8788-ae33c648a05b.png)

**Comment by suuuth** [comment]
🎉
