### ISSUE TITLE
Trim trailing whitespace off of added values to chosen lists

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#207]
It's impossible to tell if there is a trailing space within list items. This causes issues during mass import.  The interface needs to be restyled so trailing spaces are obvious. OR spaces at the end of the item should automatically be removed somehow.

**Comment by asheill** [comment]
cc: @seilagonzalez

**Comment by austintruchan** [comment]
Where are you referring to? @asheill

**Comment by asheill** [comment]
The field options page, like projects/11/forms/10/fields/136/options

**Comment by asheill** [comment]
That page is currently broken though @austintruchan. I talk about it in the kora channel.

**Comment by fritosxii** [comment]
The new list interface we create will make it easier to rearrange and edit list items.

In the meantime, I think the best solution is prescriptive. Basically anywhere initializeSelectAddition is used in JS, we need to trim trailing whitespace before adding it to the list.

Removing myself and Austin in case another developer wants to take this on

**Comment by suuuth** [comment]
trailing whitespace is now trimmed before adding it to the list.
