### ISSUE TITLE
Project Card - On Main Projects Page - If the project doesn't have any forms...

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#21]
... the project forms listing on the project card should say "No forms" instead of just being blank.

**Comment by suuuth** [comment]
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/197

**Comment by suuuth** [comment]
duplicate of #58

**Comment by fritosxii** [comment]
Closing because of duplication
