### ISSUE TITLE
New & Edit Record - Remove pagination if only one page exists

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#214]
Remove pagination if only one page exists for new and edit record pages. Will this break anything?

**Comment by suuuth** [comment]
I don't believe this will break anything, but from what I can see there isn't an instance where create/edit record pages only have 1 page.  

on branch `suth-214` - if there are no extra pages, `disabled` class is added to pagination element, which applies `display: none` and hides pagination

**Comment by austintruchan** [comment]
Lol. Well you would just need a form that only has one page, and make a record from it. 

But this seems to work based on my testings!
