### ISSUE TITLE
Auto Highlighting of First field on "Edit" Pages.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#22]
Stop Auto highlighting first input field on "edit" pages. This should only happen on "Create" Pages. Austin can clarify.

**Comment by suuuth** [comment]
was only seeing this issue on Edit Field page

removed autofocus attribute on input element

can be seen on branch `suth-#22`

**Comment by austintruchan** [comment]
Okay. Seems to be working!
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41618538-73cc0748-73d1-11e8-9143-8ec5fc05fb86.png)
