### ISSUE TITLE
Designate Record as Preset Modal Layout Fix

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#222]
Currently looks like: 
<img width="836" alt="screen shot 2018-07-16 at 3 31 57 pm" src="https://user-images.githubusercontent.com/5408529/42779175-9aceaa48-890d-11e8-8556-f3536a0ea3b1.png">

Should look like: https://projects.invisionapp.com/d/main#/console/11107725/242539672/preview

**Comment by suuuth** [comment]
branch `suth-222`

**Comment by austintruchan** [comment]
Looks good! 

A couple more things on top of this:

- [ ] After you create the record preset, the link then turns to "Designated as preset". This is good, but i'm told by anthony you'll have to set it so the class is switched to allow for this modal to appear: 
<img width="399" alt="screen shot 2018-07-18 at 11 32 58 am" src="https://user-images.githubusercontent.com/5408529/42892168-2b67f146-8a7f-11e8-9c83-1b6fb802a9b4.png">

- [ ] This modal currently looks like this and needs some style fixing: 
<img width="341" alt="screen shot 2018-07-18 at 11 36 00 am" src="https://user-images.githubusercontent.com/5408529/42892241-5c8c3566-8a7f-11e8-9339-68f5e5646fac.png">

- [ ] I would like to update the styling of the "Designated as Preset" button after the record is infact set to be a preset to appear as such: https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview
Hovering on link would turn it to accent green, and clicking on it would reveal the already a preset modal.

**Comment by austintruchan** [comment]
Good job
