### ISSUE TITLE
Project Card - On Main Projects Page - Project Admin Modals

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#23]
Listed Project Admins will eventually be links to pop open the their user modals.

example (if you click on one of the "person names"): https://projects.invisionapp.com/d/main#/console/11107725/236966805/preview

**Comment by suuuth** [comment]
on branch `suth-23`

**Comment by austintruchan** [comment]
Hmm. I'm not able to reveal the modal by clicking on one of the admin names.

**Comment by austintruchan** [comment]
cc: @mikelsav Looks like you guys both may have started this.

**Comment by austintruchan** [comment]
This looks pretty good!
