### ISSUE TITLE
Modals and Multiselect Inputs Potential Improvement

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#232]
This used to be a thing, where opening a multiselect list in a modal would show the full drawer of the options, without being cropped within the modal. 

I believe this got changed when we made modals scrollable, but I did like having the dropdown drawer fall off the edge of the modal, instead of getting cropped off by the height of the modal. 

This is most noticeable in the request project permissions modal found on the all projects page.

See if its possible to get the multiselect list to show the full drawer, not get cropped, and fall off the bottom of the modal, instead of getting cropped within the modals height, while still keeping modals scrollable.

**Comment by suuuth** [comment]
this probably isn't easily possible due to the fact that `overflow: auto` or `overflow: scroll` is what allows the modal to be scrollable, but it also crops the element's overflow to remain within the element, rather than bleed over the edge like you want here

I will see what I can do however

**Comment by suuuth** [comment]
will be on branch `suth-232`

**Comment by suuuth** [comment]
can be seen on this page `http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/manage/projectgroups`  when you click `add users to group`.  The modal has visible overflow, but is not scrollable. 

change applied to only this modal

**Comment by austintruchan** [comment]
That looks pretty good!
