### ISSUE TITLE
Stop Mobile Menu Drawer from Pushing User to Top of Page

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#233]
On Mobile, selecting the hamburger menu icon pushes the user to the top of the page. Stop it from doing this.

**Comment by suuuth** [comment]
branch: `suth-233`

**Comment by suuuth** [comment]
increased height of the `.blanket` element - should be visible from anywhere on the page now

**Comment by austintruchan** [comment]
Great!
