### ISSUE TITLE
Advanced search results sorting and pagination bug 

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#236]
When soring an advanced search of a form, selection of 20 per page, 30 per page, or any of the sort order options leads to zero of zero results.

**Comment by asheill** [comment]
You also cannot go to the next page by either clicking a different number or clicking next page.

**Comment by Dev34** [comment]
I'm unable to reproduce any of the issues mentioned; it seems to be working fine. Maybe this was fixed, or maybe an incorrectly-created record was used in the search causing the whole thing to fail like it did.

**Comment by asheill** [comment]
This apparently was resolved...
