### ISSUE TITLE
Record Submission Validation Modal

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#237]
I don't think this feature has been added as an issue yet, so here we go:

When filling out a record and then trying to submit it, its possible the record won't submit due to form validation errors on other pages of form record. As it is now, there is no way to know why the record won't submit, nor knowing which pages the errors occur on.

There is a modal that was designed initially to help solve this, by explaining that there are form validations errors on other pages, and what pages those errors are on.

This can be seen here: https://projects.invisionapp.com/d/main#/console/11107725/241473567/preview

This modal will appear after selecting the submit button, when there are errors on other pages. 

If the only errors exist on the page the user is on, the modal wouldn't show, but would do the thing that scrolls the user up to the errors. 

If there are errors on the current page and other pages, ideally the modal would show, explaining that there are errors on other pages AND the current page, and upon closing the modal, then would scroll the user to the errors on the current page.

**Comment by suuuth** [comment]
branch suth-237

**Comment by austintruchan** [comment]
- [ ] I am seeing the modal, however it seems to only show one page at a time that contains errors.

- [ ] Page titles in the modal also appear with a # hashtag in front of them.

**Comment by austintruchan** [comment]
Ok!

A couple updates that you can see in the comp.

- [ ] Instead of a bullet point, lets have Page # - Page Name

- [ ] Lets also have these pages be links to the actual page themselves, if possible.

**Comment by austintruchan** [comment]
<img width="340" alt="screen shot 2018-08-24 at 1 54 54 pm" src="https://user-images.githubusercontent.com/5408529/44599841-953c4e80-a7a5-11e8-86a7-febc071b1dff.png">

- [ ] Update "The missing fields occur on page(s):" to be Medium weight
- [ ] Update the page titles to be accent green and medium weight
- [ ] Reduce the space above "There are 7 more required fields that must be filled out before you can create the record" and below the modal title

**Comment by austintruchan** [comment]
Okay! I think were looking good, except for this issue on my mobile: 
![png image 9](https://user-images.githubusercontent.com/5408529/44679620-7dfd9b00-aa09-11e8-9412-a742f36df880.png)

**Comment by austintruchan** [comment]
Looks good!
