### ISSUE TITLE
Addition of Form Validation Functionality

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#24]
https://projects.invisionapp.com/d/main#/console/11107725/258057318/preview

Submit button should be faded, and inactive, and non hoverable, until all fields are complete. 

A tooltip will reveal itself on click of the submit button. This is a quick, informative way that stays out the way. 

Fields go to their warning state if the user tabs or moves passed them, and if they are required.

after selecting the non interactive submit button, all feilds that may have not been changed to their warning / missed state, will now change to their warning / missed state. 

Once all required fields are filled, submit button will be come fully opaque, and submittable.

**Comment by austintruchan** [comment]
Just a heads up this is kinda already completed. Or at least there is a system of form validation that you should talk with anthony about if you haven't already. Some things, like the faded submit button, and tooltip that come off of faded submit button, and how the faded submit button becomes unfaded I don't think ever was implemented.

**Comment by suuuth** [comment]
append class `error` to unfilled text fields
append class `disabled` to disabled submit buttons

**Comment by suuuth** [comment]
on branch `suth-#24`

**Comment by austintruchan** [comment]
I can see the faded submit button, and the tooltip, however your work disables the actual error messaging per field. These error messaging should still exist. 
<img width="891" alt="screen shot 2018-06-19 at 2 54 31 pm" src="https://user-images.githubusercontent.com/5408529/41618313-d4d9664e-73d0-11e8-9047-c5d00ae048ac.png">

**Comment by austintruchan** [comment]
After reviewing the UX of disabling the submit button, I've decided that this ultimately is a bad idea. I think what we currently have works better. I am going to close this ticket and we can scrap this branch.
