### ISSUE TITLE
New Forms Remove the "Find a field" and sort options

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#240]
This causes the first page to be directly up against the header.

<img width="980" alt="screen shot 2018-07-20 at 2 29 06 pm" src="https://user-images.githubusercontent.com/5408529/43019058-9a879594-8c29-11e8-9b8f-91af736d351a.png">

Lets keep the find a field search, and sort options for forms that don't have any fields. I don't remember if this was removed on purpose, or maybe this happened accidentally.

**Comment by suuuth** [comment]
branch `suth-240`
