### ISSUE TITLE
Batch Assign, Batch Delete, and Batch Export Multi Selected Records

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#245]
NEW FEATURE ALERT!

Here is the design for a way of selecting / multiselecting records from the form results page, in order to batch assign, batch delete, or batch export the records selected.

https://projects.invisionapp.com/d/main#/console/11107725/308692309/preview

- [x] Record cards on the form results page will now have a radio select button next to the record name.

- [x] Record card style will change when the record is selected (as seen in comps)

- [x] A selected record toolbar will rise / slide in from the bottom of the page immediately after a record is selected, offering functionality to the selected records. 

- [x] Functionality in this toolbar includes selecting / deselecting all records, batch field assigning just for the selected records, exporting just the selected records, and deleting just the selected records.

- [x] When selecting records, and then hitting batch assign in the selected record toolbar, the user will be taken to a special batch assign page. This batch assign page will only effect the selected records, but will be the same as the regular batch assign page, just with altered text. (text for this page in the works).

- [x] When selecting records, and then hitting the export button in the selected records toolbar, the modal for exporting records will appear with altered text. 

- [x] When selecting records, and then hitting the delete button in the selected records toolbar, the modal for deleting a record will appear with altered text. 

- [x] The selected records Toolbar will be adjusted on smaller widths and on mobile. As the browser gets smaller, the space between each item will condense, and the lines between items will also remove when there is no more room for them. Items will begin to fall off the screen, and this toolbar will become horizontally scrollable. 

- [x] Selected Record toolbar will also need to work well while the sidebar is opened, or is closed. 

- [x] Selected Records Toolbar will slide off the bottom of the screen when all records are deselected, either deselecting them all one by one, or by hitting the 'deselect all' button

- [x] Selected Records Toolbar items will have dynamic numbers next to them indicating how many records are selected. The 'Select all' button will have the total number of results, and not the selected number of records.

**Comment by austintruchan** [comment]
New Batch Assign Selected Fields page will contain the following title and description changes: 

Title Changed to: “Batch Assign Field Value Records (23 Selected Records)”
Where (23 Selected Records) is pushed to a new line, and is font-size: 28px;, and where 23 is a dynamic number of selected results.

The Batch Assign Field Values page allows you to modify field values for the selected field across a number of records. You are currently set to Batch Assign Field Values for 23 Selected Records. To begin the Batch Assign process for these selected records, select a field below.

**Comment by suuuth** [comment]
Delete, Export, Select All, Deselect All are all currently functional

the Batch Assign button brings the user to the Batch-Assign-Selected page - but functionality for this page has not been built yet.  Lets review the design of the toolbar, delete/export modals, and batch-assign-selected page, and then finish the Batch-Assign-Selected page functionality

**Comment by austintruchan** [comment]
- [ ] Remove hover effect, The styling will only change when the record is selected, by hitting the radio button.

- [ ] Do have the regular radio button hover effect on the radio select though.

- [ ] Fontsize 12px, ubuntu medium for all text in toolbar

- [ ] When sidebar is open, and then selecting a record, toolbar seems to appear above the sidebar and is full width, instead of stopping at the sidebar. Opening and closing the sidebar then fixes it, but it should stop at the sidebar after selecting, while the sidebar is already open.

- [ ] ^ Same thing on mobile, where the sidebar will appear below the toolbar at first. Closing and reopening will bring the sidebar to the top again though.

- [ ] There are certain leaflet elements, from the location based fields on the records that appear above the toolbar.

- [ ] Lets actually have the select / deselect all be the dark slate text color.

- [ ] Can we include the lines that seperate the buttons in the toolbar?

- [ ] I would pull the batch assign icon from the page in the comps and use it, so the border will be thicker at the smaller size.

**Comment by austintruchan** [comment]
- [ ] On second thought, lets keep fontsize as 14px for the text in toolbar

- [ ] reduce size of plus and minus icons by a couple fontsizes.

- [ ] Reduce left margin of trashcan from 20 to 10px. 

- [ ] Toolbar on mobile seems to scroll the entire page, instead of just scrolling the toolbar content.

**Comment by suuuth** [comment]
I believe the last bullet is fixed.  However, viewing all records of `Austin's Project > This is the Form Name` contains many errors due to multimedia elements not displaying properly (from what I see on my dev) and can cause the entire page to act buggy.  Please check for this horizontal-scrolling issue on other projects as well if you are still seeing this issue.  Also, let me know what widths you are seeing the issue.

**Comment by austintruchan** [comment]
Hmmm. The view all form records pages are now all screwy. I can't even select one of the records anymore. This is for any view form records page.

**Comment by austintruchan** [comment]
- [ ] The new batch assign page when batch assinging selected records has a white background

- [ ] When deleted selected records, if possible, keep the user on the same form records page

**Comment by austintruchan** [comment]
A few things, 

- Selecting all records will select 12 records, even though only 10 records are displayed.
- Is there any potential way to keep your selection of records as you go from page to page?
 - If not, could we safely add an option in the per page dropdown to "show all" ?

**Comment by austintruchan** [comment]
- [ ] if possible keep the toolbar visible after going to the next page, if you've selected something from the first page.

- [ ] trying to deselect all records from the second page, when selecting records from the first page should deselect all records from all pages if possible.

**Comment by suuuth** [comment]
I am having record cards show up on the Global Search page with the checkboxes for this toolbar.  The toolbar isn't added to the Global Search page, so the checkboxes are inactive.  How should I address this?  Remove the checkboxes from cards on this page, or add the toolbar to this page, or something else entirely?

**Comment by austintruchan** [comment]
Nice job with this! I think this is pretty much set!
