### ISSUE TITLE
Search History Items Linking outside of installation

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#248]
I have noticed that the search history items in my dev will more often than not link to the search results page on Kevins Dev. 

I tested this on enslaved.kora.matrix.msu as well, and the search history links would link to kora.matrix.msu.edu instead of enslaved.kora.matrix.msu

**Comment by suuuth** [comment]
This was happening to me as well, except I get rerouted to Austin's Dev when searching for 'Austin's Project'.

I can't seem to recreate it at the moment however

**Comment by austintruchan** [comment]
I figured it out. So in theory this would never really happen in the wild, since no two kora installations would ever point to the same database. So we can close this tissue.
