### ISSUE TITLE
Update the Or, And, Exact Single Select to be the Non Search Version

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#253]
Update the Or, And, Exact Single Select to be the Non Search Version, on all result pages, global, project and form.

**Comment by suuuth** [comment]
- [ ] all result pages
- [x] global
- [ ] project 
- [ ] form

**Comment by suuuth** [comment]
on branch `suth-253`

**Comment by austintruchan** [comment]
Works!
