### ISSUE TITLE
Form Association Cards Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#255]
On the Form associations page, for the association cards, for new and request pages:

- Reduce the spacing above and below the form description. There is currently too much whitespace.
- Add tooltip to the delete icon: "Remove Form Association"

**Comment by suuuth** [comment]
branch `suth-255`

**Comment by austintruchan** [comment]
Better. Lets have the delete tooltip a bit closer to the delete icon, and more centered above it if possible.

**Comment by austintruchan** [comment]
Looking good.
