### ISSUE TITLE
Copy Updates!

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#256]
Use the following bits of text below to update the head section text for the following pages. Where text is italized create a link that is ubuntu medium and the accent green. Link to according pages, unless the link is for documentation. 

## Field Value Presets
Field Value Presets allow you to create predefined field options to be used repeatedly across all projects and forms. For more information on Field Value Presets, refer to the _Field Value Presets - Kora Documentation_. You may Create a New Preset, or edit an existing preset here.

## Batch Assign
The Batch Assign Field Values page allows you to modify field values for the selected field across all records. To begin the Batch Assign process, select a field below. You can also Batch Assign Field Values to only a selection of records. To begin this process, head to the _View Form Records_ page. For more information on Batch Assigning Field Values, refer to the _Batch Assign Field Values - Kora Documentation_.

## Batch Assign for Selected Records (Page does not exist yet)
Based on issue #245
Title Changed to: “Batch Assign Field Value Records (23 Selected Records)” 
Where (23 Selected Records) is pushed to a new line, and is font-size: 28px;, and where 23 is a dynamic number of selected results.

The Batch Assign Field Values page allows you to modify field values for the selected field across a number of records. You are currently set to Batch Assign Field Values for 23 Selected Records. To begin the Batch Assign process for these selected records, select a field below. 

## Record Presets
Use this page to view and manage record presets within this form. Record presets allow you to create an instance of a record to be reused again. To create a new record preset, visit the single record you wish to turn into a preset. There you’ll find the option to turn the record into a preset. For more information on Record Presets, refer to the _Record Presets - Kora Documentation_.

## Form Results
Enter keywords to search below. You can also filter by “Or”, “And”, or “Exact” keyword results. The Search Form Records page also allows you to individually select a number of records in order to batch delete, assign field values, or to export. To create a selection of records,  select the radio buttons next to each record name use wish to select.

## User Management 
Here you can invite, edit and view all the users within this Kora installation. If you need to manage users on a project or form level, go to the according permissions page within the project or form.

**Comment by suuuth** [comment]
branch `suth-256`

**Comment by suuuth** [comment]
- [ ] Field Value Presets
- [ ] Batch Assign
- [ ] Batch Assign for Selected Records (Page does not exist yet)
- [ ] Record Presets
- [ ] Form Results
- [ ] User Management

**Comment by austintruchan** [comment]
All looks good!
