### ISSUE TITLE
Empty States - Removal of Filtering

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#257]
To be consistent with the single form and single project empty state pages, I noticed there are a few sub pages that still have filtering when no objects exists. Lets update the following so that they can all be consistent. 

- [x] Field Value Presets

- [x] Record Revisions (See if we can remove search bar for showing revisions when none exists)

- [x] Tokens

- [x] Backups

- [x] Then I don't have a proper way of testing this, but lets just be sure that the All Projects page doesn't have filtering when no projects exists. 

any other pages?

**Comment by suuuth** [comment]
ranch `suth-257`

**Comment by austintruchan** [comment]
Seems good!

**Comment by suuuth** [comment]
woohoo!
