### ISSUE TITLE
Updating Password, or other user password Issue

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#259]
I am currently unable to update my own password or other users passwords as an admin. Clicking the update profile button does nothing at the moment. Perhaps I am having weird coincidental issues. This was tested on my dev and on the main kora3.matrix.msu.edu. Or perhaps this feature was never implemented yet.

**Comment by Dev34** [comment]
@austintruchan Just tested this and both of these features are working

**Comment by austintruchan** [comment]
Okay! I retested as well and it is indeed working.
