### ISSUE TITLE
Global Search UX Enhancements

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#26]
- [x] Selecting Search, or using Command+K should open the search dropdown, and also auto highlight the search input so the user can begin typing. 

- [x] Update styling based on provided comp: https://projects.invisionapp.com/d/main#/console/11107725/235887767/preview

- [x] Clear search history button should be green

- [x] "Clear Recent search history" should not exist if there is no recent search history. 

- [x] Need ability to be able to use command + K to open menu, then to start typing immediately, then to be able to hit enter on the most relevant / first option provided, or to use the arrow keys to navigate to the correct option and then hit enter. 

- [x] Don't show "clear recent search history" when no search history exists.

- [x] Reduce the number of  "space bar spaces" in front of the "Start typing to search" to be just one space

**Comment by fritosxii** [comment]
- [ ] Styling for focused items as you tab through them

**Comment by suuuth** [comment]
Majority of these seem to have already been addressed.  

I addressed `Styling for focused items as you tab through them` and `Reduce the number of "space bar spaces" in front of the "Start typing to search" to be just one space`

**Comment by austintruchan** [comment]
- [ ] Search dropdown should be pressed up against the right edge of the browser window.

- [ ] Long named search history items should have ellipses.
<img width="290" alt="screen shot 2018-05-22 at 12 08 16 pm" src="https://user-images.githubusercontent.com/5408529/40375218-0224290a-5db9-11e8-9470-36d3cea2d6d1.png">

- [ ] I unchecked a couple of things that just weren't completed from the original comment for this issue.

- [ ] Round the corners of the search dropdown when it is just the search input. 
<img width="284" alt="screen shot 2018-05-22 at 12 10 28 pm" src="https://user-images.githubusercontent.com/5408529/40375322-3fa489be-5db9-11e8-8b07-77b7fae36759.png">

- [ ] autocomplete results fall off the edge, should wrap accordingly as discussed. If not possible, use ellipses.
<img width="278" alt="screen shot 2018-05-22 at 12 11 39 pm" src="https://user-images.githubusercontent.com/5408529/40375373-663de296-5db9-11e8-9a06-1d7e3ea9c00a.png">

- [ ] Bug where if I search for something, and select an autocomplete result, and then open up the search drawer, it shows zero recent search items, and shows the clear history button. I would say it should show the term I searched for.
<img width="292" alt="screen shot 2018-05-22 at 12 14 01 pm" src="https://user-images.githubusercontent.com/5408529/40375507-cf4fd938-5db9-11e8-81dc-154ae8780439.png">

**Comment by austintruchan** [comment]
Also, looks the user dropdown drawer is also shifted on your dev.

**Comment by suuuth** [comment]
If there is no recent-search-history, and you type something in to trigger the autocomplete results, then delete your search query before submitting any search queries, the autocomplete results dissappear, but the clear-recent-search button shows and stays. 

Investigating

**Comment by suuuth** [comment]
Bug has been addressed.  Please review @austintruchan

**Comment by austintruchan** [comment]
This is good. I would say we should push these changes after anthony's code review, and get them on the main beta. 

After that, I would like to see what you can do as far as increasing the speed at which the autocorrect items show up. At the moment they are very hesitant when you first enter the search, especially when there are history items, as the history results slowly animate away, and the auto correct results slowly fall in. I would say we should speed up these animations so they are almost instant, or remove them. Anything to get those autocomplete results to appear faster. Right now I feel like they can easily be missed since they take a couple seconds to appear.
