### ISSUE TITLE
User Management's Invite User(s) modal prompts deletion of own account, and random User account

### ISSUE THREAD

**Issue by Dev34** [matrix-msu/Kora3#279]
![inviteuserbug](https://user-images.githubusercontent.com/12753141/44221143-8b37a180-a14e-11e8-9846-3ddde487e4b3.PNG)
See image. Remove everything concerning account deletion.

**Comment by Dev34** [comment]
Removed the offending modals from the Invite New User(s) modal on the User Management page.

This is on the invite-modal-fix-#279 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
I do not see the delete user stuff, so I think we are good!
