### ISSUE TITLE
Creating New Field Value Preset "<<<<<<HEAD" 

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#283]
<img width="890" alt="screen shot 2018-08-24 at 11 34 30 am" src="https://user-images.githubusercontent.com/5408529/44593577-c7dc4c00-a791-11e8-9bf3-1c395be6cd53.png">

I am assuming this should be removed?

Also looks like it shows up for all field value presets

**Comment by fritosxii** [comment]
git merge code removed

**Comment by austintruchan** [comment]
I love the development team on k3! They will fix any bugs in under 10 minutes!

**Comment by fritosxii** [comment]
That's the Kora 3 Dev Team promise *thumbs up*
