### ISSUE TITLE
Fix Delete User modal on User Management page

### ISSUE THREAD

**Issue by suuuth** [matrix-msu/Kora3#288]
Delete User modal currently displays an empty modal instead of a modal with a 'Delete User' button

**Comment by suuuth** [comment]
will be on branch suth-288

**Comment by austintruchan** [comment]
Okay. Looks good. Would you also be able to make the tooltip when hovering over the trash can closer to the trash can?
<img width="124" alt="screen shot 2018-09-04 at 1 27 59 pm" src="https://user-images.githubusercontent.com/5408529/45047195-5aa8a080-b046-11e8-91ca-c1de65b62bba.png">

**Comment by suuuth** [comment]
- [ ] fix `Delete User` tooltip
- [ ] investigate this fix bringing back issue #279

**Comment by austintruchan** [comment]
I'm confused, I don't see the tooltip being fixed, and also should I be seeing the Delete my account buttons on the user invite modal still?

**Comment by suuuth** [comment]
looks like my fix wasn't committed yesterday.  Will re-fix

**Comment by austintruchan** [comment]
Classic Kevin you guys!!!

**Comment by suuuth** [comment]
This was weird, from what I saw here, it looks like my modal fix was applied but not the tooltip fix.  Should be good now.  Branch suth-288

**Comment by austintruchan** [comment]
Looks like the modal is fixed, but the tooltip is still a bit too far away from the trashcan. 
<img width="179" alt="screen shot 2018-09-07 at 2 01 17 pm" src="https://user-images.githubusercontent.com/5408529/45235332-8924b680-b2a6-11e8-8ff0-8d36eb02cf14.png">

**Comment by austintruchan** [comment]
Third times a charm! Looks good.
