### ISSUE TITLE
Restore Fields to Before Modal Update

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#290]
<img width="859" alt="screen shot 2018-09-11 at 11 02 25 am" src="https://user-images.githubusercontent.com/5408529/45368728-474f8500-b5b2-11e8-9acd-56fa6c450efd.png">

Should be a lil modal as shown in the comps: https://projects.invisionapp.com/d/main#/console/11107725/244300975/preview

**Comment by suuuth** [comment]
branch suth-290

**Comment by austintruchan** [comment]
Hmmm, still seeing the big modal. Tested on the main Manage Record Revisions Page, and on single record revision page.

**Comment by austintruchan** [comment]
Hmmmm. It looks like you've just shrunk the bigger modal design. It should be a little modal like all the other little modals.

Example of little modal: 
<img width="354" alt="screen shot 2018-09-26 at 4 34 03 pm" src="https://user-images.githubusercontent.com/5408529/46107717-183c3480-c1aa-11e8-97eb-50198e9124bf.png">

Your Restore Fields modal: 
<img width="347" alt="screen shot 2018-09-26 at 4 34 00 pm" src="https://user-images.githubusercontent.com/5408529/46107727-225e3300-c1aa-11e8-8fae-856ea72a6333.png">

**Comment by suuuth** [comment]
added `small` class to this modal.  Deleted dead css

**Comment by austintruchan** [comment]
Much better. I would reduce the spacing above and below the paragraph text though to be closer to the comp: https://projects.invisionapp.com/d/main#/console/11107725/244300975/preview

**Comment by suuuth** [comment]
Vertical margins have been reduced

**Comment by austintruchan** [comment]
Good
