### ISSUE TITLE
Delete Preset Tooltip Positioning

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#291]
<img width="203" alt="screen shot 2018-09-11 at 11 13 13 am" src="https://user-images.githubusercontent.com/5408529/45369379-bd082080-b5b3-11e8-8d5f-ae2ff6fd86ed.png">

Should be directly centered above the trash icon, and closer to the trash icon.

**Comment by suuuth** [comment]
on branch suth-291

**Comment by austintruchan** [comment]
Looks good
