### ISSUE TITLE
Combo Field Single Field Page Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#292]
Goal is to make Combo Field page more inline with the comps: https://projects.invisionapp.com/d/main#/console/11107725/292425673/preview

Several updates to the field UI & interactions are being developed by @mikelsav, and the default list values section will use elements that are created by him. 

We will also need to test out every variant of field combinations the combo field can have.

**Comment by suuuth** [comment]
will be on branch suth-292

**Comment by suuuth** [comment]
can be seen on page: `/Kora3/public/projects/193/forms/391`

combo field page styling should be more inline with comps now.

**Comment by austintruchan** [comment]
- [ ] Make sure spacing below titles that are "title --------" have consistent spacing beneath.
<img width="1024" alt="screen shot 2018-10-17 at 1 39 39 pm" src="https://user-images.githubusercontent.com/5408529/47105927-5362de00-d213-11e8-999a-96f4d626d9cc.png">

Here you can see there is more space below "field options for occupation", than field options for name.

**Comment by austintruchan** [comment]
- [ ] Lets also have consistent spacing between each of the groups. Comp updated to reflect this. Let me know if this doesn't make sense.

**Comment by austintruchan** [comment]
Okay. I think we're good.
