### ISSUE TITLE
Associator Field Single Field Page Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#293]
Goal is to make Associator Field page more inline with the comps: https://projects.invisionapp.com/d/main#/console/11107725/292425673/preview

**Comment by suuuth** [comment]
will be on branch `suth-293`

**Comment by suuuth** [comment]
Edited associator-field-page associator-section to be more inline with comps

**Comment by austintruchan** [comment]
Looks really good!

**Comment by suuuth** [comment]
wooohooo!
