### ISSUE TITLE
New Associator Field Page Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#294]
Update the Create new Field page when associator is selected, for the advanced options drawer, to be more inline with the comps: https://projects.invisionapp.com/d/main#/console/11107725/292413004/preview

**Comment by suuuth** [comment]
branch `suth-294`

**Comment by austintruchan** [comment]
- [ ] Add quotations around the form name for Search through "Form name"?

- [ ] Add a bit of space between the preview field and the 'search through 'form name'?'

- [ ] Need spacing between radio buttons when there are multiple associations:
<img width="775" alt="screen shot 2018-09-27 at 11 12 56 am" src="https://user-images.githubusercontent.com/5408529/46155905-5d15a900-c246-11e8-823d-1812a6346c1e.png">
<img width="894" alt="screen shot 2018-09-27 at 11 13 09 am" src="https://user-images.githubusercontent.com/5408529/46155914-5f780300-c246-11e8-8e14-f047625fa7bc.png">

**Comment by austintruchan** [comment]
- [ ] lets add even more space between the buttons, at least of the bottom of an open button, so the next button doesn't feel apart of the open button.
<img width="570" alt="screen shot 2018-09-27 at 2 13 26 pm" src="https://user-images.githubusercontent.com/5408529/46165889-c2c25f00-c25f-11e8-9dac-7009fa8a69d5.png">

**Comment by suuuth** [comment]
Added 10px of margin between these elements

**Comment by austintruchan** [comment]
Ok thats looking good.

**Comment by austintruchan** [comment]
Make sure this spacing carries over to the styling of the associator design for the single associator field page for #293
