### ISSUE TITLE
Associator & Combo Field Design on Single Record and Single Record Cards

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#296]
Might be involved in #2, but want to make sure we get to this.

Update Associator and combo fields to look more inline with the comps on the single record page, and the single record cards: https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview

**Comment by suuuth** [comment]
This can be seen on 'kevin test project' > 'demiGod' > view form records page

the record is 193-278-9270

**Comment by suuuth** [comment]
Ok - now if you edit the associator field on the form that will display the records containing this associator field, you can now select more than 1 field to preview

this can be seen at `/Kora3/public/projects/193/forms/278/records`

**Comment by austintruchan** [comment]
- [ ] let's Reduce the name of the record in the associated record preview cards down to font-size: 16px. Seems to be at 18px still.

- [ ] add cursor pointer on the associated record for opening and closing it's drawer. Still not seeing this. Essentially adding cursor pointer to the area that opens and closes the associated record drawer. 
<img width="811" alt="screen shot 2018-10-10 at 12 58 48 pm" src="https://user-images.githubusercontent.com/5408529/46752876-4763a300-cc8c-11e8-9161-8c786ccdae82.png">

- [ ] Still seeing strange half rounded, half square corners. Looks like you need to add border radius 5px to the overlay div to fix.

**Comment by suuuth** [comment]
Okay, I had applied these styles to the individual record page rather than that page as well as the record-index page.  Styles have been applied to both pages now.

**Comment by austintruchan** [comment]
Looks good!
