### ISSUE TITLE
Update Field and Update Form "floating" buttons on respective edit pages, are unclickable when floating above other clickable elements

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#3]
As they are unclickable when floating above other clickable elements.

**Comment by Dev34** [comment]
**# Ready for Review**
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/3/edit
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/3/fields/2/options
Re-added the smooth opacity transition on hover, completely re-did button positioning implementation for more extensibility

**Comment by austintruchan** [comment]
Seems good! commit changes for this.

**Comment by austintruchan** [comment]
Seems Good.

**Comment by fritosxii** [comment]
Go ahead and make a pull request for this when ready

**Comment by fritosxii** [comment]
All set
