### ISSUE TITLE
Implement Batch Assign Field Values page for a batch record set

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#301]
The page should behave/look exactly like the regular Batch Assign Field Value page, with a couple exceptions. 

- The `Overwrite All Previously Inputted Fields?` checkbox doesn't need to be in the html form and can be removed. 
- The html form should submit to `massAssignRecordSet` instead of `massAssignRecords`. You may need to make a new route.
- The RID set from the batch selection process should be passed into the html form under the value "rids". `massAssignRecordSet` expects it be an array, so modify the function to transform it into an array of RIDs if the value is passed in another variation during the html form's submission.

**Comment by suuuth** [comment]
will be on branch suth-301

**Comment by austintruchan** [comment]
Design for page looks good.
