### ISSUE TITLE
Back Button Functionality Update & Add in Missing Back Buttons

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#308]
As it is now, the back button will take you back to the previous page, but if selected again it will take you back to the page you were just on.

Is there any potential way to allow it to work more like the browser back button? Where it would continue taking me back through the previous pages I visited?

**Comment by austintruchan** [comment]
I've also notice that several pages are missing the back button entirely

- [ ] Import Records

- [ ] Manage Record Revisions

- [ ] Form Permissions

- [ ] Association Permissions

- [ ] Run through all pages to confirm all back buttons are present.

**Comment by austintruchan** [comment]
Hmmm, would you be able to push this functionality so I can play with it?

**Comment by Dev34** [comment]
Good news! I was able to find an alternative implementation that works well and intuitively with the browser's built-in back button.

It also looks like Anthony went ahead and added back buttons to all those pages you listed. I combed through most of the Kora3 pages again and couldn't find one without a back button.

This is on the back-button-#308 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Nice! This seems to work well!
