### ISSUE TITLE
Notifications to Add (Growing List - Keep Open)

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#309]
Would like to have this issue remain open if possible so I can request additional notifications as I see them.

**Comment by austintruchan** [comment]
- [ ] Form Association Permissions - When creating a new form association. I feel like one was made before, but I am not seeing it. Should be a disappearing notification, reading "Form Association Successfully Created!"

**Comment by austintruchan** [comment]
- [ ] Double check and make sure notifications show up when creating a new project permissions group, and when creating a new form permissions group.

**Comment by austintruchan** [comment]
- [ ] "All Test Records Successfully Deleted!" after hitting the delete test records button on the edit form page

**Comment by suuuth** [comment]
branch `suth-new-notifications`

**Comment by suuuth** [comment]
The three notifications listed here have been added and are ready to be reviewed.

**Comment by austintruchan** [comment]
Looks good. Anthony can review code and then we can close this ticket, despite the name of the ticket title.
