### ISSUE TITLE
User Preference data for new user.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#312]
Couple bugs we need to fix.

A user cannot get to the Register page because preferences are invoked and a non logged-in user does not have an account yet.
- When the preference function is invoked, have the function return a "default" set of values if the user is `\Auth::guest()`.

Along with this we need to make sure that whenever a new user is created, they get a preference table row added with "default" values.
- Add to `User::finishRegistration()` and create user section of `AdminController->batch()`

Lastly as a safety net. When we look at user's preferences, if that row doesn't exist, let's just add it to the preferences table.
- When the preference function is invoked, if the user's preference row is null, make them a default one.

**Comment by suuuth** [comment]
branch suth-312

**Comment by suuuth** [comment]
- Added default set of preferences to `returnUserPrefs` if condition `\Auth::guest()` is met
- Added block to assign default preferences to `User::finishRegistration()`
- Added block to assign default preferences to `AdminController->batch()`
