### ISSUE TITLE
Apply association input design to record create

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#317]
Apply same design for associator field options page to the record input field (views/partials/records/input/associator.blade.php)

Keep in mind to maintain the ID structures that are different than the option page version.

**Comment by suuuth** [comment]
branch suth-317

**Comment by austintruchan** [comment]
Will want the associator field to look more inlines like that in the comp, with proper spacing between the associator fields and descriptions beneath each associator field if possible: https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview


This will also be reiterating what #295 is tasking

**Comment by suuuth** [comment]
This should look quite a bit more like the invision design now

**Comment by austintruchan** [comment]
Looks good! For the association results field description, change "Default Associations" in that text to be "Selected Associations"

**Comment by suuuth** [comment]
Done!
