### ISSUE TITLE
Dashboard development needs to finished

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#318]
in dashboard view, project blocks have no padding between edge of browser chrome 
![2018-10-01_10-57-04](https://user-images.githubusercontent.com/109138/46296870-5bf7bb00-c569-11e8-9a28-7058c57e75dd.png)

**Comment by fritosxii** [comment]
Dashboard is still in development, so review of style is unneeded at this point

**Comment by austintruchan** [comment]
Closing this issue, official Dashboard ticket: #356
