### ISSUE TITLE
Add presets to combolist options page

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#327]
Basically we need to apply the field option presets that exist for certain field types (Text, List, etc), to their respective sub-field types in a combo list. Will be similar, but a smidge more dynamic and involved due to the nature of combo list.

**Comment by suuuth** [comment]
will be on branch `suth-327`

**Comment by suuuth** [comment]
can be seen here: `/Kora3/public/projects/193/forms/397/fields`

**Comment by austintruchan** [comment]
seems to be good
