### ISSUE TITLE
Couple errors for advanced search

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#328]
Advanced search only has a couple validation fail cases. In the controller's processRequest function, it fails in a couple cases involving Schedule and Number, we basically need to either send back with an error notification or we need to error out these cases and prevent the form submit for an advanced search.

**Comment by fritosxii** [comment]
I'm replanning how these are handled so I'm stealing this while I work on other Advanced search things.

**Comment by fritosxii** [comment]
Have to rethink this logistically, since we ignore blank inputs, so they aren't technically wrong. Closing for now

**Comment by fritosxii** [comment]
No worries @Dev34 , the whole thing needs to be rethought out so it's a little more work than what I had planned for this ticket.

**Comment by Dev34** [comment]
Sounds good!
