### ISSUE TITLE
Single Project Page - Description in the head of the page lists out the Unique ID in the description area, along with the description. 

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#33]
<img width="970" alt="screen shot 2018-03-08 at 1 13 13 pm" src="https://user-images.githubusercontent.com/5408529/37168383-b5f788a4-22d2-11e8-8e34-c20d7271e3ff.png">

**Comment by austintruchan** [comment]
I believe this was fixed.

**Comment by Dev34** [comment]
Yes, this was committed
