### ISSUE TITLE
Gallery Fields with Captions

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#334]
Gallery fields with captions designs have been made.
For New / Edit Record: https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview

For Single Record, and record cards: https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview

Now it is your duty to make this into reality? Do you have what it takes? Only time will tell...

**Comment by fritosxii** [comment]
@mikelsav Let me know when the front end portion of this is committed, so I can start the backend portion!

**Comment by asheill** [comment]
@fritosxii @mikelsav what is the status of this?

**Comment by fritosxii** [comment]
Can test on this Form: http://robbie-72.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/1/forms/100/records

**Comment by austintruchan** [comment]
All looks good. The only thing I would say could be better is that the arrow icons in the gallery get a tad off center in their circles on smaller widths / mobile. 
![png image](https://user-images.githubusercontent.com/5408529/48731475-1b342e00-ec0b-11e8-86bc-06acfddd033d.png)

**Comment by fritosxii** [comment]
Will deal with the arrow thing here: #385
