### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#336]
Onboarding will occur after a user creates a new account. After they hit the sign up button, they'll be redirected to the main projects page, but greeted with the onboarding modals.

There are a few onboarding paths:
1. General user, unfamiliar with Kora
2. General user, familiar with Kora
3. Admin user, unfamiliar with Kora
4. Admin user, familiar with Kora

For general users, the onboarding screens start here: https://projects.invisionapp.com/d/main#/console/11107725/256492346/preview
This is for any user invited into kora that is not set as an admin.

For admin users, the onboarding screens start here: https://projects.invisionapp.com/d/main#/console/11107725/258847068/preview
Admin onboarding will occur for the root user after the kora installation sequence, or if the user is invited into kora as an admin.

Users and admin users will only see the onboarding modals once, and these modals should never repeat after the user goes through all of them, or hits the skip intro button. 

There is however a way for the user to 'replay' the modals from the user preferences page, which will need to be set up.

For general users, if they request project permissions on the last screen of the onboarding modals, a notification will appear as shown here: https://projects.invisionapp.com/d/main#/console/11107725/257442911/preview

Illustrations for screens can be found within(Note: Several of these illustrations are bound to change, but can be used as placeholders in the meantime): 
[Onboarding Illustrations.zip](https://github.com/matrix-msu/Kora3/files/2484281/Onboarding.Illustrations.zip)

For mobile designs of the onboarding modals, refer to this: https://projects.invisionapp.com/d/main#/console/11107725/313155141/preview

Sit down with Austin before beginning the onboarding development to run through everything.

**Comment by suuuth** [comment]
branch suth-336

**Comment by suuuth** [comment]
- [ ] General user, unfamiliar with Kora
- [ ] General user, familiar with Kora
- [ ] Admin user, unfamiliar with Kora
- [ ] Admin user, familiar with Kora

**Comment by austintruchan** [comment]
<img width="513" alt="screen shot 2018-12-14 at 10 49 29 am" src="https://user-images.githubusercontent.com/5408529/50013061-279f7280-ff8e-11e8-848a-35e992f80f20.png">

- [ ] remove font-weight bolds from h3s, these should be ubuntu medium
- [ ] Remove space after users name and before exclamation point

<img width="199" alt="screen shot 2018-12-14 at 10 53 22 am" src="https://user-images.githubusercontent.com/5408529/50013192-81a03800-ff8e-11e8-977d-b4ce053b818c.png">
- [ ] hover effects all look good, but if you could get the tooltips to be centered above the hovered pagination dot that would be great.

<img width="98" alt="screen shot 2018-12-14 at 10 56 15 am" src="https://user-images.githubusercontent.com/5408529/50013341-e65b9280-ff8e-11e8-9605-37956b309516.png">
- [ ] add space in between what's new

<img width="706" alt="screen shot 2018-12-14 at 10 58 41 am" src="https://user-images.githubusercontent.com/5408529/50013573-7b5e8b80-ff8f-11e8-80a8-d8ec0966424d.png">
- [ ] Set up so that if the user is an admin, they see the admin final on boarding screen, instead of this screen if they take the "I am new to kora" path.


<img width="741" alt="screen shot 2018-12-14 at 11 04 12 am" src="https://user-images.githubusercontent.com/5408529/50013752-063f8600-ff90-11e8-9a70-9f0386d0cc43.png">
- [ ] make this dropdown searchable
- [ ] at the moment it is also impossible to scroll this dropdown. I can't get to or see project 5 & project 6.

**Comment by austintruchan** [comment]
@watrall The latest comments have not been addressed yet, no. Once the public website development is complete, development will continue with finalizing these onboarding screens.

**Comment by austintruchan** [comment]
> @austintruchan looks like the on boarding visuals and text haven’t been updated based on comments?

@watrall 
I realize I misunderstood what you were asking. The text in these should be up to date based on suggestions from invision. There are several pages that will need to be rewritten completely based on feedback on InVision, which will come from the upper admins. Other issues, like the onboarding navigation has been updated. The visuals have not been updated yet, no. When they're updated they'll be reposted to invision for approval.

**Comment by austintruchan** [comment]
@suuuth 

- [ ] Make sure inline linked text is ubuntu-medium, and have the padding bottom of this text drop down to 3px from 5px.

<img width="167" alt="screen shot 2019-01-09 at 10 40 02 am" src="https://user-images.githubusercontent.com/5408529/50910061-09952880-13fb-11e9-8dc1-c1cee838202f.png">

- [ ] Have the "Skip Intro" Text be ubuntu medium as well.

- [ ] For the Project permissions page, I realize that this should be a multiselect dropdown, in the case the user knows of multiple projects they should request permissions to.

**Comment by suuuth** [comment]
All set for another review.

**Comment by austintruchan** [comment]
- [ ] Update project permissions multiselect dropdown so there are spaces between the selected items.

- [ ] Update so the project list is left aligned with the dropdown's placeholder text.

<img width="647" alt="screen shot 2019-01-10 at 1 59 12 pm" src="https://user-images.githubusercontent.com/5408529/50990488-28211f80-14e0-11e9-935b-84889d1a9438.png">

**Comment by suuuth** [comment]
- margin added to selected options
- padding reduced for dropdown options

**Comment by austintruchan** [comment]
- [ ] Onboarding cards should be scrollable on smaller heights.

- [ ] Make sure the project permissions dropdown is scrollable

- [ ] onboarding cards backgrounds seem to be browser height based, but should be based on the height of the content within: 
<img width="314" alt="screen shot 2019-01-10 at 3 05 05 pm" src="https://user-images.githubusercontent.com/5408529/50994171-91596080-14e9-11e9-9d71-3ddf83256ce3.png">


- [ ] I think the mobile breakpoint happens a little too early. I would see what you can do keep the desktop breakpoint for as long as possible as the browser condenses.

**Comment by suuuth** [comment]
- entire modal can now be scrolled if there is any overflow off the edge of the screen - this includes cases where the projects dropdown drops past the edge of the screen
- projects dropdown is scrollable, assuming there is more than 6 options to select from.  I have updated the amount of options in this dropdown to show this
- percentage-based height attribute removed from this modal
- modal now breaks to mobile styles much later, breakpoint moved from 700px to 420px

all set for another review

**Comment by austintruchan** [comment]
This is looking much better.

- [ ] Onboarding modals are now scrollable, but on smaller height browsers I am unable to scroll to the very top of the modal. I can however scroll all the way to the bottom. 

- [ ] For the permissions dropdown on modal, if possible allow the height of the modal to grow as the height of the permission input grows. 
<img width="331" alt="screen shot 2019-01-11 at 4 34 58 pm" src="https://user-images.githubusercontent.com/5408529/51060869-4578eb00-15bf-11e9-8202-cb6c3708af48.png">

**Comment by suuuth** [comment]
- `top:50%; transform: translateY(-50%);` were preventing scrolling to the top of the modal.  Added some js to address this issue
- height value on dropdown on small browser widths removed.  Dropdown (and containing modal) now grow and shrink as items are added and removed

all set for another review

**Comment by suuuth** [comment]
Ok I added this scroll-top-on-page-change functionality.  Take a look and let me know what you think!

**Comment by austintruchan** [comment]
- [ ] On the permissions screen, update the projects name that you already have permissions to, to be the same size as the paragraph text above. 

- [ ]  On the permissions screen, update the spacing below the request permissions input so that it is 40px on wider widths. Looks fine on mobile.

**Comment by suuuth** [comment]
- font size adjusted
- margin-bottom added to dropdown input

Set for another review

**Comment by austintruchan** [comment]
Oh and set up the "replay Kora introduction" to work from the my preferences page.

**Comment by suuuth** [comment]
This still needs:
- Should this also pop up on projects page as well as dashboard?  In case the user sets 'projects' page as their default landing page rather than dashboard.
- [ ] Currently reloading the page shows the onboarding modals again.  Should only show once.
- [ ] Need to set up `replay kora intro` on prefs page
- [ ] Connect projects to project permissions modal slide

**Comment by austintruchan** [comment]
Yes, should actually only appear on the all projects page, as that is the page that should be set as the default page the user lands after signing up. I believe rainier may have fixed the default home page in #449

**Comment by suuuth** [comment]
All set for another review!
- onboarding modal now visible on projects page
- onboarding modal now disables itself once loaded, this prevents it from showing up every time the page is loaded
- clicking `replay kora intro` button on edit preferences page enables the onboarding modal and takes the user to the page where they will see the modal
- project permissions slide now displays projects that the user has access to, and also projects the user can request access to

**Comment by austintruchan** [comment]
- [ ] Move the replay kora intro section to bottom of my preferences as is in the comps

- [ ] As a non admin user, I was unable to replay the Kora introduction. Works with the admin / root user.

**Comment by suuuth** [comment]
Replaying onboarding as a non admin works for me, however I noticed the request-project-access slide doesn't actually request project permissions.  Setting that up now.

**Comment by suuuth** [comment]
- replay kora intro button moved to bottom of preferences page
- selecting a project in the dropdown on the request-access slide, then clicking `finish` button now submits a request for permissions to the selected projects

Let me know if this should submit some way other than only when there are items selected and the `finish` button is pressed.  It is very easy to accidentally click off the modal and have it close without requesting access to any of the selected projects.

**Comment by austintruchan** [comment]
Hmmm i'm not sure if its just my dev, but I still can't get the kora introduction to replay. It just sends me back to the projects page. Is it because I have projects set to be the home target? 

Mmmm, I suppose that is a good point. I did notice that because the height of the modals change as you click through them it makes it more possible that someone may click off of it too. Let's just have it so that clicking off the modals does nothing to eliminate that possibility.

**Comment by suuuth** [comment]
Onboarding is on both the projects page and the dashboard page, so the replay button bringing you to the projects page shouldn't cause any issues.  The replay system also doesn't rely on the user being an admin, so whether admin or not it should replay.  This does work for me on both admin and non admin accounts.

**Comment by suuuth** [comment]
Clicking off the modal no longer closes the modal.  You can only close the modal with the `skip intro` button on top of the modal or with the `finish` button on the last slide

**Comment by austintruchan** [comment]
Ok. Make sure the "Skip Intro" text also closes the modals along with the "X" icon.

**Comment by suuuth** [comment]
Done!  Text and "X" both close the modal.

**Comment by austintruchan** [comment]
Okay! I am thinking this is good to go then!

**Comment by Dev34** [comment]
Roughly half of the onboarding changes have been ported to deconstruct. This includes all the new images and fonts, changes to preferences (which were reconciled with preference changes in deconstruct), most of the CSS, and many minor tweaks.

**Comment by Dev34** [comment]
The rest of the onboarding changes have been ported to deconstruct, which includes all the new markup files and a few other changes. Bugs related to fetching user preferences that were caused by the different preferences implementations between the two branches were fixed, but some still remain. From initial testing, everything was ported correctly as the onboarding modal is working correctly and looking as before.

**Comment by Dev34** [comment]
Upon further testing: a JS error was found that would occur on page load for non-admin users and cause the onboarding modal not to display. This has been fixed. The user preference for toggling onboarding was not updating when the user closed the onboarding modal. That is now fixed so that onboarding only displays once. It was also discovered that the onboarding modal would break the section spacing on the projects. An issue will be created for this bug.

Onboarding is now fully moved to deconstruct.
