### ISSUE TITLE
Invite User & User Management UX Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#337]
- [x] Need loading icon when inviting new user from user management page

- [x] Need error state if user tries to enter an email that is already registered on the invite new user modal

- [x] Need notification for Invite user success "User(s) Successfully Invited!"

- [x] Need to create the email that is sent for newly invited users: https://projects.invisionapp.com/d/main#/console/11107725/257900977/preview

- [x] Need to create the account set up / sign up screen the user goes to after selecting 'Accept Invite' From the email. This will allow the user to set up there profile information from the get go: https://projects.invisionapp.com/d/main#/console/11107725/258590126/preview

--- 

- [x] We also would like the ability to find users by their email, when searching for users on the user management page.

**Comment by austintruchan** [comment]
This things will also need to be applied to the project / form permissions pages when inviting new users. I believe those pages do have loading icons and notifications, but not sure about error state. And we'll need to make sure they have the new email design as well.

**Comment by suuuth** [comment]
will be on branch `suth-337`

**Comment by suuuth** [comment]
Form Permissions modal doesn't currently have an add-users-by-email input, only a dropdown to select users by their first + last name.  Did you want me to add invite-by-email to this modal like the project-permissions modal?

**Comment by austintruchan** [comment]
No.

**Comment by suuuth** [comment]
This should be good to go.  I believe I have everything set as it should be, however I can't seem to get the second-to-last line of text in the emails to appear bold.  It has the proper font family assigned, but doesn't appear bold for me in Gmail (unless I use `font-weight:600`).

**Comment by austintruchan** [comment]
- [ ] Accept Invite button in the invite email seems to take me to the login screen instead of the set up account screen. Upon logging in as the Root person, it takes me to the account set up screen ... ?

- [ ] Upon trying to submit the sign up on the set up account screen, I ran into the problem of having the email already exist. 
<img width="890" alt="screen shot 2018-11-20 at 10 57 46 am" src="https://user-images.githubusercontent.com/5408529/48785722-4d00cf80-ecb3-11e8-9189-9e6978ce36be.png"> I'm assuming this is because it technically does already exist, since the account was created when the admin sent the invite.

- [ ] Remove  font weight bold from "Lets set up your account"
<img width="656" alt="screen shot 2018-11-20 at 10 54 18 am" src="https://user-images.githubusercontent.com/5408529/48785801-73266f80-ecb3-11e8-9af2-3f7f3f0e97c9.png">

**Comment by suuuth** [comment]
Routing issue is fixed along with the email validation and font-weight.  Tested this with my gmail and I was able to invite and create an account for myself.

**Comment by austintruchan** [comment]
- [ ] Make sure "You have been invited by Root Person" is just Ubuntu-Medium without any font weights on it for the invitation email: 
<img width="331" alt="screen shot 2018-11-28 at 11 18 51 am" src="https://user-images.githubusercontent.com/5408529/49165560-7ea31780-f2ff-11e8-934b-bd444b63cf35.png">

- [ ] Strange circle logo at the top of the welcome to kora page. You can use what currently exists on the "Thanks for Signing Up page"
<img width="843" alt="screen shot 2018-11-28 at 11 20 14 am" src="https://user-images.githubusercontent.com/5408529/49165631-a4302100-f2ff-11e8-86fe-0d030996b724.png">

- [ ] After signing up from the "Welcome to Kora" Screen, I was redirected to the "Thanks for Signing UP Page." This is good, however I am still waiting on the activation email for maybe 10 mins now. Could be a fluke, but can you reassure me that this activation email does in fact send after the user signs up from the "Welcome to Kora page"? I'll comment on this issue if I receive it anytime soon.

**Comment by suuuth** [comment]
`however I am still waiting on the activation email for maybe 10 mins now`  This happened to me as well.  Upon clicking `request another email` I received both the initial email and the second email.

**Comment by suuuth** [comment]
"You have been invited by Root Person" was Ubuntu-Bold.  This has been corrected.  Confirmed font-weights have not been applied to this text.

**Comment by austintruchan** [comment]
> `however I am still waiting on the activation email for maybe 10 mins now` This happened to me as well. Upon clicking `request another email` I received both the initial email and the second email.

Okay, we should look into whats stopping the initial email. User shouldn't be expected to hit the "Send another email" button in order to get the email. Unless its assumed that this should just work when its live?

**Comment by suuuth** [comment]
> Unless its assumed that this should just work when its live?

I would not make that assumption, I am looking into this at the moment.

Also running into an error where you click `request another email` -> receive email -> click button in email to activate account -> whatever page this is loading seems to error consistently

You can still activate your account my manually copy/pasting the token, however once you do this and login, your account only has an email (and username?) set, and the user needs to edit their own account to add their first/lastname.  This happens regardless of what information the user tries to set up their account with.

**Comment by austintruchan** [comment]
Ok. please continue looking into this.

**Comment by suuuth** [comment]
Progress track:
- [ ] automatically send activation email when necessary
- [ ] fix activation button in activate email
- [x] fix issue of user not being able to set firstname, lastname, username, etc. on invited-register page

**Comment by suuuth** [comment]
There is an error that occasionally appears: 
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ZZTest_kevin_sutherl' for key 'projects_slug_unique' (SQL: insert into `kora3_projects` (`name`, `slug`, `description`, `updated_at`, `created_at`) values (ZZTest kevin.sutherl, ZZTest_kevin_sutherl, Test project for user, kevin.sutherl, 2018-11-28 20:54:08, 2018-11-28 20:54:08))`

I believe this won't be an issue on the live site.  I was able to fix this issue by logging out of the newly created account, logging in as Root, deleting the project referenced in the error, and logging back in on the new account.  I believe logging in on the new account creates a sort of 'placeholder' project, and this project already existed because i've been testing this for some time now

Another test was: see error -> log out -> login as 'Root' -> delete project AND new user -> re-invite AND re-create new user account -> activate account without error

Other than these errors I believe this branch is due for another review @austintruchan

**Comment by austintruchan** [comment]
Okay. 

- [ ] Add in the loading indicator after user hits the sign up button and the sign up is successful on the "Welcome to Kora" page. @Dev34 recently did this on the main signup page.

- [ ] Can we make the blue link green and ubuntu-medium?
<img width="577" alt="screen shot 2018-11-28 at 4 14 25 pm" src="https://user-images.githubusercontent.com/5408529/49182782-2bde5580-f329-11e8-95bd-177c5e1199b2.png">

- [ ] After hitting "Activate Account" from the email I was greeted with this error, but I believe that is the error you are referring to, where the test project already exists.
<img width="1635" alt="screen shot 2018-11-28 at 4 14 58 pm" src="https://user-images.githubusercontent.com/5408529/49182857-61833e80-f329-11e8-8db5-084c90644b7b.png">

**Comment by suuuth** [comment]
> After hitting "Activate Account" from the email I was greeted with this error, but I believe that is the error you are referring to, where the test project already exists.

Yep that's the error I was getting.  I believe this won't be present on the live site since that project wouldn't normally exist before the user creates their account.

**Comment by suuuth** [comment]
> Can we make the blue link green

Yes but then the user will not be able to click the link and will need to copy/paste the link in order to use it.  This is because gmail recognizes links within `<a href="..` and styles them manually.  To fix this, I can wrap the link in `<a href="#"`, where the `#` fools gmail into believing this is not a link and therefore does not override styles we apply.  You can also see evidence of this on the `invite` email you receive when invited to Kora, when you look at the email in `You have been invited by Root Person
(admin, anthon70@msu.edu)` section

**Comment by austintruchan** [comment]
> > Can we make the blue link green
> 
> Yes **but then the user will not be able to click the link and will need to copy/paste the link** in order to use it. This is because gmail recognizes links within `<a href="..` and styles them manually. To fix this, I can wrap the link in `<a href="#"`, where the `#` fools gmail into believing this is not a link and therefore does not override styles we apply. You can also see evidence of this on the `invite` email you receive when invited to Kora, when you look at the email in `You have been invited by Root Person (admin, anthon70@msu.edu)` section
> 
> This is also specific to gmail. I am not sure how other email clients will handle this, but if I wrap the link in an anchor link like i'm describing here then the link will look good on gmail (maybe other email clients too), but you most likely will not be able to click the link on any email client

Okay, Lets not worry about this then.

**Comment by suuuth** [comment]
Okay, I did apply the proper font to the link.  That much gmail does not seem to overwrite.

**Comment by austintruchan** [comment]
- [ ] With the "Welcome to Kora" page, the loading indicator seems to occur everytime I enter an input and tab to the next thing. Ideally this wouldn't happen. And after hitting the submit button, the loading indicator appeared for a second and then went away. Loading indicator should only appear after the user hits the signup button, and it should remain until the page redirects to the activate account page.

**Comment by suuuth** [comment]
Manually added the loading icon here.  Should behave properly

**Comment by austintruchan** [comment]
perfect!!!!
