### ISSUE TITLE
Fix "FIX ME" on Sign up Success page

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#343]
<img width="643" alt="screen shot 2018-10-18 at 10 14 06 am" src="https://user-images.githubusercontent.com/5408529/47174305-40691000-d2de-11e8-99c2-7ece56a3a8ba.png">

- [x] Ideally should auto-populate the root users email

**Comment by suuuth** [comment]
branch suth-343

**Comment by austintruchan** [comment]
seems to work?!
