### ISSUE TITLE
Update Kora Activation Email Link Styling

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#344]
<img width="557" alt="screen shot 2018-10-18 at 2 05 17 pm" src="https://user-images.githubusercontent.com/5408529/47174556-e9b00600-d2de-11e8-9e91-a151b91f0e63.png">

Update the styling of the "https://kora3.matrix.msu.edu/auth/activate" link to be the kora accent green, and ubuntu medium

**Comment by Dev34** [comment]
Added the kora accent green color and the link is now always clickable instead of just plaintext.

I added the Ubuntu-Medium font-family to the link, but it seems to look kind of strange. Is this what you're looking for?
![signupemail](https://user-images.githubusercontent.com/12753141/48278851-b44d9280-e41c-11e8-88a9-3d645bd88a2d.PNG)

This is on the activation-link-#344 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Well in that screenshot, none of the text is ubuntu, or ubuntu medium, and the activate account button is grey, and is spaced weird. I'll test for myself and see what I get.

**Comment by austintruchan** [comment]
First test didn't send the email at all ¯\_(ツ)_/¯

**Comment by austintruchan** [comment]
Okay, after hitting resend email it did go through, and looks good. If you could, make sure all the different kora emails that include text links / email links are the kora accent green, and ubuntu medium.

**Comment by austintruchan** [comment]
Wait. Actually the ubuntu font no longer renders in the ios or mac mail app for me, but does on my third party mac mail app. It used to render on both, lol. Strange. Not sure if its something you've done or something else entirely. But the link is infact green now. I think in the future / down the line we can play around with email styling moreso.

**Comment by fritosxii** [comment]
@austintruchan Hows this?

<img width="535" alt="Screen Shot 2019-06-25 at 9 53 47 AM" src="https://user-images.githubusercontent.com/4040076/60104296-2914d900-972f-11e9-9d91-f49ae8f37d8f.png">
