### ISSUE TITLE
Loading Indicators to Add (Growing List - Keep Open)

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#345]
Would like to have this issue remain open if possible so I can request additional loading indicators as I see them.

**Comment by austintruchan** [comment]
- [ ] Thanks for Signing up page, requesting another email

- [ ] User Profile Page when trying to switch to the permissions and record history tab

**Comment by Dev34** [comment]
Added the loading icon to those two spots.

This is on the loader-icon-#345 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looks good.

**Comment by austintruchan** [comment]
- [ ] Another one: When creating a new project permissions group

**Comment by Dev34** [comment]
Added the loading icon to the 'create new project permissions group' modal.

This is on the loader-icon-#345 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looks good. Lets also add one when creating a new form permission group.

**Comment by austintruchan** [comment]
- [ ] Also we could use one right after the user selects the Sign Up button from the register page and sign up is successful.

**Comment by Dev34** [comment]
Added loading icon to 'create new form permission group' modal submit and when the sign-up modal is successfully submitted.

This is on the loading-icon-#345 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Great job!
