### ISSUE TITLE
Single Project Empty State Missing

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#347]
The empty state for when a project has no forms seems to be missing for me. 
<img width="1310" alt="screen shot 2018-10-18 at 2 19 51 pm" src="https://user-images.githubusercontent.com/5408529/47175424-0c431e80-d2e1-11e8-8569-86121cbd1ede.png">

**Comment by austintruchan** [comment]
I believe this might only be for admins, I can see the empty state with my non admin account, but not for my admin account

**Comment by suuuth** [comment]
branch suth-347

**Comment by austintruchan** [comment]
Looks like its back!
