### ISSUE TITLE
Adding admins to new project / new form Update

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#349]
If possible, and for consistency with project permissions, lets add project admins / form admins when creating a new project / new form by firstname lastname instead of username.

<img width="910" alt="screen shot 2018-10-18 at 3 44 32 pm" src="https://user-images.githubusercontent.com/5408529/47179761-e1f75e00-d2ec-11e8-8061-dbbe522b72af.png">

<img width="897" alt="screen shot 2018-10-18 at 3 44 20 pm" src="https://user-images.githubusercontent.com/5408529/47179758-de63d700-d2ec-11e8-9bf5-c9071b09f291.png">

- [x] Also update the spacing above the description text for the Select Additional Form Admin Fields to have correct spacing

**Comment by suuuth** [comment]
branch suth-349

**Comment by austintruchan** [comment]
This looks good. This makes me wonder if its possible to allow the username to display alongside the first name and lastname as well. Like "Austin Truchan (atru22)", in the case that there are two people with the same name. Would something like that be possible?

**Comment by suuuth** [comment]
Yep!

**Comment by austintruchan** [comment]
Great! I would make that change to the form and project permissions as well when looking at a list of users to add to new or previously created permissions group.

**Comment by austintruchan** [comment]
Seems good. How is the list of users being organized? Would it be possible to organize them Alphabetically by firstname?

**Comment by suuuth** [comment]
I don't believe it is currently being organized any particular way.  Maybe by user ID.  I can certainly make the change to have it sort by alphabetical by firstname.

**Comment by suuuth** [comment]
dropdown menus are now sorted alphabetically by firstname with users lacking firstname lastname appearing at the top

**Comment by austintruchan** [comment]
Looks good!
