### ISSUE TITLE
Drag and Drop or profile pictures

### ISSUE THREAD

**Issue by mikelsav** [matrix-msu/Kora3#35]
Drag and Drop currently not supported

**Comment by fritosxii** [comment]
This needs to be fixed for all file inputs.

**Comment by fritosxii** [comment]
Reference #165 for edit user

**Comment by suuuth** [comment]
drag n drop works for adding files, however submitting throws another `call to member function on string` error.  Uploading with button and submitting does not throw this error.  File types seem to be the same from both methods as `image/jpeg`

**Comment by suuuth** [comment]
commenting out `initializeForm()` in `edit.js` allows us to upload new photos with the buttons, but prevents drag n drop.  uncommenting this function allows us to drag n drop, but we get the `member function` error as mentioned above.  Trying to upload the photo the normal way, we can select and input the photo, but uploading it throws a `status 200` error, which the script then calls `location.reload`

**Comment by suuuth** [comment]
seems like when I upload a file normally, this interacts with the `<input>` element associated with uploading photos, whereas drag and drop does not.  The latter method only interacts with the `<label>` element

**Comment by suuuth** [comment]
There were two issues here.  The first being that two separate Ajax calls were being triggered by the user pressing the `submit` button.  This broke the normal file upload, with normal referring to using the buttons to input a new file.  

The second issue was that `ajaxData.append('profile'...` did not populate the existing `profile` field, but rather created a new, identical, field to populate.  Deleting the existing, empty, `profile` field fixed this issue.  

Moving to code review

**Comment by austintruchan** [comment]
What page should I review this on? What branch?

**Comment by suuuth** [comment]
on branch `suth-35` on the edit-user page there is a drag and drop to edit profile pictures

**Comment by austintruchan** [comment]
Huh. Unfortunately everytime I tried to go to an edit user page, it would redirect me to the the users main profile page. This only happens on this branch.

**Comment by suuuth** [comment]
fixed routing issue.  Should be able to navigate to this page now

**Comment by austintruchan** [comment]
Okay. It seems to work, but as soon as I drop something in, it automatically submits the page. It shouldn't do that.

**Comment by austintruchan** [comment]
I am sad about safari though. I think that for now we should get this pushed, but should come back to safari eventually. 

The file uploaders are designed to encourage drag and drop, and will definitely cause confusion for safari users for when they just don't work as expected. Safari is apparently the second most widely used browser behind chrome. So its definitely worth seeking a solution.

**Comment by suuuth** [comment]
We could implement a visual change when Safari is detected to avoid this confusion you are talking about. This would ideally be a temporary fix for until safari-drag-n-drop is figured out

**Comment by austintruchan** [comment]
Also, drag and drop file fields need to be updated on all import pages as well. Import project, form, records etc.
