### ISSUE TITLE
Public Website Development

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#352]
Design for the public website has been finalized and approved! 
https://projects.invisionapp.com/d/main#/projects/prototypes/11945889

These designs are very similar to the design of the Arcs promo website, and I would use those as a starting point for these designs. Work with nick to get the arcs promo site set up.
The way the arcs promo site handles its mobile design can be reused for the kora promo site as well.

**Comment by austintruchan** [comment]
Mobile screen for home, and mobile screen for the mobile menu added:
https://projects.invisionapp.com/d/main#/console/11945889/336926525/preview
& https://projects.invisionapp.com/d/main#/console/11945889/336928431/preview

**Comment by austintruchan** [comment]
For button hover effects, we are actually going to do the same as the arcs promo site. Hovering will smooth transition the hovered button to full opacity, while moving the button up a few pixels. Comps have been updated to show on load opacities. 

Ghost buttons (buttons with borders) will have 80% border opacity on load, and filled buttons will have 90% background opacity on load. On hover they'll increase to 100%. Text within these buttons will remain at 100% opacity onload and on hover.

Links in the top navigation menu will be 80% text opacity on load (unless its the active page), and on hover 100% opacity.

**Comment by suuuth** [comment]
- [ ] keep nav sticking to top of browser
- [ ] make nav slide up/down animation more smooth for when user is scrolling fast

**Comment by suuuth** [comment]
K3 Promosite gitlab repo: https://gitlab.matrix.msu.edu/matrix/kora-promo

I believe you can review the live site from this link: http://robbie-72.matrix.msu.edu/~kevin.sutherland/kora-promo/home/

**Comment by austintruchan** [comment]
### HOME

- [ ] Not seeing hover effects for the pill buttons, like "Learn More", "Discover All Features", etc. "Hovering will smooth transition the hovered button to full opacity, while moving the button up a few pixels. Comps have been updated to show on load opacities."

- [ ] Watch the Video button should be the other green color. 

- [ ] For the first feature, and 4th feature listed, the according icon appears blurry and a slightly different color compared to the other featured icons? 
<img width="1006" alt="screen shot 2019-01-03 at 4 14 35 pm" src="https://user-images.githubusercontent.com/5408529/50661924-ab87c180-0f72-11e9-844d-e49ce79bd43b.png">

- [ ] Update the dropshadow on the "Out Now" badge. Should be updated to what is should be in invision now. 

- [ ] Let's Remove the box shadow from the heart in the footer. Comps have been updated with new asset.

- [ ] Landing section text content should be left aligned at wider widths.

- [ ] "Learn More" & "View on Github buttons should be closer together at wider widths. 

- [ ] Hold on the desktop layout for longer as the size of the browser reduces. We can do a number of things: 

- Reduce the space between the menu links as the browser condenses, and hold on to showing all the links for as long as possible.
- Condense the menu links into the hamburger icon but still keep the desktop layout.
- Have the screenshot imagery fall off the side of the browser, similar to what the arcs promo site does.

- [ ] Need a gradient overlay on top of the screenshot image, inorder to create some depth between the screenshot and the features section. This overlay can be seen on the invision comp.

**Comment by austintruchan** [comment]
### About
---

- [ ] Weird box around image. I think because its an svg. I would just use any old image of nature and fit it in that box with the box shadow and rounded corners. Then we can mess with how the image is cropped as well.
<img width="974" alt="screen shot 2019-01-03 at 4 40 19 pm" src="https://user-images.githubusercontent.com/5408529/50663071-71b8ba00-0f76-11e9-9dad-412c12e9d92d.png">

**Comment by austintruchan** [comment]
## Features

- [ ] Looks like the folder icon and the form icon are blurry on this page as well. I feel like this might just be a weird mac bug.

- [ ] Add a bit more space, maybe 3px, between the icon and the featured name for the last section.
<img width="1060" alt="screen shot 2019-01-03 at 4 52 52 pm" src="https://user-images.githubusercontent.com/5408529/50663630-4afb8300-0f78-11e9-8f6b-1e835cb2295c.png">

- [ ] Make this last section columns a bit wider apart so the section as a whole is a bit wider.

- [ ] At certain widths, the last section appears to be off center: 
<img width="512" alt="screen shot 2019-01-03 at 5 11 25 pm" src="https://user-images.githubusercontent.com/5408529/50664322-a6c70b80-0f7a-11e9-9dd8-6782144ab0de.png">


- [ ] I think the box shadow you have for the Feature boxes in the first section is way too huge, and is creating a weird gradient effect on the entire text and image container. Update based on what is in invision.

- [ ] When the first section, featured boxes go into one column, make sure the title of the feature and according text always appears above the image, instead of below it. 

- [ ] When the first section, featured boxes go into one column, have the text content and image content be left aligned.

**Comment by austintruchan** [comment]
## Support

- [ ] Lets have the entire boxes for Installation guide, user documentation, etc be clickable, and activate the hover effect for the white pill buttons.

- [ ] White pill buttons look to have too much box shadow. Confirm you are using what is suggested in invision.

- [ ] The h3 titles for each box are much too big. Refer to Invision for sizing.

**Comment by austintruchan** [comment]
## Contact

- [ ] Update spacing above "We're happy to help" to match the same spacing that is directly below the landing section that is there on the support page. 
<img width="1167" alt="screen shot 2019-01-03 at 5 16 10 pm" src="https://user-images.githubusercontent.com/5408529/50664536-64ea9500-0f7b-11e9-94d3-0b56891c4743.png">

- [ ] Add same spacing below the contact form box as well, this spaceing should match the spacing below the 4 boxes on the support page. 

- [ ] Placeholders in form are getting a bit cropped. Seems to be a safari thing I think.
<img width="418" alt="screen shot 2019-01-03 at 5 17 21 pm" src="https://user-images.githubusercontent.com/5408529/50664606-abd88a80-0f7b-11e9-9951-790b7f1f12da.png">

- [ ] We will need to get this contact form actually working. For now can we set it up to test emails and send emails to truchan@msu.edu for testing purposes?

- [ ] we will need to create some sort of success state to inform user their message was sent. I'll create a todo for myself to mock this up.

**Comment by suuuth** [comment]
- all icons on the Home page use the same color (#283c46), the folder icon does appear blurry for me while the form icon does not
- confirmed box shadow on the About page is what is on invision
- confirmed box shadow on Features page is also what is on invision
  - adjusted box shadow for both of these to be what is on the arcs promo site
- reduced padding and line-height on contact form input fields.  This should help reduce cropping of placeholder text

Still working on getting the contact form working

**Comment by austintruchan** [comment]
## Home / Menu / Footer

- [ ] When at this width, have the learn more, and view on github buttons have a bit more space between them. 

- [ ] lets hide the watch the video for now. We may need to reimplement it in the future, but at first we won't need it. 

- [ ] Align top of mobile menu to bottom of the fixed header, and the view on github button in the mobile menu is wonky: 
<img width="309" alt="screen shot 2019-01-07 at 3 12 13 pm" src="https://user-images.githubusercontent.com/5408529/50791086-c158f780-128e-11e9-9c17-b1b0db281755.png">

- [ ] have the mobile menu auto close if the menu is open and the browsers width is expanded. 

- [ ] For the see what's new button, lets have a the same hover effect that is on the kora 3 interface, where the right arrow moves to the right a bit. 

- [ ] Add a bit left and right spacing around the heart in the footer. margin: 0 4px; looks good.

**Comment by austintruchan** [comment]
## Contact

- [ ] Break the layout into one column around 900px.

**Comment by suuuth** [comment]
contact form is up and running.  You can test it from this link -> http://peach.matrix.msu.edu/~kevin.sutherland/kora-promo/contact/ and this will send an email to truchan@msu.edu

All other style changes have been addressed and are ready for review

**Comment by austintruchan** [comment]
- [ ] Lets also reduce the margin top for the .Home header .flex>div:first-child h3 (lol) down to 30px on the widest break point, and down to 20px at 1050px and below.

**Comment by suuuth** [comment]
- box shadow on `view on github` button on sidemenu removed
- h3 margins reduced on home page
- entire `whats-new` block links to the proper page now

**Comment by austintruchan** [comment]
- [ ] On contact page, update so the form block is roughly 2/3rds the width of the page like on the comp. 

- [ ] On contact page, Have the "Send Your Message" button right aligned.

- [ ] On contact page, Update the  inputted text based on updated comp: https://projects.invisionapp.com/d/main#/console/11945889/334223597/preview

- [ ] And For the success message, could we simply have the general kora3 notification pop in and say, "Message Sent!"

**Comment by austintruchan** [comment]
- [ ] On the features page, remove the cursor pointer on hover for the features in the second and third sections.

Other than that and the contact success message, I think we're good to go!

**Comment by suuuth** [comment]
All set for another review!

**Comment by austintruchan** [comment]
- [ ] For the mobile menu, lets actually have it appear full height, and be above the fixed header and hambrger icon.

- [ ] Main Kora Logo was updated in the comp now so the text is outlined and looks normal on different browsers. Please update. 

- [ ] On the home page, for the see what's new button, lets make sure that is ubuntu-medium

- [ ] For the contact form, lets make sure we have all the fields set to required, and have default browser validation. So if I hit the send button I should see some default browser validation behavior to let me know that I need to fill in the email, etc.

- [ ] Update the success notification with updated box shadow (comp has been updated with new box shadow to look better on the dark green background)

- [ ] Have the notification stay until the user dismisses it or the user leaves the page. 

- [ ] decrease the padding of the form when the browse width is 500px and below.

**Comment by suuuth** [comment]
This should be all set for another review!

**Comment by austintruchan** [comment]
I realized we are using fontweights for a lot of things.

- [ ] Remove all fontweights!
- [ ] Any case of using font-weight: bold should be replaced with the actual font for ubuntu medium.

- [ ] In the footer, for 'footer .middlewrap div:first-child' for widths under 600px, update the margin bottom to 50px.

Any luck with the blurry icons?

**Comment by suuuth** [comment]
Okay, all icons now share the same color.  Opening up the svg files, I found filters and shadows defined that I was able to remove to get everything looking the same.  All set for another review

**Comment by suuuth** [comment]
- reduced folder width from 82px to 67px
- reduced folder height from 76px to 61px

 All set for another review

**Comment by austintruchan** [comment]
Okay. 

- [ ] Folder icon will need to be updated so the borders remain the same in proportion to the others. I have updated the svg on invision for the folder to be smaller with same border proportions, and I removed the shadowing from that svg as well. 

- [ ] Update linear gradient on the screenshot image of the home page to be 
`linear-gradient(0deg, rgba(22,42,51,0.1) 0%, rgba(21,39,48,0) 10%)`. Reducing the 0-100 to 0-10% looks a bit nicer.

**Comment by suuuth** [comment]
Done! All set for another review

**Comment by austintruchan** [comment]
Looks good!

- [ ] On the contact page, have the github issue button open up in a new tab

- [ ] Actually for all links that link to github, have them open up in new tabs. 

- [ ] Actually do this for all links that link outside of the kora promo site, including the twitter and matrix links in the footer.

- [ ] Wait, make the matrix logo in the footer link to matrix and open in a new tab. 

## Mobile Updates

- [ ] On the home page and features page, for the features in the three coloums, it looks like the the last three features on both pages have smaller spacing between the features on mobile than the other features do: 
<img width="316" alt="screen shot 2019-01-15 at 1 41 39 pm" src="https://user-images.githubusercontent.com/5408529/51202064-d1df2280-18cb-11e9-9891-d9afd546b3ee.png">

- [ ] On the updates page on mobile, reduce the padding for each update section. You could also reduce the spacing around the grey background for each update section so there is more space within.

- [ ] On the features page on mobile, reduce the padding for each of the first 6 feature sections. You could also reduce the spacing around the grey background for each feature section so there is more space within.

- [ ] For the logo on mobile, Update the margin left so it's 5px. 

- [ ] On the Support page on mobile, make the same adjustments to the spacing around the grey background for each feature section so there is more space within that is made to the updates and feature pages .

**Comment by suuuth** [comment]
- all github links open in new tabs
- added matrix link in footer
- matrix and twitter links in footer open in new tabs
- feature items had inconsistent margin values when they broke to single and double column layouts.  This has been fixed
- logo margin updated
- for the 'reduce padding on mobile', each of these items' padding values drop to `padding: 25px` around 768px browser width

Ready for another review!

**Comment by austintruchan** [comment]
Ok! I think we're good to go. Now Accessibility!

- [ ] Grab the Wave Chrome Extension to test accessibility https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh?hl=en-US

- [ ] Fix all the red errors that appear in the wave test.

- [ ] Fix as many yellow alerts that you can.

**Comment by austintruchan** [comment]
Accessibility checks out and I think we're looking good. 

- [ ] I noticed the learn more button on the home page and the view on github button in the navigation have green box shadows I believe. I updated the comp so the proper shadowing shows up in the inspect.

**Comment by suuuth** [comment]
Buttons have been updated.  Box shadow has been changed to this: `0 3px 5px 0 rgba(21,39,48,0.1)` from this: `0 5px 16px 0 rgba(21,39,48,0.09), 0 13px 45px 0 rgba(4,182,175,0.44)`.

All set for another review

**Comment by austintruchan** [comment]
I believe we're good to go. Awaiting instruction on next steps.

**Comment by fritosxii** [comment]
Migrated all of Kevin's changes to the master branch of that repo. Also added the logo in #570 . Now we wait for the launch plan and the initial content plan...
