### ISSUE TITLE
Add tooltip on the (X) icon for projects within tokens on the token management page

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#353]
<img width="135" alt="screen shot 2018-10-19 at 10 54 11 am" src="https://user-images.githubusercontent.com/5408529/47227956-09543680-d392-11e8-952a-527a8ca97c9b.png">

- [ ] Add tooltip above the (x) icon on hover that reads "Remove Project from Token"

**Comment by Dev34** [comment]
Added the tooltip

This is on the token-tooltip-#353 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
I would have the tooltip be centered above the (x) icon, instead of left aligned.

**Comment by Dev34** [comment]
Centered the tooltip

Please run ```compass compile```
This is on the token-tooltip-#353 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
looks good!
