### ISSUE TITLE
Language Dropdown

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#355]
<img width="185" alt="screen shot 2018-10-22 at 1 33 13 pm" src="https://user-images.githubusercontent.com/5408529/47308248-0d38c080-d5ff-11e8-8f54-96ad9b0cbca5.png">

Somewhere down the line, the language dropdown seems to have stopped working / opening. 

- [x] Bring back the functionality of the drawer.

I believe @mikelsav set up this drawer initially.

**Comment by suuuth** [comment]
branch suth-355

**Comment by austintruchan** [comment]
Looks good. I realize why it may have been hidden, because we just have english atm. @fritosxii What is the plan for having the multi language support for Spanish and french? Should we just remove language dropdown for the time being, or add another option for "More languages coming soon" maybe?

**Comment by fritosxii** [comment]
We are pushing back language support. I like the idea or the More languages coming soon option

**Comment by austintruchan** [comment]
Ok. @suuuth add an option under english for "More Languages Coming Soon" that is non hoverable / non clickable.

**Comment by suuuth** [comment]
This should be good 2 go

**Comment by austintruchan** [comment]
- [ ] Set "More Languages coming soon" to .4 opacity

- [ ] Add a break between "More Langagues" and "Coming soon, so that it breaks to two lines.

**Comment by suuuth** [comment]
Done!

**Comment by austintruchan** [comment]
Good!
