### ISSUE TITLE
Custom Permission Groups Trash Issue

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#361]
<img width="874" alt="screen shot 2018-10-23 at 1 42 28 pm" src="https://user-images.githubusercontent.com/5408529/47379691-99afb580-d6c9-11e8-9a2d-471fac284e26.png">

- [ ] Trash  icon and the permissions group options should be aligned.

**Comment by suuuth** [comment]
fixed on both the project and form permissions pages

**Comment by austintruchan** [comment]
looks good!
