### ISSUE TITLE
Import Record Success Page Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#362]
A few updates could be made to enhance the UX of the success pages after importing records.

- [x] All Records Successful: https://projects.invisionapp.com/d/main#/console/11107725/325343347/preview

- [x] Some to no Records Successful: https://projects.invisionapp.com/d/main#/console/11107725/325343348/preview

**Comment by fritosxii** [comment]
Here is my proposal for a new layout that includes all three links for when there are failed records

The button will say JSON or XML depending on the type they uploaded with

<img width="953" alt="screen shot 2018-11-28 at 9 24 48 am" src="https://user-images.githubusercontent.com/4040076/49158767-f0279980-f2f0-11e8-9e01-cbe006e1455a.png">

**Comment by austintruchan** [comment]
🤢🤮

**Comment by austintruchan** [comment]
Updated the comp a bit: https://projects.invisionapp.com/d/main#/console/11107725/325343348/preview

**Comment by austintruchan** [comment]
holy crap it worked!
