### ISSUE TITLE
All Projects Page Empty State Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#363]
<img width="1310" alt="screen shot 2018-10-24 at 12 32 52 pm" src="https://user-images.githubusercontent.com/5408529/47450200-9d5b3f00-d792-11e8-824d-b89124b0b245.png">
^ All Project empty state currently looks like, but should look like: 
  
https://projects.invisionapp.com/d/main#/console/11107725/251340897/preview

  
- [ ] Update Icon

- [ ] Update text based on comp

- [ ] Make sure links in this text are ubuntu medium and the accent green

- [ ] Let's also have it so that if the user isn't an Admin, remove the part about creating a new project, so it would read "Request permissions to a project to get started."

**Comment by Dev34** [comment]
I'm aware of the icon replacement process, but how do I get the new .svg for this icon? I can't find it anywhere on Invision.

**Comment by austintruchan** [comment]
Whoops, the icon wasn't set for export before, but you should be able to download it directly from the invision inspect page: https://projects.invisionapp.com/d/main#/console/11107725/251340897/inspect

**Comment by Dev34** [comment]
@austintruchan Can I get rid of the 'Request permissions to a project' link for [https://projects.invisionapp.com/d/main#/console/11107725/251340897/preview](url). I think this comp is supposed to be the admin view for this page, but I think admins automatically get access to all the projects

**Comment by austintruchan** [comment]
Yes you can, but it needs to remain for non admins. 

Ok, so we need two states of this empty state, one for admins and one for non admins. 

For admins the description can read: 
"No projects exist."
"Create a new project to get started." - where "Create a new project" is a link to do so.

For non admins the description can read:
"Either you don’t have permissions, or no projects exist."
"Request permissions to a project to get started." - where "Request permissions to a project" is a link to do so.

**Comment by Dev34** [comment]
Updated the empty states for admin and non-admin users. (texts, fonts)
Added the new icon and enlarged it slightly so it looks about the same size as the comp.

The old icon is used in several places in Kora. I'm assuming you didn't want this new icon to also replace where the old icon is used in these other places, so the icon change that I've made is local to the empty state of projects page. If that's not what you wanted, I can change it so the new icon replaces the old icon everywhere in Kora.

If you want to see the empty state, but don't want to delete all your projects, then you can uncomment the PHP code in Kora3\resources\views\projects\index.blade.php on line 26.

Please run ```compass compile```
This is on the projects-empty-state-#363 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
I'm thinking this looks good!
