### ISSUE TITLE
Create New Document Field Error

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#368]
When creating a new document field, the page will error out if I open the advanced field options drawer before creating it. If I do not open the advanced field options drawer, it is fine. Even though the page errors out with the advanced field options drawer open, the field is still created.

**Comment by Dev34** [comment]
Error was occurring due to the filetype input being left empty in advanced options. It is now fixed.

This is on the document-field-error-#368 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Seems to work now!
