### ISSUE TITLE
Empty State for "Association Search Configuration" for Association New Field & Edit Field

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#374]
We just need some text inside the box that says "No Forms Associated", instead of a blank box. 
<img width="891" alt="screen shot 2018-11-12 at 3 04 47 pm" src="https://user-images.githubusercontent.com/5408529/48374542-3515c400-e693-11e8-8eab-10ad910552e5.png">

**Comment by Dev34** [comment]
Added 'No Forms Associated' text to Association Search Configuration for New Field and Edit Field.

Please run ```compass compile```
This is on the empty-#374 branch (pushed to GitHub)

**Comment by Dev34** [comment]
Updated the color, I _think_ I picked the right one.

Please run ```compass compile```
This is on the empty-#374 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
nope. You want to use the $base-text variable

**Comment by austintruchan** [comment]
Looks good!

**Comment by Dev34** [comment]
These changes were ported from development to deconstruct last week, and have today been tested in the deconstruct environment. Behavior in deconstruct environment is as expected, so a pull request has been made.
