### ISSUE TITLE
Add form empty state to project cards on the All Projects Page.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#375]
I believe this may have been implemented before, but I don't see it live. If a project doesn't have any forms, we should have some text in the project cards next the "Forms:" label, that says "This project has no forms yet."

**Comment by austintruchan** [comment]
- [ ] Remove period from THis project does not have any forms

- [ ] Change to be the normal kora text color, and ubuntu regular.

- [ ] If possible, reduce the left spacing of "This project does not have any forms" so that the space between "Project Forms" and "This project does not have any forms" is the same as "Project Admins:" and "Root Person"

**Comment by suuuth** [comment]
Done.  For the 3rd item, I reduced this spacing for every instance, not just when there are no forms.  Not sure if this was what you intended me to do or if this was meant to be case-specific

**Comment by austintruchan** [comment]
It's perfect!
