### ISSUE TITLE
Multi-Select & Single Select Dropdown Chevron

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#379]
<img width="885" alt="screen shot 2018-11-13 at 10 11 10 am" src="https://user-images.githubusercontent.com/5408529/48422400-8f169800-e72c-11e8-9bf1-21d5f71456a5.png">

- [x] If possible update this chevron so that it looks and behaves like the dropdown chevrons on project cards. Should have reduced opacity, and on hover have increased opacity and scale up in size. Should look and behave like: 
<img width="876" alt="screen shot 2018-11-13 at 10 11 18 am" src="https://user-images.githubusercontent.com/5408529/48422491-c38a5400-e72c-11e8-9caf-e4bc241e8faa.png">

- [x] Chevron could come down a couple of pixels too so that is more vertically centered.

**Comment by suuuth** [comment]
branch suth-379

**Comment by austintruchan** [comment]
Any luck with having the reduced opacity on the chevrons? Similar to how the project cards handle the chevrons opacity.

**Comment by suuuth** [comment]
Opacities are now set!

**Comment by austintruchan** [comment]
- [ ] Have the opacity increase up to .8 on hover, instead of up to 1.

**Comment by austintruchan** [comment]
Its beautiful!
