### ISSUE TITLE
Update Timezone to be relative to user

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#380]
You can see at the bottom of a single record page, the timestamps are listed for creation and last updated. These stamps are in GMT. Would it possible to change them relative to where the user is? That or we should post "GMT" after the time stamp.

**Comment by suuuth** [comment]
Added some javascript to read, adjust, and return date/time relative to the timezone the user is in.  Also added the timezone name to this text.  Can be seen on branch `suth-380` at the bottom of any single record page

**Comment by austintruchan** [comment]
Does the timezone name change dynamically based on location? or is it always EST? Sounds like its dynamic just am curious. Also could we do the acronyms for the timezones instead of the full name?

**Comment by suuuth** [comment]
Yep I can add a bank of timezone acronyms to match up with and replace the full name.  The timezone changes based on location.  I wish I could explain how it knows where the user it but the only explanation offered from the documentation that I could find is roughly this --> `javascript knows the user's location from system settings` [read more here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset)

**Comment by suuuth** [comment]
Found a way for javascript to convert the full time zone name to an abbreviated version.  All set for review

**Comment by austintruchan** [comment]
seems good!
