### ISSUE TITLE
Update text of "Create Test Record" button to be "Create Test Record(s)"

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#381]
Update text of "Create Test Record" button to be "Create Test Record(s)" on the edit form information page. 
<img width="898" alt="screen shot 2018-11-13 at 10 35 07 am" src="https://user-images.githubusercontent.com/5408529/48424054-d2263a80-e72f-11e8-9195-8b14e104f8b0.png">

**Comment by suuuth** [comment]
branch suth-381

**Comment by austintruchan** [comment]
you did it!

**Comment by suuuth** [comment]
Woohooo!
