### ISSUE TITLE
Unable to upload MP3 File to playlist/audio field [Safari big]

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#382]
Tried multiple mp3 files on multiple projects and forms, on my dev, and on kora3.matrix.msu.edu, but I am unable to upload mp3 files to the playlist field when creating a record. Maybe its just me?

<img width="919" alt="screen shot 2018-11-13 at 4 40 10 pm" src="https://user-images.githubusercontent.com/5408529/48444741-cf910880-e762-11e8-81b4-b74fe396938b.png">

Here are some of the files I was trying to upload: 
[mp3s.zip](https://github.com/matrix-msu/Kora3/files/2578243/mp3s.zip)

**Comment by fritosxii** [comment]
Looks like safari is having an issue checking the MIME types of the file against the MIME standards for mp3. Since it is a safari only issue, we will delay this to 3.1

**Comment by fritosxii** [comment]
Turns out safari interprets the file as audio/mpeg instead of audio/mp3. Wrote some code to compensate for it.
