### ISSUE TITLE
Safari arrow bug for gallery

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#385]
The arrows in safari are slightly off center, because safari...

![image](https://user-images.githubusercontent.com/4040076/48733500-da3f1800-ec10-11e8-9735-19c002c01e8e.png)

**Comment by suuuth** [comment]
centered these icons with `position:absolute`.  Can be seen on branch `suth-334` on this page `/public/projects/199/forms/407/records`

**Comment by austintruchan** [comment]
the right chevron could move to the right by 3px

**Comment by austintruchan** [comment]
ok looks good!
