### ISSUE TITLE
Editing Records with Many Pages - Include Page Horizontal Page Scrolling

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#386]
The horizontal page scrolling should be present when editing a record that contains many pages, just like the new record page does.

The horizontal page scrolling: 
<img width="263" alt="screen shot 2018-11-20 at 2 29 22 pm" src="https://user-images.githubusercontent.com/5408529/48797709-eee2e500-ecd0-11e8-9d5c-9078c2c52c55.png">

Eg: http://robbie-72.matrix.msu.edu/~nicholas.mikelsavage/Kora3/public/projects/199/forms/248/records/9327/edit

**Comment by suuuth** [comment]
branch suth-386

**Comment by suuuth** [comment]
`'/assets/javascripts/records/tabs.js'` was being referenced in record-create's javascripts section, rather than in the `partials.records.javascripts` partial.  The script is now in the `partials.records.javascripts` partial which seems to fix the issue
