### ISSUE TITLE
Remove Empty State on Form Pages if a Field is dragged onto a new page

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#390]
In this example, a couple of fields were dragged into a new form page, yet the empty state remained. This is the same if using the arrows as well. The empty state does go away on refresh, but if possible, would be nice if it went away after a field is dragged onto it, and if possible, have the empty state return when all fields are dragged off of it. 
<img width="888" alt="screen shot 2018-11-26 at 1 39 36 pm" src="https://user-images.githubusercontent.com/5408529/49037079-58f30280-f187-11e8-957b-54e4a86a4ef0.png">

**Comment by suuuth** [comment]
branch suth-390

**Comment by suuuth** [comment]
Field empty-states are now always present on this page, and we show/hide them as the user interacts with the page rather than just when the page is loaded.

**Comment by austintruchan** [comment]
it works!
