### ISSUE TITLE
New Field Layout Fix

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#391]
<img width="1104" alt="screen shot 2018-11-27 at 4 09 57 pm" src="https://user-images.githubusercontent.com/5408529/49111732-f66d3580-f25e-11e8-92d3-66537508be50.png">

Page header content should be left aligned with the page content below. I believe the page content is thinner than it should be. Compare with other pages and match.

**Comment by suuuth** [comment]
branch suth-391

**Comment by suuuth** [comment]
Page content was thinner than it should be due to extra padding existing on the edges of every element inside the main page content section.  Should be fixed now

**Comment by austintruchan** [comment]
Looks good!
