### ISSUE TITLE
Create / Edit Record Page With Sidebar Open Layout Issues

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#399]
Around widths of 875px to 975px with the sidebar open, the create and edit record pages layout falls off the left side of the window. 

<img width="969" alt="screen shot 2018-11-29 at 4 13 56 pm" src="https://user-images.githubusercontent.com/5408529/49252411-fe111380-f3f1-11e8-8b7e-dea846a58535.png">
<img width="981" alt="screen shot 2018-11-29 at 4 14 01 pm" src="https://user-images.githubusercontent.com/5408529/49252417-ffdad700-f3f1-11e8-87fc-2561f2b677ce.png">

**Comment by suuuth** [comment]
Only happens on pages with a wide `.content-sections-scroll` element.  Issue is related to this element having `display:flex` applied where the flex container refuses to shrink with the page

**Comment by suuuth** [comment]
branch suth-399

**Comment by suuuth** [comment]
Added a media query in `app.scss` to address this
