### ISSUE TITLE
Edit token modals, User can select none as the token type. 

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#4]
Users should not be able to select zero token options, and one token should always be selected.

**Comment by Dev34** [comment]
Enforced rule: Users must keep at least one token option selected. If they try to unselect their last checked option, it won't do anything.
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/tokens

**Comment by austintruchan** [comment]
Still seeing the issue. Should I look in a certain branch?

**Comment by Dev34** [comment]
This is on the edit-token-modalfix branch

**Comment by austintruchan** [comment]
Editing a token is good. I am not able to select no tokens when editing.

We should also implement this for when creating a new token as well. So the user has to select at least one token type option before being able to commit it.

**Comment by Dev34** [comment]
@austintruchan If the user opens the create token modal, should the button be changed in any way to reflect that they cannot go through with creating the token until they select at least 1 checkbox? Or, should one option automatically be selected?

**Comment by austintruchan** [comment]
@Dev34 I updated the comps a bit to reflect what will happen. https://projects.invisionapp.com/d/main#/console/11107725/242825222/preview

No change to the selects initially, but if the user tries to hit the create button, a validation error will appear. Speak with Anthony for further advice on how to implement form validation.

**Comment by Dev34** [comment]
Enforced rule: Users must keep at least one token option selected in the Create Token modal. If they try to unselect their last checked option, it won't do anything.

Per Anthony's request:
Added real-time validation to the token name input which is triggered by focusing on that input and then shifting focus, so the validation error appears immediately after finishing editing that input.
Added whole-form validation upon submit on the client-side and server-side.

Validation warnings are displayed per the comp, and opacity change is applied to the button.

This is on the token-validation-#4 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
hmmm. I'm seeing the validation error, however they aren't styled. I refreshed cache and am testing in chrome as well. 

<img width="836" alt="screen shot 2018-06-19 at 2 51 24 pm" src="https://user-images.githubusercontent.com/5408529/41618105-40c80c76-73d0-11e8-984d-3147382bb093.png">

**Comment by Dev34** [comment]
@austintruchan Could you try running 'compass compile' and then checking again? I had the same issue when I was pulling in styling changes earlier and that fixed it

**Comment by austintruchan** [comment]
Okay. I see it now. Lets actually update the font to be size 14px, and to have the font be ubuntu medium... for the error text.

**Comment by Dev34** [comment]
Changed font to Ubuntu-Medium and changed font size to 14px

This is on the token-validation-#4 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41727496-7a960d9a-7542-11e8-92af-33499a648b0b.png)
