### ISSUE TITLE
See if we can stop the extra space from appearing when typing in a caption in a gallery field

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#405]
If possible, stop the extra space from appearing when typing in a caption.
<img width="880" alt="49399305-f1046500-f70e-11e8-93f4-d5cafb9094c9" src="https://user-images.githubusercontent.com/5408529/49406029-5f065780-f722-11e8-89c1-767133a1af2c.png">

**Comment by suuuth** [comment]
branch suth-405

**Comment by austintruchan** [comment]
Holy cow it works!!!
