### ISSUE TITLE
Changes to Date Select Field Name Settings

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#406]
Would like to request some changes to the Date Select Field Name Settings (https://projects.invisionapp.com/d/main#/console/11107725/250270205/preview):

- [x] Change "Select Era" to "Select Calendar/Date Notation"
- [x] add BP as an option
- [x] add KYA BP as an option
- [x] selecting either BP should disable the day and month dropdowns
- [x] Rewrite search/advanced search to handle the different types

**Comment by fritosxii** [comment]
@austintruchan Not sure if this would involve any design beyond adding another radio button for the era.

Programming wise, selecting BP should disable the day and month dropdowns

**Comment by austintruchan** [comment]
@fritosxii Simply adding another radio button will work fine.

**Comment by suuuth** [comment]
- [ ] Change "Select Era" to "Select Calendar Notation"
- [ ] add BP as an option
- [ ] selecting BP should disable the day and month dropdowns

branch suth-406

**Comment by fritosxii** [comment]
On pause till decision is made on potential 4th era

**Comment by watrall** [comment]
add KYA BP as the additional notation. (KYA BP is thousands of years before present and is represented by a simple number as opposed to a year...like BP.  so, 100 KYA BP is 100,00 years before present, where BP is represented by a year...5065 BP)

Change "Select Era" to "Select Calendar/Date Notation"

**Comment by fritosxii** [comment]
BPs added as well as search parameters
