### ISSUE TITLE
Updates to Date Select on Create / Edit Field & Create Edit Record

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#411]
- [x] Update border hover effect to expand full width of date column:
<img width="319" alt="screen shot 2018-12-04 at 4 20 15 pm" src="https://user-images.githubusercontent.com/5408529/49473837-1b265780-f7e1-11e8-864d-9ea4686b5a72.png">

- [ ]  Some clipping on the arrow icon. Arrow icon gets slightly cropped.

- [x] Opening a drawer will remove the right border from the field: 
<img width="310" alt="screen shot 2018-12-04 at 4 20 21 pm" src="https://user-images.githubusercontent.com/5408529/49473910-4f017d00-f7e1-11e8-8665-4a5601d8ebf2.png">

- [ ] Add 5px below the "Select Era"

**Comment by suuuth** [comment]
Branch: `suth-411`

**Comment by suuuth** [comment]
I don't see a 'select era' field or arrow icons cropping/clipping.  These may have been fixed already by someone else. 

Date inputs no longer have space between them, and the border-right style disappearing has been fixed.  Ready for review.

**Comment by austintruchan** [comment]
Nice, yes I believe all is better.

Last thing I noticed is to have the 'X' icon when a date is applied to be at the lowered opacity (same as the chevrons next to it), and transition to the higher opacity on hover. You could also have these grow a bit on hover, same as the chevron. These hover effects would only apply if you hover directly on the 'X', instead of the whole input as the chevron does.

**Comment by suuuth** [comment]
'X' button now has `opacity: 0.6;` applied.  On hover, this button grows a bit larger, and has `opacity: 1` applied with a smooth transition.  Ready for review

**Comment by austintruchan** [comment]
- [ ] For the border radiuses that shouldn't exist, they seem to do. I was able to remove them by telling the radiuses that shouldn't exist to be 0. eg:     border-top-left-radius: 0;    border-bottom-left-radius: 0;

- [ ] Update the positioning of the 'X' to be right: 50px and top:18.5px

- [ ] There used to be a mobile layout for this date field where the columns of the field would stack. It is no longer there. Looked like so: 
<img width="839" alt="screen shot 2019-03-07 at 10 35 50 am" src="https://user-images.githubusercontent.com/5408529/53968329-d1415c00-40c4-11e9-8104-d30444df148c.png">

**Comment by suuuth** [comment]
Which border-radii specifically need to be removed?  Do these need to be removed when the dropdown is opened, closed, or both?  Is this only for the default-date input dropdowns, or is this meant for all of the dropdowns on this page with this green border?

**Comment by austintruchan** [comment]
Sorry, for the very left input, the right two border radiuses should be 0. For the middle input all the radiuses should be 0. For the very right input, the left two border radiuses should be 0.

**Comment by austintruchan** [comment]
We will see how that looks when they dropdowns are opened.

This is only for the date field, where the three inputs are all in one row.

**Comment by suuuth** [comment]
Okay!  The border-radii have been set as requested.  Styles apply for both on hover and when the dropdown is opened/selected.  This can be seen on both of these pages:
`/Kora3/public/projects/199/forms/248/fields/1306/options`
`/Kora3/public/projects/199/forms/248/advancedSearch`

All set for review

**Comment by austintruchan** [comment]
Looks good!
