### ISSUE TITLE
Admin Invites User Email - Remove Personal Message if no Message Exists

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#412]
<img width="685" alt="screen shot 2018-12-04 at 10 42 42 am" src="https://user-images.githubusercontent.com/5408529/49474054-b28baa80-f7e1-11e8-8f87-318bce72e30e.png">

If the admin didn't include a personal message, remove the "" and the spacing made for the personal message.

**Comment by suuuth** [comment]
branch suth-412

**Comment by austintruchan** [comment]
This works! but...

- [ ] Update spacing around the personal message to how it used to be, if a personal message is included.
<img width="815" alt="screen shot 2018-12-06 at 11 17 40 am" src="https://user-images.githubusercontent.com/5408529/49596630-c43b9200-f948-11e8-9329-380b97b38da1.png">


- [ ] I'm not sure where it went, but I noticed the notification for successfully inviting a user did not appear for me.

**Comment by suuuth** [comment]
The spacing issue ended up being a simple css fix, just had to remove the '>' operator.  The notification however appears consistently for me.  Looking at the code, it appears that as long as everything works and the email is sent, the notification should appear.  Could I get you to look at this once more?

**Comment by austintruchan** [comment]
Okay, emails look good.
but yeah i'm still not seeing the notification for successful invite. I am seeing the notification for successful deletion of user however. Not sure whats up.

**Comment by suuuth** [comment]
I think I may need to sit down with you to see what is going on since the notification seems to work on this side of the wall

**Comment by suuuth** [comment]
- [ ] add warning notification if email fails to send

**Comment by fritosxii** [comment]
Lets go ahead and push it real good
