### ISSUE TITLE
Add Tooltips to Fields Containing Media on Single Record and Record Card

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#413]
<img width="824" alt="screen shot 2018-12-04 at 4 30 52 pm" src="https://user-images.githubusercontent.com/5408529/49474342-7278f780-f7e2-11e8-908a-7d414f14613b.png">

### Gallery
- [x] Open in New Tab
- [x] Download Image
- [x] View Fullscreen

### Video
- [x] Open in New Tab
- [x] Download Video
- [x] View Fullscreen

### Playlist
- [x] Open in New Tab
- [x] Download Audio

### Document
- [x] Open in New Tab
- [x] Download Document

### Geolocator
- [x] Open in New Tab
- [x] View Fullscreen

**Comment by suuuth** [comment]
Branch: `suth-413`

**Comment by suuuth** [comment]
Added all tooltips listed in original issue post.  Added the following tooltips to 3d Model field:
- Open in New Tab
- Download Model
- View Fullscreen

All set for review.  Can be seen at this link: `Kora3/public/projects/199/forms/402/records/9364`

**Comment by austintruchan** [comment]
If you can, have the tooltips be centered above the according icon.

Also, while we are here, if you could fix the gallery field from having the grey background, it should be white.

**Comment by suuuth** [comment]
Tooltips have been centered, gallery field background is now white.  Ready for review

**Comment by austintruchan** [comment]
Looks good!
