### ISSUE TITLE
Include New Number Input Up & Down Arrows for Duplicate and Create Test Record Inputs

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#414]
- [x] Create Test Records Modal
<img width="752" alt="screen shot 2018-12-04 at 4 41 31 pm" src="https://user-images.githubusercontent.com/5408529/49475169-81f94000-f7e4-11e8-8263-b2e10e1c103f.png">

- [x] Duplicate Record, on duplicate record page: 
<img width="769" alt="screen shot 2018-12-04 at 4 47 49 pm" src="https://user-images.githubusercontent.com/5408529/49475187-8de50200-f7e4-11e8-9945-33b5e848edee.png">

- [x] Duplicate record, at the bottom of create new record page: 
<img width="1001" alt="screen shot 2018-12-04 at 4 48 07 pm" src="https://user-images.githubusercontent.com/5408529/49475204-98070080-f7e4-11e8-9a00-a85232f7f807.png">

**Comment by suuuth** [comment]
Branch: `suth-414`

**Comment by suuuth** [comment]
New number input up & down arrows added to:
- create test records modal `/Kora3/public/projects/193/forms/324/edit`
- duplicate record `/Kora3/public/projects/193/forms/324/clone/9594`
- create new record page, duplicate record input `/Kora3/public/projects/193/forms/324/records/create`

All set for review

**Comment by austintruchan** [comment]
Looks good!
