### ISSUE TITLE
Kora Logo Target Update

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#415]
<img width="776" alt="screen shot 2018-12-04 at 4 51 00 pm" src="https://user-images.githubusercontent.com/5408529/49475290-d4d2f780-f7e4-11e8-8b9a-eb596c940d02.png">

- [x] Update to read Kora Home Target
- [x] Update description to read "Upon login, or selecting the Kora logo in the top left corner, where would you like to be taken?

- [x] If the dashboard is selected as the home target, the user should be taken to the dashboard upon login, and the if projects is selected, the user is taken to the All projects page on login.

**Comment by suuuth** [comment]
branch suth-415

**Comment by suuuth** [comment]
Adjusted text for this preference and routes based on this preference.  When testing, be sure to navigate to `/home` or just `/`, as once you navigate to the dashboard page, the url will then be `/dashboard` and refreshing the page from there will only bring you back to that page.
