### ISSUE TITLE
User management - Changing the sort of the users, makes all users blank.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#420]
<img width="1014" alt="screen shot 2018-12-06 at 2 32 26 pm" src="https://user-images.githubusercontent.com/5408529/49607389-c9f2a100-f963-11e8-90ab-2a819c8535fc.png">
Changing it to anything other than Alphabetical A-Z seems to cause this blank user bug.

**Comment by Dev34** [comment]
Fixed names disappearing when changing sorts.

This is on the user-management-sort-#420 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looks good!

**Comment by Dev34** [comment]
These changes were ported from development to deconstruct last week, and have today been tested in the deconstruct environment. Behavior in deconstruct environment is as expected, so a pull request has been made.
