### ISSUE TITLE
Reorder user dropdown options for admins

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#422]
<img width="254" alt="screen shot 2018-12-06 at 3 46 23 pm" src="https://user-images.githubusercontent.com/5408529/49610989-265abe00-f96e-11e8-90dc-cd14a812f47d.png">

For consistency with the management drawer in the sidebar:
- [x] Move user management above token management in this user dropdown

- [x] Lets also remove the Kora exodus option from this dropdown, as this will likely rarely ever be used, and having it just exist in the management drawer is fine. Exodus is a pretty cool name though. 

- [x] Then in the management sidebar drawer, lets move backup management up as the third option, to be consistent with the user dropdown.

**Comment by suuuth** [comment]
on branch `suth-422`
- for User Dropdown:
  - `User Management` moved above `Token Management`
  - `Kora Exodus` removed
- `Backup Management` is now the 3rd option in the sidemenu management drawer

**Comment by austintruchan** [comment]
This seems to be good!
