### ISSUE TITLE
Gallery with lots and lots of images

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#423]
![screen shot 2018-12-04 at 1 52 03 pm](https://user-images.githubusercontent.com/5408529/49611240-f06a0980-f96e-11e8-84d6-e029e9b6023a.jpg)

- [ ] I think the grid of dots that occurs is fine, but arrow buttons should remain a perfect circle. So we need to limit the width of the pagination dots grid to allow for the circular buttons to remain intact.

**Comment by Dev34** [comment]
The navigation buttons for GalleryFields contained in a Record should now be circular. A small padding between the buttons and pagination dots has also been added.

Also, I noticed when testing that there was a bug causing the file upload to the GalleryField to error out if the user had not expanded the Advanced Options when creating the GalleryField. This has also been fixed.

Please run ```compass compile```
This is on the gallery-field-updates-#423 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Okay. This looks good!
