### ISSUE TITLE
Error reporting when user tries to enter a number that is outside the allowed range on create / edit record

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#424]
<img width="921" alt="screen shot 2018-12-03 at 4 20 56 pm" src="https://user-images.githubusercontent.com/5408529/49611419-7ede8b00-f96f-11e8-968e-961282fbefd6.png">

eg: If the max number amount 6 and I input 8, the field turns orange but I do not know why.

- [ ] need error validation on this field. Maybe "Number is outside of set range (2-6)" - where 2-6 is the range that is set for that number field.

**Comment by Dev34** [comment]
Added new error message for NumberField in create/edit record.

This is on the record-validation-#424 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Error message does appear after trying to submit the record. Is it possible to also have it appear if the user clicks off / tabs away from the input?

When creating a number field, I also noticed that there is no warning text when you set the default value outside the range that you've set. We will need error text for "Default value is outside the set range" for when the default value is below or above the range.

**Comment by Dev34** [comment]
Added number field value validation when creating record when you click off / tab away from the input.

Added number field value validation when creating a number field. I found the old validation code that was broken and got it working again. It has 'Default value must be less than the maximum' and 'Default value must be greater than the minimum' error messages and a few others. You must have approved those messages at some point in the past or Anthony just added those. Did you want the 'Default value is outside the set range (min-max)' error message instead?

This is on the record-validation-#424 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
We can use what was there before. What I suggested I assumed would be easier to implement, but if those error messages are already there then lets use them.

**Comment by Dev34** [comment]
@austintruchan Yep! The code is already there. Can this issue be moved into code review?

**Comment by austintruchan** [comment]
Sure!

**Comment by Dev34** [comment]
Moving this back to In Progress because I have found a bug with the existing validation code with negative minimums
