### ISSUE TITLE
Spacing / Styling Updates on Advanced Search Page

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#425]
<img width="938" alt="screen shot 2018-12-06 at 4 04 58 pm" src="https://user-images.githubusercontent.com/5408529/49612332-69b72b80-f972-11e8-8798-6724f15ddaf8.png">

- [x] Spacing between lat/long and range field for geolocator advanced search field

<img width="915" alt="screen shot 2018-12-06 at 4 05 16 pm" src="https://user-images.githubusercontent.com/5408529/49612631-4f318200-f973-11e8-8ef2-3507c3a2b845.png">

- [x] "Combo List" label could be closer to its box/group. Remove the margin-top on .record-data-card

- [x] combo list box/group styling should be updated, refer to #417 

  - [x] The padding inside of the combo list box/group could be updated as well.  padding: 10px 30px 30px 30px; looks good.

**Comment by suuuth** [comment]
Styles have been updated.  Can be seen on branch `suth-425` on page `/public/projects/234/forms/405/advancedSearch`.  Ready for review

**Comment by austintruchan** [comment]
Looks good, for the combo list block, have the block container be styled the same way as other block containers that are found on the create new record, single field, etc pages. This one here looks a bit off compared to the others. Make sure all container blocks for all fields are styled like they should be on this advanced search page.

**Comment by suuuth** [comment]
Associator field isssue has been fixed.  This is all set for review.  Again on branch `suth-425` and this page: `/public/projects/234/forms/405/advancedSearch`

**Comment by austintruchan** [comment]
Spacing around the inputs in this grouped block are too small. Make spacing like other inputs that are contained within this type of box: 
<img width="935" alt="screen shot 2019-01-28 at 11 19 23 am" src="https://user-images.githubusercontent.com/5408529/51849921-ae19d480-22ee-11e9-8d33-d5bbe4116347.png">

**Comment by suuuth** [comment]
Can I get you to please check this again?  From that screenshot, you either need to run `compass compile` or you need to verify that you are in the correct branch `suth-425`.  Here is what that block looks like for me:
![capture](https://user-images.githubusercontent.com/31667253/51851950-ffc45e00-22f2-11e9-9b25-f887b0c6adf7.PNG)

**Comment by austintruchan** [comment]
Ope, it seems to be better! looks good.
