### ISSUE TITLE
No Search Results Empty State Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#427]
<img width="1131" alt="screen shot 2018-12-06 at 4 44 33 pm" src="https://user-images.githubusercontent.com/5408529/49614039-27441d80-f977-11e8-9e3e-c83c89aa7143.png">

- [x] Lets remove the "try another search" button when there is no results. It serves little function when the search is already right there. 
Remove from:
- [x] project search results
- [x] form search results
- [x] global search result pages.
- [x] This button should remain when search results do exist though. 

<img width="1003" alt="screen shot 2018-12-06 at 4 50 48 pm" src="https://user-images.githubusercontent.com/5408529/49614148-696d5f00-f977-11e8-89a5-9a13c280114e.png">

- [ ] Advanced Search results needs the no results empty state.

**Comment by suuuth** [comment]
branch `suth-427`

**Comment by suuuth** [comment]
- 'try another search' button removed from all search result empty states
- 'try another search' added to all search result pages to the bottom of the page, below the pagination
- no-results empty state added to advance search page

All set for review

**Comment by austintruchan** [comment]
Looks good!
