### ISSUE TITLE
Mobile Improvements

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#43]
All around

- [x] Headers

- [x] Manage Record Revisions

- [x] Header Tabs

- [x] Pagination

- [x] General

**Comment by suuuth** [comment]
will be on branch suth-43

**Comment by suuuth** [comment]
I believe every header tab section now has horizontal scrolling at smaller widths, the checkboxes no longer overlap text/check area, cards on user management and user profile pages now always collapse to ellipsis on smaller widths like the project cards do on the all projects page, filter sections now collapse consistently across the site and should not have issues with breaking to two lines/overlapping/overflowing off the page

If i've missed anything please let me know

**Comment by austintruchan** [comment]
Sweet. I went through page by page and found several things that could be improved for the mobile experience:

- [ ] Fix empty state on mobile for this page:
![png image](https://user-images.githubusercontent.com/5408529/45320070-9b555d80-b50f-11e8-8416-c9f03be2d34f.png)

- [ ] Looks like the checkboxes get a little miss-aligned on smaller widths on the permission pages.
![png image 9](https://user-images.githubusercontent.com/5408529/45320075-a3ad9880-b50f-11e8-8979-edb48b3e433a.png)

- [ ] Add in space below the content of the card, and above the card actions on user cards on mobile, and really all cards should have this consistent spacing between the content of the card, and the card actions.
![png image 10](https://user-images.githubusercontent.com/5408529/45320120-c049d080-b50f-11e8-9fe2-54b61a06d33e.png)
The space that is there for the fields on the single form page is a good example to go off: 
![png image 11](https://user-images.githubusercontent.com/5408529/45320184-f2f3c900-b50f-11e8-9eea-bf217af81dc7.png)

- [ ] Same for the all projects page - project cards, and the single project page - form cards, where the action buttons are too close to the card content on mobile. 
- [ ] The card content also seems to be too vertically spaced out. Eg: "1234errr" should be a bit closer to the Unique project ID, the way "Fielldddd" is pretty close to unique field Id in the last example.
![png image 16](https://user-images.githubusercontent.com/5408529/45320576-0ce1db80-b511-11e8-8a75-f24dd5788107.png)


- [ ] Single User profiles, and editing user profiles, Lets have the avatar get smaller on mobile, attempting to get it so the line height of the page header title is consistent when it breaks to multiple lines. 
![png image 13](https://user-images.githubusercontent.com/5408529/45320322-5251d900-b510-11e8-894c-8d3bc1940ef3.png)

- [ ] Checkboxes in modals on mobile seem to be too close together, messing up the proximity of which box each title belongs to. Eg: the "search" text is closer to the "create" checkbox, than it is to its own checkbox.
![png image 14](https://user-images.githubusercontent.com/5408529/45320400-875e2b80-b510-11e8-9e07-ecc6710089b0.png)

- [ ] A lot of extra spacing on the backup management pages for the filtering section.
![png image 15](https://user-images.githubusercontent.com/5408529/45320421-993fce80-b510-11e8-9570-c9039b1a10ec.png)


- [ ] Page titles for record cards on mobile get very spaced out, the space between the page title, and it's line should be consistent for all widths: 
<img width="386" alt="screen shot 2018-09-07 at 2 27 43 pm" src="https://user-images.githubusercontent.com/5408529/45320683-54686780-b511-11e8-9c32-da96290048e4.png">


- [ ] Idk I thought this was fixed before, maybe it is on another branch, but there are some mobile issues with the pagination and record filters on record result pages: 
![png image 18](https://user-images.githubusercontent.com/5408529/45320728-77931700-b511-11e8-8d2c-04f6734efa95.png)


- [ ] If a user hits the search button, would be neat if the users keyboard popped up as well like it does on desktop. Not sure what is possible here: 
![png image 19](https://user-images.githubusercontent.com/5408529/45320775-91ccf500-b511-11e8-8cab-331880a83aa6.png)

- [ ] Pages that include multi-step pages with tabbed pagination on mobile, have the hyphen between pages too low: 
![png image 20](https://user-images.githubusercontent.com/5408529/45320804-a7dab580-b511-11e8-8978-a4b7af8a163e.png)

![png image 21](https://user-images.githubusercontent.com/5408529/45320810-add09680-b511-11e8-9aab-fb50f0c59f13.png)

**Comment by austintruchan** [comment]
Sorry for that long comment with lots of long imagery. Let me know if you're confused by any of it!

**Comment by austintruchan** [comment]
- [ ] Looks like you missed the one about aligning the checkboxes on the permissions pages.

- [ ] You can add more space above the trash icon on the user cards, again trying to get the same spacing that is above the trash icon on the field cards on the form page.

- [ ] Actually revert what I said about making ""1234errr" should be a bit closer to the Unique project ID, the way "Fielldddd" is pretty close to unique field Id in the last example." 
We should actually add spacing between the unique field id in and the field description on the single form page, for all widths.

- [ ] checkboxes in the create new token modal are better, but I would add even more space between each checkbox.

- [ ] Add spacing between 10 per page and last modified descending. 
<img width="454" alt="screen shot 2018-09-28 at 2 06 19 pm" src="https://user-images.githubusercontent.com/5408529/46225594-c1f50000-c327-11e8-84eb-cd838a455426.png">

- [ ] At widths lower than 590px, the 10 per page and last modified descending could be spaced out horizontally a bit more as well.

- [ ] Any luck with popping up the keyboard when the user hits the search icon? I wasn't able to see this happening.

**Comment by suuuth** [comment]
- permissions checkboxes now aligned properly
- 15px added to spacing between trash and content of user cards
- 10px added to spacing between field ID and field Description
- 5px added to spacing between create-new-token modal checkboxes
- 5px added to vertical spacing between `per page` and `last modified descending` dropdowns on pages
  - record-index
  - my-profile>Record History
  - individual record revisions
  - search project records
- at 590px width, 40px of margin is applied to `per page` dropdowns
- applied another possible fix to the keyboard issue.  My phone can't connect to my devsite, so I am unable to test if this fix works.

**Comment by austintruchan** [comment]
Everything is good except for the keyboard popping up when selecting the search icon. I would just remove the progress you made on this. Its probably more trouble than its worth. Now I can't even get the search dropdown open, and there are also noticeable issues with the user dropdown. So lets just leave how it was.

**Comment by suuuth** [comment]
Ok.  Changes undone.

**Comment by austintruchan** [comment]
Great. I think we can push.
