### ISSUE TITLE
Form Records Advanced Search Empty State

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#430]
<img width="1302" alt="screen shot 2018-12-06 at 4 01 06 pm" src="https://user-images.githubusercontent.com/5408529/49666372-e48d4e80-fa25-11e8-99c6-d44010d6f85b.png">

- [ ] We need an empty state for when no fields are marked as advanced searchable. https://projects.invisionapp.com/d/main#/console/11107725/335813308/preview

**Comment by suuuth** [comment]
Empty state for when no fields are marked as advanced searchable has been added.  Can be seen on branch `suth-430` on page `/public/projects/193/forms/308/advancedSearch`

**Comment by suuuth** [comment]
'form page' now displays with ubuntu-medium font

**Comment by austintruchan** [comment]
Now we just need cursor pointer on that form page button
