### ISSUE TITLE
3D Model Field on Single Record and Record Card Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#431]
<img width="697" alt="screen shot 2018-12-04 at 4 42 20 pm" src="https://user-images.githubusercontent.com/5408529/49670116-89615900-fa31-11e8-8bf0-dd840324f11f.png">

- [x] Update so the content area of the 3d object displays fills the entire container of the field, like how the geolocator map does.

- [x] Include icon buttons for Open in New Tab, Download, and Full screen. Same layout of icon buttons as the gallery field, but overlayed on top of the 3d object content area.

- [x] Add in functionality for these icon buttons. For fullscreen, mimic the what the geolocator map field does. 
  - [x] open in new window button
  - [x] download file button
  - [x] view fullscreen button

**Comment by suuuth** [comment]
will be on branch `suth-431`

**Comment by suuuth** [comment]
- added model sidebar controls
- added view-in-new-window functionality
- added view-fullscreen-modal
- added functional download button
- adjusted plugin to draw graphics larger when page is loaded

can be seen on this page `Kora3/public/projects/199/forms/408/records`

**Comment by austintruchan** [comment]
- [ ] for 'Update so the content area of the 3d object displays fills the entire container of the field, like how the geolocator map does.' I meant to fill the area around the 3d model, between the edge of the container and the start of the 3d model background. The object itself doesn't need to be enlarged as it seems you have done. 

- [ ] Update box shadow of the x button in the full screen view to match the similar icon buttons in the non full screen view. 

- [ ] Update the size of this x button icon in the full screen view to be font-size 12px

**Comment by austintruchan** [comment]
I dont know if this is directly a cause of what you've done in this branch, but in this branch, a lot of the fields are now the background grey instead of white, and also have enlarged paddings. Make sure this is fixed if caused by your work on the 3d model. 

<img width="853" alt="screen shot 2019-02-18 at 1 50 25 pm" src="https://user-images.githubusercontent.com/5408529/52971118-418d7500-3384-11e9-8ae5-1c01bac19ec6.png">

**Comment by suuuth** [comment]
This style issue was caused by my changes for #425 when I edited styles for the advanced-search page.  This has been fixed.

**Comment by suuuth** [comment]
- fixed styles on this page caused by edits made for issue #425 
- Undid changes made to jsc3d plugin to draw graphics larger
- modified box-shadow and font-size of X icon within the modal-toggle button.

All set for another review

**Comment by austintruchan** [comment]
on smaller widths, ~320px, allow the field to be taller so that the fullscreen and other icon buttons can sit comfortable within. 

<img width="323" alt="screen shot 2019-02-18 at 4 00 08 pm" src="https://user-images.githubusercontent.com/5408529/52976178-70144b80-3396-11e9-8fbc-5a2bbeb8d154.png">

**Comment by suuuth** [comment]
Added a media query to allow this behavior.  All set for review!

**Comment by austintruchan** [comment]
Looks good!
