### ISSUE TITLE
Search button on search pages positioning on mobile

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#432]
![png image](https://user-images.githubusercontent.com/5408529/49759831-beb7b200-fc90-11e8-98c7-3ac454dcde07.png)

- [x] Fix the issue that allows the line to appear behind the search button on mobile
- [x] Make sure this fixed for project search, form search, form advanced search and global search

**Comment by suuuth** [comment]
I think every instance of this has been addressed.  Issue was the button on the right (which is the bottom button on mobile widths) has `float: right` and this was not being removed when the buttons broke to two lines.  This float is now unset at smaller widths.

On branch `suth-432`

**Comment by austintruchan** [comment]
Seems to be good!
