### ISSUE TITLE
Tooltip on create new preset on single field pages when button is faded.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#44]
This will explain that you need to submit/update the field first, before you can create the new value preset.

**Comment by suuuth** [comment]
on branch `suth-44`

**Comment by austintruchan** [comment]
Hmmm not seeing this.

**Comment by suuuth** [comment]
this can be seen on this page: http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/199/presets/create?

if that link doesn't work you can navigate to the page by clicking the project name breadcrumb dropdown -> select 'Field Value Presets' -> select 'create new preset'

**Comment by austintruchan** [comment]
Hmm. I don't think the issue is refering to that page, but is refering to a single field page, specifically fields that have the regex input in the advanced options.

**Comment by suuuth** [comment]
added tooltip to [this](https://i.imgur.com/B3YZ88w.png) button.  removed tooltip previously added

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41997066-e9c19090-7a24-11e8-9bee-81b1ef9bda86.png)

**Comment by suuuth** [comment]
- [ ] List
- [ ] Multi-Select List
- [ ] Generated List
- [ ] Geolocator
- [ ] Schedule
