### ISSUE TITLE
Frontpage redesign 

### ISSUE THREAD

**Issue by asheill** [matrix-msu/Kora3#440]
Please implement updated frontpage from comps.

**Comment by austintruchan** [comment]
@asheill The only thing that is different from the comps is the logo, which will be replaced once the logo is finalized. This is the front page from the comps: https://projects.invisionapp.com/d/main#/console/11107725/234974779/preview

If you're referring to the public promo site frontpage, we have Kevin working on that already in this issue: https://github.com/matrix-msu/Kora3/issues/352

**Comment by austintruchan** [comment]
Oh wait... I see you meant this for ppj! closing issue.

**Comment by asheill** [comment]
Dur! Thanks @austintruchan
