### ISSUE TITLE
Update Text on Token Management Page

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#441]
Update placeholder text on Token Management page.  Currently is:

"Brief info on user Token management, followed by instructions on how to use the token management page will go here."

**Comment by fritosxii** [comment]
@austintruchan What would you like the text to be? Invision comp does not have updated text.

**Comment by austintruchan** [comment]
For now, we can have the tokens page read: "Here you can create, edit and view all the tokens within this Kora installation."

We can have the configuration file page read: "Here you can edit the configuration file for this Kora Installation."

I need help coming up with the intro descriptions on this token page, and the configuration file page that are more technical and explain what tokens can do for the user.

**Comment by fritosxii** [comment]
Token suggestion: "Here you can create, edit and view all the tokens within this Kora installation. Tokens are used to authenticate requests made to the Kora 3 API."

Config suggestion: "Here you can edit the configuration file for this Kora Installation. This includes updating ReCaptcha keys, which are used for User Registration, and updating your server/host settings for emails in Kora 3."
