### ISSUE TITLE
Dashboard - Add Form Block Update

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#446]
- [ ] In the form dropdown when adding a new form block, have the project name listed before the form name for each form, like so: Project Name - Form Name

**Comment by suuuth** [comment]
On branch `suth-446`.

**Comment by suuuth** [comment]
Both edit-block and add-block modals have form dropdowns that have been updated.  All set for review!

**Comment by suuuth** [comment]
Fixing dash bugs here -> #481
