### ISSUE TITLE
Combo List Field Edit Page Update

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#447]
At the moment, its not immediately clear what fields are being used for a combo field, unless you're a kora expert. On the combo list field edit page, I think we need to list what the field types are that are within the combo list.

I think simply changing the labels to explain what each field type could be beneficial.

- [x] For Combo List field name 1, and Combo List field Name 2, lets update these labels to be "First Field (Text) Name", and "Second Field (List) Name", where (Text) and (List) is dynamic depending on what those fields are.

- [x] For the 'Field Options for "Name"', and 'Field Options for "Occupation"', lets add in the type of field within, like so; 'Field Options for Text Field "Name"', and 'Field Options for List Field "Occupation"'. These will be dynamic based on what field type they are.

<img width="986" alt="screen shot 2018-12-19 at 1 53 45 pm" src="https://user-images.githubusercontent.com/5408529/50242144-7175c780-0397-11e9-9e02-d3abad29fcfb.png">

**Comment by suuuth** [comment]
on branch `suth-447`
- combo list field edit page field titles have been adjusted to be dynamic

**Comment by austintruchan** [comment]
Seems to be good!
