### ISSUE TITLE
Project Cards - Remove Space after Admin Names

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#451]
<img width="841" alt="screen shot 2018-12-19 at 2 44 48 pm" src="https://user-images.githubusercontent.com/5408529/50244545-33c86d00-039e-11e9-9f71-2fc321ca6b57.png">

- [x] Remove Space after Admin Names / before comma.

**Comment by suuuth** [comment]
on branch `suth-451`  can be seen on main projects page on the 'Nick's Really Cool Project' card.

**Comment by austintruchan** [comment]
Looks good!
