### ISSUE TITLE
Notification Too Far Left on "Thanks for Signing Up" Page & Loading Icon Pausing after signing up, and requesting additional email

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#452]
<img width="1242" alt="screen shot 2018-12-19 at 2 24 21 pm" src="https://user-images.githubusercontent.com/5408529/50244965-3ecfcd00-039f-11e9-838f-906c76806a4a.png">

- [ ] Notification Too Far Left on "Thanks for Signing Up" Page after signing up, and when requesting another email.

- [ ] After hitting the sign up button on the sign up page, the loading icon appears, but its animation doesn't play. It just sits there stuck, and is weird. This same stuck loading icon happens when requesting another email on the "Thanks fo Signing Up" Page.

**Comment by suuuth** [comment]
Both the loading icon and the notifications work normally for me on this page.  Tested on the `development` branch.  Screenshots below.  Can you please double check that this is broken @austintruchan ?

![register-initial-notification](https://user-images.githubusercontent.com/31667253/52295731-86f48000-294a-11e9-9d1e-dd9b03d80a02.png)
![register-requesting-more-emails](https://user-images.githubusercontent.com/31667253/52295734-88be4380-294a-11e9-8aa9-c8678d5452a4.png)

**Comment by austintruchan** [comment]
Retested and it seems to be working normally
