### ISSUE TITLE
Profile Placeholders Update - For Profile Modal and Profile Image Upload Inputs

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#453]
<img width="459" alt="screen shot 2018-12-19 at 2 57 21 pm" src="https://user-images.githubusercontent.com/5408529/50245338-3330d600-03a0-11e9-9b3d-b38e00bb9449.png">

Please be rid of this monstrosity of a placeholder image.

- [x] Update with what is shown on InVision: https://projects.invisionapp.com/d/main#/console/11107725/245471140/preview

- [x] This Profile Placeholder also exists in the installation sequence when setting up kora, for the root admin profile picture, and should be changed there as well. Make sure it is updated for all profile image upload inputs across Kora.

- [x] On Image Upload inputs, that are correct, make sure the icon is centered within the circle. Atm it is a bit too far left.
<img width="924" alt="screen shot 2018-12-19 at 3 13 58 pm" src="https://user-images.githubusercontent.com/5408529/50245594-e699ca80-03a0-11e9-9a13-06a55ba4baea.png">

**Comment by suuuth** [comment]
will be on branch `suth-453`

**Comment by suuuth** [comment]
- placeholder image replaced with new icon.  replaced on pages:
  - install page
  - edit-profile page
  - user modal on projects page
- added 2 pixels of margin to the left of this new user-icon.  This can be seen on the install page and on the edit-profile page

**Comment by austintruchan** [comment]
- [ ] Update icon in the profile modal to be:  font-size: 55px;  padding: 35px 40px;

**Comment by suuuth** [comment]
Done!

**Comment by austintruchan** [comment]
Looks good, but: 

- [ ] Profile circle falls off the top of the browser on smaller widths.

- [ ] And the modal can be very tall on smaller widths as well.

<img width="396" alt="screen shot 2019-02-04 at 2 09 31 pm" src="https://user-images.githubusercontent.com/5408529/52230947-a75b0680-2886-11e9-8e20-41f61c46ff08.png">

**Comment by austintruchan** [comment]
looks good!
