### ISSUE TITLE
Project permissions request email - spacing issue

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#454]
<img width="574" alt="screen shot 2018-12-19 at 3 25 07 pm" src="https://user-images.githubusercontent.com/5408529/50246114-5a88a280-03a2-11e9-80d6-d5dcc5369921.png">

- [ ] Spacing under the project name should exist, as shown in the comp: https://projects.invisionapp.com/d/main#/console/11107725/259309781/preview

I believe this is being caused after the changes that were made in issue #412

**Comment by suuuth** [comment]
on branch `suth-454`

- added margin-bottom to project title text

**Comment by austintruchan** [comment]
Seems to look good!
