### ISSUE TITLE
Remove "Archive" Option from "Projects Page Tab Selection" on My Preferences

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#455]
Not sure who put this in here, but it never should have been there. Why would someone want this? lol.

- [ ] Remove "Archive" Option from "Projects Page Tab Selection" on My Preferences

<img width="650" alt="screen shot 2018-12-19 at 3 42 39 pm" src="https://user-images.githubusercontent.com/5408529/50247044-e4396f80-03a4-11e9-86b1-0b4b1d599c15.png">

**Comment by suuuth** [comment]
on branch `suth-455`

- archived option removed for this Projects Page Tab Selection preference

**Comment by austintruchan** [comment]
looks good!
