### ISSUE TITLE
Weird bug that crops placeholder text on some inputs on some pages.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#46]
Image attached example comes from a new record page that features an associator field.

**Comment by suuuth** [comment]
```
style: function(a, b, c, d) {
            if (a && 3 !== a.nodeType && 8 !== a.nodeType && a.style) {
                var e, f, g, h = n.camelCase(b), i = a.style;
                return b = n.cssProps[h] || (n.cssProps[h] = Fb(i, h)),
                g = n.cssHooks[b] || n.cssHooks[h],
                void 0 === c ? g && "get"in g && void 0 !== (e = g.get(a, !1, d)) ? e : i[b] : (f = typeof c,
                "string" === f && (e = Bb.exec(c)) && (c = (e[1] + 1) * e[2] + parseFloat(n.css(a, b)),
                f = "number"),
                null != c && c === c && ("number" !== f || n.cssNumber[h] || (c += "px"),
                k.clearCloneStyle || "" !== c || 0 !== b.indexOf("background") || (i[b] = "inherit"),
                g && "set"in g && void 0 === (c = g.set(a, c, d)) || (i[b] = c)),
                void 0)
            }
        },
```
in `production/da294ac8514ee9bd042... .js`

**Comment by suuuth** [comment]
on branch: `suth-placeholder-text-crop-issue-#46`

**Comment by austintruchan** [comment]
Still seeing it 👎 
<img width="401" alt="screen shot 2018-06-19 at 3 19 01 pm" src="https://user-images.githubusercontent.com/5408529/41619413-29f4dc8c-73d4-11e8-9996-9d2c1cb6d8f9.png">

**Comment by suuuth** [comment]
did not initially commit the compiled css, so I made some changes, but they were not applied.  Modified scss to make overwriting these inline width styles more reliable.  Should be able to see this on branch `suth-placeholder-text-crop-issue-#46` and on both `create record` and `create form` pages.

**Comment by austintruchan** [comment]
Seems good!
