### ISSUE TITLE
Too much space above projects for Non Admins

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#470]
<img width="1088" alt="screen shot 2019-01-15 at 10 37 39 am" src="https://user-images.githubusercontent.com/5408529/51191175-ddbdeb00-18b1-11e9-84dc-6d90e1dc3aa1.png">

When the add new project doesn't exist, there is too much space above the first project.

**Comment by suuuth** [comment]
Excess space has been removed.  On branch `suth-470`

**Comment by Dev34** [comment]
This fix has been ported to deconstruct and tested.
