### ISSUE TITLE
Fix dashboard bugs

### ISSUE THREAD

**Issue by suuuth** [matrix-msu/Kora3#481]
- [x] issue where the dashboard has two (2) no-section sections when there should only be one
- [x] issue when adding a form block where the FID is incorrect, which completely prevents the dash page from loading
- [x] once a section is added, the user needs to manually refresh the page to be able to add a block to this section via the add-block modal
- [x] user must manually refresh page to see the new name for a renamed section
  - [x] It is also hard to edit section titles - trying to click on the text input area to update section title typically results in the entire section being dragged around

**Comment by suuuth** [comment]
![](https://user-images.githubusercontent.com/5408529/51618329-19813200-1efc-11e9-974e-1634fa7c6141.png)

**Comment by suuuth** [comment]
- adding `no section` was being called from multiple places in `dashboardController`.  Reduced the number of places this is being called to help prevent duplicate `no section`s from being created and also to improve code readability
- every time a section is added, `makeNonSectionFirst()` is called.  In this method, I added a check to check how many `no section` sections exist.  If the value is > 1, we remove the excess sections.  If the value is 0, we add the section
- edits made for #446 caused form FIDs to be modified.  This was because I used php's `sort()` method, which modified array keys.  Using `asort()` allowed me to sort the array and keep the original FIDs
- Page now automatically reloads when sections are renamed
- Excluded edit-section-title inputs from being draggable handles.  You now can't drag and reorder a section with this element, while you can with any other part of the section

All set for review.  Can be seen on branch: `suth-481`

**Comment by austintruchan** [comment]
Things seem good! Can add a block to no section with no problems, and I no longer see multiple no sections.
