### ISSUE TITLE
Record Revisions Filters

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#486]
We want to filter items on this page by these parameters:

- [ ] user

- [ ] date

- [ ] action i.e. created, edited, deleted, etc.

Need design layout of this and then frontend/backend changes required to make this happen

**Comment by austintruchan** [comment]
@fritosxii would this be for the main Manage Record Revision Page, or for the individual record revision, or both?

At the moment, for me, on kora3.matrix.msu.edu, record revision pages are broken and inaccessible.

**Comment by fritosxii** [comment]
Both. There are probably certain Forms that have broken revision data. The 3.0 version is still pretty buggy. I would try a different Form potentially, or one that doesn't have a lot of records (or complex field types)

**Comment by austintruchan** [comment]
@mikelsav The Manage Record Revisions comp has been updated with ways to sort by user, select a date, and sort by revision type (action): https://projects.invisionapp.com/d/main#/console/11107725/242537799/preview

The date select can use the date select plugin we use on the schedule field, if possible, shown in this comp: https://projects.invisionapp.com/d/main#/console/11107725/252981280/preview

The same additions should be added to the single record revision page as well.
