### ISSUE TITLE
Revision sorting broken

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#488]
Sorting in revisions page is broken

Original issue:
"https://enslaved.kora3.matrix.msu.edu/projects/11/forms/10/records/revisions/recent?order=idd
All Record Revision Sorting logic is not right.
Selection of ID Descending starts with 92773 and starts going down until it gets to 96765 then 96767 the 96766
Selection of ID Ascending starts with 91993 and starts going down until it gets to 92772 then 92773 then 92775.
Selection of Last Modified Ascending starts with listings on 7/19/2018 and vacillates between that and 8/3/2018
Selection of Last Modified Descending does appear to be the opposite of Last Modified Ascending, it starts with 1/25/2019, lists many hundreds of records from 7/19/2018 and then vacillates between that and 8/3/2018
Reminder: ascending means that earlier values precede later ones e.g. 1/1/2000 will sort ahead of 1/1/2001."

**Comment by suuuth** [comment]
branch suth-488

**Comment by suuuth** [comment]
`/Kora3/public/projects/199/forms/248/records/revisions/recent?page-count=30&order=idd&page=1`

**Comment by suuuth** [comment]
In RevisionController, the functions fetching and sorting revisions was sorting by the revision's `created_at` date, and then in the blade file, the record's `updated_at` date was being displayed.  When sorting by ID, the RevisionController was sorting by revision ID, rather than RID.  RevisionController now sorts by `updated_at`, as well as by RID.  All set for review.

**Comment by austintruchan** [comment]
As far as I can see, the sort by is now working properly. 

While you here, if you wanna put the tooltips on the expand / collapse icons similar to other pages that would be good.

**Comment by suuuth** [comment]
Tooltips added, all set for review

**Comment by austintruchan** [comment]
they're there now!
