### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#49]
Updated Design of Notifications: https://projects.invisionapp.com/d/main#/console/11107725/236320203/preview

Notifications will mimic that of macOS notifications, sliding in from the top right, just beneath the header menu. The notification will be fixed, so it will show up beneath the header, even if the user halfway down the page.

Notification will disappear / reverse animate out, after 6 seconds, or if the user taps the dismiss button on the notification.

We will also need the ability for certain notifications to remain, until the user specifically hits the dismiss button.

This was added to allow notifications to be a bit more noticeable.

**Comment by fritosxii** [comment]
- [ ] Updated Notification Design: https://projects.invisionapp.com/d/main#/console/11107725/236320203/preview

- [ ] Notifications should appear immediately. eg: After editing a project, the user is taken to the single project page, the notificaiton should pop in immediately, not slightly delayed.
- [ ] Notifications should dissapear after a little bit. Lets try 6 seconds to start.

- [ ] Also need special notification that stays, until user dismisses it.

- [ ] Notification with Title and body text: https://projects.invisionapp.com/d/main#/console/11107725/236323666/preview

**Comment by fritosxii** [comment]
Disappearing Instances

- [ ] Project Successfully Updated! - After editing project information, and being redirected to project page.

- [ ] Project Successfully Imported! - After importing a project and being redirected to to the All Projects page.

- [ ] Project Successfully Deleted - After deleting a project, and being redirected to the all projects page.

- [ ] Form Successfully Deleted - after deleting a form, and being redirected to the single project page

- [ ] Form Successfully Imported! - After importing a form and being redirected to the single project page.

- [ ] Project Successfully Archived - After archiving a project and then being redirected to the all projects page

- [ ] Field Value Preset Created! - After creating a field value preset and being redirected to the main field value preset screen

- [ ] Field Value Preset Updated! - after editing a field value preset and being redirected to the main field value preset screen

- [ ] Field Value Preset Deleted - After deleting a field value preset

- [ ] Record Successfully Deleted

- [ ] Field Successfully Deleted

- [ ] Form Page Successfully Deleted

- [ ] Form Page Name Updated!

- [ ] Old Record Files Deleted - On the Edit form page

- [ ] All Form Records Deleted - On edit form page

- [ ] # Test Records Created - where "#" is the actual number of test records created. If this is "too hard" just have it say "Test Records Created" - On the edit form page.

- [ ] Record Successfully Duplicated!

- [ ] Record Fields Restored! - after restoring fields to a previous state on the single record revision page, or the all record revisions page.

- [ ] Field Successfully Created! - After creating a field and being redirected back to the single form page.

- [ ] Field Successfully Deleted - After deleting a field and being redirected back to the single form page.

- [ ] Field Successfully Updated! - After editing a field and being redirected back to the single form page.

- [ ] Record Re-Activated! - when reactivating a record from the record revisions managment page.

- [ ] Batch Assign Successful! - After batch assigning field values

- [ ] User Successfully Deleted - After an admin deletes a user from the edit user page.

- [ ] User Successfully Updated! - After and admin updates a user from the edit user page

- [ ] Profile Successfully Updated! - After you update your own profile.

- [ ] Backup File Successfully Created!

- [ ] Editing user profile and updating the password.

**Comment by fritosxii** [comment]
Static Instances

- [ ] Password Reset Email Sent Notification https://projects.invisionapp.com/d/main#/console/11107725/259288984/preview

- [ ] Project Permissions Requested: https://projects.invisionapp.com/d/main#/console/11107725/236323666/preview

- [ ] Password Successfully Reset! 

- [ ] Update Available

- [ ] Required Update available: https://projects.invisionapp.com/d/main#/console/11107725/277195141/preview

- [ ] Sign up success page - user requests another email

- [ ] Form association requested

**Comment by bogdanpozderca** [comment]
Should probably be implemented as such for page load and JS trigger:

#### Page Load
--------
If there is an immediate notification to be displayed on page load, the back-end will set a JSON object in the JavaScript with the following properties:

`type`: Required, value is either 'success' or 'error'
`title`: Required
`description`: Optional
`auto_dismiss`: Optional, Defaults to 'true'
`dismiss_time`: Optional, defaults to '5000' (milliseconds)
`display_delay`: Optional, defaults to '500' (milliseconds)

On load, a method defined in `global.js` will look for the JSON variable and handle it accordingly.

#### JS Trigger
----------
In the event that a notification is to be displayed without a page reload, the method defined in `global.js` should also accept the same JSON object passed in as a variable

**Comment by suuuth** [comment]
branch `suth-notifications`

**Comment by suuuth** [comment]
What determines if an update is required or not?  Or, what would an example of a required update be vs. a non-required update?

**Comment by austintruchan** [comment]
I don't think the updates system has been implemented yet, so no need to worry about this at the moment.

**Comment by austintruchan** [comment]
sweeeeeet

**Comment by austintruchan** [comment]
- [ ] There is a green glow at the top of the login screens, I think from the previously implemented notifications box shadow?

- [ ] Requesting access to project doesn't want to work for me. The submit button in the request project access modal just closes the modal it seems?

- [ ] Update box shadow of green notifications to be     box-shadow: 0 5px 20px 0 rgba(4,182,164,0.3);

**Comment by austintruchan** [comment]
- [ ] "Don't see the project you are looking for? You might not have the permissions..." and Request Project Permissions button seems to be missing now.

- [ ] Request project permissions modal, when selected from the all projects dropdown, does not include the functionality for having the multiselect dropdown drawer to be uncropped by the modal. The dropdown drawer seems to currently be cropped for me. On the project permissions page, when adding a user to the group, this is not the case. 

- [ ] Lets make all notifications the green gradient for now, updating all red notifications. 

- [ ] Add in a notification for "Form Successfully Updated!"

- [ ] add in a notification for "Record Successfully Updated!"

- [ ] add "!" after # test records created

- [ ] Was unable to get the notification for deleting a form page to appear.

- [ ] Don't know if this cause of this branch, but the delete user button, in the delete user modal on the user management page has disappeared! 

- [ ] add in a notification for "User(s) Successfully Invited!" when inviting a user from the user management page. This will also need to be added to the project permissions page, when functionality for inviting users there is complete (currently being worked on by rainier i believe)

- [ ] Add in a notification for "User(s) Successfully Added to Permissions Group!" - for project and form permissions pages. 

- [ ] Add in a notification for "User Successfully Removed from Group" - for project and form permissions pages.

**Comment by suuuth** [comment]
The issue with the Delete User button and modal is present on the master branch as well, and looking at it with inspect-element shows that the body of the modal is actually that of the Invite User To Project modal.  We should probably make an issue for this unless one already exists

**Comment by suuuth** [comment]
Delete User modal issue will be resolved with #288

**Comment by austintruchan** [comment]
Okay! from all my testing things are looking pretty good. Good work on all of this. Further testing on this notification functionality will continue in the main beta.

**Comment by austintruchan** [comment]
Better, I would just make the top and bottom spacing of the text equal, so in this case reducing the space below the text so it is equal to the space above the text.
![png image](https://user-images.githubusercontent.com/5408529/45378093-87226680-b5ca-11e8-964e-4104dba22a01.png)

**Comment by austintruchan** [comment]
Looks good!
