### ISSUE TITLE
Rich Text Display issue

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#499]
Rich text field breaks the html for the Kora display record page.

The following file has the data entered into the rich text field that broke the HTML
[broken_rich.txt](https://github.com/matrix-msu/Kora3/files/2856603/broken_rich.txt)

Find out what's breaking it and why

**Comment by suuuth** [comment]
Screenshot of broken HTML:
![richtext-display-issue](https://user-images.githubusercontent.com/31667253/52664758-dea96300-2ed7-11e9-9a23-95eac2608a41.PNG)

The rest of the page (individual record page) was not expanding with the richtext display, and this display was appearing behind other fields and above the `Record Owner`, `Created`, `Last Updated` text at the very bottom of the page.

Cause: When toggling the field closed/open, upon opening the field, the element was assigned an explicit height value, which then caused issues when children of this element (the rich text display box in this case) were expanded past the parent's height value.

Fix: Unset height value once slide-open animation is complete.  This allows the parent to grow and shrink with children

This was also happening on the view-all-records page when toggling the record card.  Issue has been fixed on this page as well.

Can be seen on branch `suth-499` on any of these pages:
`Kora3/public/projects/199/forms/248/records`
`Kora3/public/projects/193/forms/409/records/9415`
`Kora3/public/projects/193/forms/409/records/9416`

All set for review

**Comment by austintruchan** [comment]
seems to be good!

**Comment by suuuth** [comment]
woohoo!
