### ISSUE TITLE
Stop Scroll to top of page, when you open a dropdown in the header.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#5]
Selecting a dropdown item in the navigation header, automatically scrolls the user to the top of the page. The view should stay put when opening the navigation header dropdown items.

**Comment by suuuth** [comment]
I did not see this happening with any of the dropdown items, however, it was happening upon clicking the activate-sidebar nav button.  Removing the `href="#"` from the `<a>` in the button fixed this.

I went ahead and removed all other unnecessary `href="#"`'s from dropdown elements, just in case this was a browser-specific issue somehow. 


on branch `suth-#5`

**Comment by austintruchan** [comment]
I believe this was already fixed by bogdan awhile back. I would say we just remove your work you've done here, as you've eliminated the cursor pointer on a lot of the links.
