### ISSUE TITLE
offsetWidth error in console

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#500]
There is a global JS error that seems to get triggered often. Notice it on the live sites more than my own dev. Find and remove the cause.

<img width="475" alt="screen shot 2019-02-12 at 3 06 17 pm" src="https://user-images.githubusercontent.com/4040076/52664844-0993b700-2ed8-11e9-8bfd-f67960d20c80.png">

**Comment by austintruchan** [comment]
Ok. I will.

**Comment by suuuth** [comment]
Added a check to check if variable is null before executing code that relies on this var.  If the variable doesn't exist, the code doesn't execute, which prevents this error from showing up 5 times a second every second.

Can be seen on branch `suth-500` on this page `Kora3/public/projects/217/forms/323/records`

**Comment by suuuth** [comment]
Moved to code review because nothing visual was changed for this issue
