### ISSUE TITLE
Add Loading Icon when "Create Record" button is pushed, Same for Edit Record.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#517]
Upon selecting this button on the Create Record Page, include the loading icon. 
<img width="910" alt="screen shot 2019-03-05 at 11 48 29 am" src="https://user-images.githubusercontent.com/5408529/53821924-b643e000-3f3c-11e9-8423-b9b6d7f03e90.png">

Do the same for the Edit Record Page as well.

**Comment by Dev34** [comment]
Added the loading icon to those two buttons.

This is on the record-loading-icons-#517 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looks good!
