### ISSUE TITLE
Specialty Field Displays - Record Card and Single Record View

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#52]
https://projects.invisionapp.com/d/main#/console/11107725/236813275/preview

- [x] Geo
- [x] schedule
- [x] gallery
- [x] rich text
- [x] video
- [x] audio
- [x] documents
- [x] 3d Model

**Comment by fritosxii** [comment]
Adding to this, we will need to fix or rebuild fullscreen implementation for our 3d model viewer (JSC3D)

**Comment by austintruchan** [comment]
## Geo

- [ ] Add Dropshadow around map that is in the comp https://projects.invisionapp.com/d/main#/console/11107725/236813275/preview

- [ ] Opening in a new tab, remove the max width on the map.

- [ ] For the full screen Modal, I would have the modal expand as wide and as tall as the browser

- [ ]  For the full screen Modal, I would have the map fill the height of the modal, and then have the X icon within a white square in the top right. Just like how the open in new tab icon/button is on the map. Keep the X icon's animation.

- [ ] For the Open in Tab, and Fullscreen buttons hover, we might need to have the buttons fade to the hex code of the color that is created when the dark blue is transparent on top of white, so we don't see through the buttons.

**Comment by austintruchan** [comment]
## Gallery

- [ ] Update gallery full screen modal to look like: https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview

- [ ] Have it so clicking directly on the image in a gallery opens up the full screen modal as well.

**Comment by austintruchan** [comment]
## Audio

- [ ] Some subtle updates to the audio player field display, to include timestamps: https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview

- [ ] I can't actually see the timedot moving as the audio plays.

**Comment by austintruchan** [comment]
## Document

- [ ] Update  padding around title of document and around the file size to match the comp: 
https://projects.invisionapp.com/d/main#/console/11107725/241503985/preview

- [ ] Have the title of the document open the document in a new tab, instead of downloading it.

**Comment by austintruchan** [comment]
## Single Select

<img width="861" alt="screen shot 2018-11-08 at 2 03 21 pm" src="https://user-images.githubusercontent.com/5408529/48221113-265fa200-e35f-11e8-815e-f447cfeb813f.png">

- [ ] Have list options and search box left aligned with placeholder/ selected item. Should also be right aligned too with the arrow on the right.

- [ ] Add some space below the search box

- [ ] Have a placeholder in the search box if possible. 

<img width="832" alt="screen shot 2018-11-08 at 2 03 53 pm" src="https://user-images.githubusercontent.com/5408529/48221271-a0902680-e35f-11e8-8cf3-432445b1572f.png">

- [ ] For this case, with groups of options, Update the group titles to no be font-weight bold. 

- [ ] Add more space between each group

**Comment by austintruchan** [comment]
## Gallery 

- [ ] Full screen modal view: reduce space below the caption on taller widths.
<img width="1609" alt="screen shot 2018-12-03 at 3 08 30 pm" src="https://user-images.githubusercontent.com/5408529/49398870-a0403c80-f70d-11e8-89e3-2cda5a1e35c2.png">

**Comment by austintruchan** [comment]
## Playlist

- [ ] Update spacings based on this image:
<img width="847" alt="screen shot 2018-12-03 at 3 17 18 pm" src="https://user-images.githubusercontent.com/5408529/49400309-e8f9f480-f711-11e8-8407-5ce0814e5fa7.png">

- [ ] Keep the play pause circle around the replay icon: 
<img width="837" alt="screen shot 2018-12-03 at 3 17 45 pm" src="https://user-images.githubusercontent.com/5408529/49400345-00d17880-f712-11e8-9011-23cf520f5169.png">

**Comment by austintruchan** [comment]
@fritosxii Nick says he wants you to add that new icon to icomoon for him

**Comment by austintruchan** [comment]
## Playlist

- [ ] On single record card, fix time stamp wonkiness, and update to include updated spacings that you included on the single record.
<img width="846" alt="screen shot 2018-12-03 at 5 53 37 pm" src="https://user-images.githubusercontent.com/5408529/49406738-6dee0980-f724-11e8-892d-7f91afacae3f.png">

- [ ] Too much space to the left of the audio file name and the playbutton now. 
<img width="839" alt="screen shot 2018-12-03 at 5 53 56 pm" src="https://user-images.githubusercontent.com/5408529/49406889-d5a45480-f724-11e8-9ca3-8118ee8ce1ea.png">

- [ ] Doesn't look like you've added any space to the right of the first time stamp, and to the left of the second timestamp.

**Comment by austintruchan** [comment]
## Rich Text
- [ ] Add 5px above the content in the rich text field.
<img width="844" alt="screen shot 2018-12-03 at 3 20 55 pm" src="https://user-images.githubusercontent.com/5408529/49406992-2a47cf80-f725-11e8-997d-f605096854e6.png">

**Comment by austintruchan** [comment]
## Gallery
- [ ] In the full screen modal, if there is a caption, remove the rounded bottom corners of the dark blue background: 
<img width="828" alt="screen shot 2018-12-03 at 6 29 55 pm" src="https://user-images.githubusercontent.com/5408529/49408385-089d1700-f72a-11e8-8e72-f2c16e1754c7.png">

- [ ] in the full screen If no caption exists, and only one image exists, remove the white area below the image. 

- [ ] in the full screen If no caption exists, and only one image exists, there seems to be a tiny white edge to the right side of the modal: 
<img width="965" alt="screen shot 2018-12-03 at 6 30 58 pm" src="https://user-images.githubusercontent.com/5408529/49408449-59147480-f72a-11e8-99de-f2aa33bca60d.png">

**Comment by austintruchan** [comment]
Looks good!
