### ISSUE TITLE
Delete Field Modal Wording

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#521]
<img width="431" alt="screen shot 2019-03-06 at 10 59 59 am" src="https://user-images.githubusercontent.com/5408529/53894984-0be0c100-3fff-11e9-9e3e-7aeb342543bf.png">

Lets change the text to read "Are you sure you wish to delete this field? Deleting will remove any data collected for this field on preexisting records within this form. This cannot be undone."

**Comment by suuuth** [comment]
Branch: `suth-521`
Url: `/public/projects/199/forms/248/fields/1007/options`

There is also a delete-field modal on this page `/public/projects/199/forms/248`.  Should the updated text be applied to the delete-field modal on this page as well @austintruchan ?

**Comment by austintruchan** [comment]
Good call, yes lets do there as well.

Text on the single field modal looks good.

**Comment by suuuth** [comment]
Done.  Set for review.

**Comment by austintruchan** [comment]
Looks good.
