### ISSUE TITLE
Deleting the underlying project/form/record etc for a Dashboard block causes dashboard page to error out

### ISSUE THREAD

**Issue by Dev34** [matrix-msu/Kora3#528]

**Comment by suuuth** [comment]
Branch: `suth-528`

**Comment by suuuth** [comment]
Added a check in the back-end code to prevent this error.  Can be seen on dashboard page.  Can be tested by:
- create a new project
- add a project-block to the dash with the new project
- delete this new project by navigating to the project's page and delete it from there
- refresh/reload the dashboard page

The page should load without errors, and without the project block containing the deleted project.

**Comment by austintruchan** [comment]
Looks good. Tested and works.  

Kevin has left us, so we'll have to manually push this.
