### ISSUE TITLE
Year Range for Date type fields

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#536]
For the date related fields, specifically for setting the max year, we want an option to set it to the current year.

@austintruchan Any thoughts on this since the standard input is a number input? Should we just have a radio button under it that disables the number input and sets it to the current year?

![Screen Shot 2019-04-15 at 9 12 24 AM](https://user-images.githubusercontent.com/4040076/56135392-a3222800-5f5e-11e9-9460-db62d3c1b259.png)

**Comment by austintruchan** [comment]
To understand better, we want to add an additional option for 'end year', to allow the end year to be dynamic with the current year? So if I select current year this year, 2019, The end year is 2019, but when its 2020, the end year is automatically then 2020?

**Comment by fritosxii** [comment]
Yep, so it will always dynamically change to the current year. The design problem is since the End Year box is a number input and not a select, we can't add 'Current Year' to the input

**Comment by austintruchan** [comment]
Ok. Would we want this as a feature for 'start year' as well?

**Comment by fritosxii** [comment]
We may as well.

**Comment by watrall** [comment]
you can check https://github.com/matrix-msu/Kora3/issues/535 for context.  The reporter can also provide you feedback on implementation

**Comment by austintruchan** [comment]
Updated comp with dynamic start and end year options: https://invis.io/XYMZ38FC9SN#/249998349_New_Field_-_Date

Selecting one of the current year radio options will fill in the according year input with '2019 (Current Year)' where '2019' is the current year. 

Selecting one of the current year radio options will also make that input non-selectable and hide the up and down chevron icons.

I'd say we could pass this to development, unless we want to show this to person who inquired about it?

**Comment by mikelsav** [comment]
http://chyron-23.inst.67f3f364-96f5-64dd-8c1f-b6f183235342.us-elns-1.cns.matrix.msu.edu/projects/57/forms/276/fields 
https://github.com/matrix-msu/Kora3/pull/548
I have implemented the solution, awaiting pull request.
