### ISSUE TITLE
Onboarding modal breaks main projects page on certain resolutions on empty state

### ISSUE THREAD

**Issue by Dev34** [matrix-msu/Kora3#550]
When the onboarding modal is sent to a user, the main projects page will look okay on some resolutions, and for other resolutions it will look very badly like this: 
![onboarding-emptystate-projectspage](https://user-images.githubusercontent.com/12753141/56688233-2ef62b80-66a6-11e9-82e9-395b0cce953f.PNG)
This only occurs when there are no projects available to the user (empty state).

This issue only occurs when the onboarding modal is sent to the user, which is typically only once unless they replay it manually.

**Comment by mikelsav** [comment]
http://chyron-23.inst.67f3f364-96f5-64dd-8c1f-b6f183235342.us-elns-1.cns.matrix.msu.edu/projects

Onboarding works now, there was a missing ">" at the end of a closing div tag which caused a lot of issues.

**Comment by austintruchan** [comment]
So it looks like the h3's have fontweight bold on them, and the paragraph text should just be ubuntu regular. Here is the comp: https://projects.invisionapp.com/d/main#/console/11107725/256492346/preview
