### ISSUE TITLE
Record Presets

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#552]
- [x] Update the JS that applies record presets during Record creation

- [x] Define how file fields work in record presets

- [x] Implement isPreset in the Record Model 

- [x] Apply record presets to the Exodus Migration Control

- [x] When a form is deleted, its record presets should also be deleted

- [x] Update dropdown and side Record menus for alreadyPreset check

**Comment by fritosxii** [comment]
All tasks completed for record presets. Works for everything but combo list

**Comment by austintruchan** [comment]
yeah right
