### ISSUE TITLE
Command Line features

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#560]
Reevaluate the need and rebuild the following command line features:

- [x] Exodus script 

- [x] Field convertor 

- [x] install finish 

- [x] import helper 

- [x] record zip file 

- [x] reverse cache 

- [x] thumb script 

- [x] update kora

**Comment by austintruchan** [comment]
Ok. I will

**Comment by fritosxii** [comment]
Re evaluated scripts and removed junk ones. They are now all under the kora3 heading for php artisan instructions
