### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#569]
- [x] Update the placeholder, circle logo that is in the navigation to what is now shown in this comp: https://projects.invisionapp.com/d/main#/console/11107725/234980082/preview

- [x] Update the logo on the login screen to what is now shown in this comp:
https://projects.invisionapp.com/d/main#/console/11107725/234974779/preview

- [x] Update the logon on the signup page for invited users:
https://projects.invisionapp.com/d/main#/console/11107725/258590126/preview

- [x] Update the logo on the several installation pages that have it and in the installation navigation:
https://projects.invisionapp.com/d/main#/console/11107725/258806829/preview
https://projects.invisionapp.com/d/main#/console/11107725/258866763/preview

- [x] Update the logo for the email headers for all emails as well.

Use InVision Inspect to grab the new logos.

**Comment by fritosxii** [comment]
Login page + footer: https://chyron-20.matrix.msu.edu/

Nav logo: same but log in

Activate: https://chyron-20.matrix.msu.edu/user/invitedactivate/egf7HfWplAQgqu9WacOQjB25TdWDXSO

Install (this page uses same style as other): https://chyron-20.matrix.msu.edu/readyplayerone

Email: 
![Screen Shot 2019-06-26 at 3 32 42 PM](https://user-images.githubusercontent.com/4040076/60208986-a885d380-9827-11e9-8809-9fc487709515.png)

**Comment by austintruchan** [comment]
- [ ] Looks like we need a dark logo to go on the activate page, here take this: (Here ask me for it via mattermost when you're ready because GitHub is lame and won't let me upload svgs here)

- [ ] Looks like we could remove this extra 'Kora' text on the installation page:
<img width="480" alt="Screen Shot 2019-06-26 at 3 48 24 PM" src="https://user-images.githubusercontent.com/5408529/60210081-ff8ca800-9829-11e9-8f0e-de1ee44d9fe5.png">

- [ ] Looks like we need a white text logo to go on the activate page, here take this: (Here ask me for it via mattermost when you're ready because GitHub is lame and won't let me upload svgs here)
