### ISSUE TITLE
Tooltips on icons

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#57]
Include tooltips on the following icons....

Tooltips still need to be develop and look like this: https://projects.invisionapp.com/d/main#/console/11107725/244356350/preview

Tooltips will appear above the icons, and will ideally fade in, and have a 1s delay upon hovering before the tooltip appears. 

- [x] edit project icon on single project page

- [x] archive and trash icon on edit project page and pages that have this

**Comment by suuuth** [comment]
I believe I have added tooltips to every icon that needs a tooltip.  Please let me know if you find any un-tooltipped icons

**Comment by austintruchan** [comment]
hmmm. I would use the tooltips that bogdan made that exist on the dashboard page.

**Comment by austintruchan** [comment]
Not seeing the tooltips, should I be looking in a specific branch?

**Comment by suuuth** [comment]
these should be working again @austintruchan .  Please let me know if you find any icons that I missed

**Comment by suuuth** [comment]
on branch: `sutherland-tooltips-#57`

**Comment by austintruchan** [comment]
I see the tooltips.

- [ ] I would look to center the tooltips directly above their according icon.
- [ ] Also for the delete circle buttons the tooltips are very tall.
<img width="285" alt="screen shot 2018-06-06 at 10 30 08 am" src="https://user-images.githubusercontent.com/5408529/41044909-409ee720-6975-11e8-8eb2-349e3edcd6f0.png">


## Other Places to add

- [ ] On Form page, AND search results pages, for "Condense Cards" and "Expand Cards" <img width="115" alt="screen shot 2018-06-06 at 10 32 18 am" src="https://user-images.githubusercontent.com/5408529/41044810-1036c224-6975-11e8-88c6-2dd60aff2823.png">

- [ ] On form page, for the "Delete Page" X icons

Other than that, i'm sure there are more places, but we can make issues for forgotten icons that need them over time.

**Comment by austintruchan** [comment]
Looking good.
