### ISSUE TITLE
Update Logo for Public Website

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#570]
- [x] Update the public website with the new logo which can be seen at: https://projects.invisionapp.com/d/main#/console/11945889/251924732/preview

- [x] Additionally, notice that the logo is smaller on pages that are not the home page. Pretty cool, huh?

The logo can be grabbed using InVision Inspect.

**Comment by fritosxii** [comment]
Tell me what you think of this http://robbie-72.matrix.msu.edu/~anthony.donofrio/promo/home/

**Comment by austintruchan** [comment]
Looks good, just need to adjust the logo on the home page for the fixed header after scrolling down: 
<img width="1340" alt="Screen Shot 2019-06-27 at 3 35 04 PM" src="https://user-images.githubusercontent.com/5408529/60295257-42fe1980-98f1-11e9-8efa-fed137f11292.png">

**Comment by fritosxii** [comment]
All dope now
