### ISSUE TITLE
Add "View Field Type Descriptions" button on top of the field type dropdown.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#59]
Maybe for now just have this open up a modal that just has text saying "Documentation coming soon! Check back later!"

**Comment by suuuth** [comment]
on branch `suth-#59`

**Comment by austintruchan** [comment]
You'll want to style the button as such: https://projects.invisionapp.com/d/main#/console/11107725/241532970/preview

Anthony forgot to include the link to the comp!! Classic ANTHNOY!

The modal looks good though.

**Comment by austintruchan** [comment]
Looks good!
