### ISSUE TITLE
Can't add fields to this form

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#590]
From alicia: "I cannot add new fields to this form https://enslaved-kora.dev.matrix.msu.edu/projects/8/forms/19"

**Comment by asheill** [comment]
Or this form https://enslaved-kora.dev.matrix.msu.edu/projects/8/forms/15/fields

**Comment by asheill** [comment]
Or this form https://enslaved-kora.dev.matrix.msu.edu/projects/24/forms/40/fields

**Comment by asheill** [comment]
I can't test the importer because of this issue.

**Comment by asheill** [comment]
@seilagonzalez @goekesmi

**Comment by seilagonzalez** [comment]
I just tested and it sends you to a 404 page.

**Comment by fritosxii** [comment]
All fixed. There was a missing function in combolist that was breaking any feature that referenced the fields' php classes
