### ISSUE TITLE
Solution for Breadcrumb navigation, on smaller widths, and when breadcrumb navigation is simply too long.

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#6]
Some Potential solutions:
[rCrumbs demo](http://cm0s.github.io/jquery-rcrumbs/demo/)
[Collapsed breadcrumbs](https://codepen.io/fraddski/pen/azjwev)

At the very least...
1. The search icon, user icon, and hamburger icon should remain in their position relative to the top and right side of the browser window, at all times. 
2. The most recent navigation link should stay, while the rest of the navigation links slide behind the kora logo. They are then horizontally scrollable. If scrolled to the right, options would slide behind the search, user icon and hamburger menu. (This is not the most ideal solution), but I think for the time being, and while no sidemenu drawer system exists, this will be the best solution.

**Comment by austintruchan** [comment]
- [ ] I think that the first portion of each breadcrumb text needs to be visible, currently only showing the hyphens is not ideal.

- [ ] The three icons on the right should remain in their positions always, and never pushed off screen. For now I would have the breadcrumbs go behind these icons, but add a green div behind the icons so the text of the breadcrumbs can slide behind, so the text and icons don't interact.

In addition, some other things we can add to allow the navigation to work better on smaller widths:

- [ ] Have it go to the bread crumb condensed mode once the mobile breakpoint begins

- [ ] at widths 420px and below, hide the breadcrumb navigation. The user can then use the side menu to navigate. 

- [ ] Need to add character caps to nav items so they don't ever expand past a certain point. lets set this to be 17 characters, with ellipses if the text goes over.

- [ ] We could also allow for the nav items to be closer together. Reduce margin right of the hphens to be margin-right: 10px; instead of 15px, and also reduce the margin lefts of the nav items to be 10px as well.

**Comment by fritosxii** [comment]
Saw an issue in your dev, where the changes are breaking the language dropdown for the main login page

**Comment by suuuth** [comment]
pushed an update, could I get you to look it over again @austintruchan ?

https://github.com/matrix-msu/Kora3/pull/116

**Comment by austintruchan** [comment]
I noticed a bug that pushes the "Need to sign up" button on the login page to the middle of the browser.
<img width="1366" alt="png image 3" src="https://user-images.githubusercontent.com/5408529/40250453-55422172-5aa4-11e8-8159-013fc83be41d.png">

**Comment by suuuth** [comment]
fixed http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/

**Comment by austintruchan** [comment]
Shouldnt the dropdowns reveal their full text when hovered upon when they are condensed?

**Comment by suuuth** [comment]
They certainly should!  Some styles were not being applied in the css.  Should be fixed now.

**Comment by austintruchan** [comment]
Cool. Cool.
