### ISSUE TITLE
If no projects / forms / field cards exist, remove filter options from displaying and just display the empty state.

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#60]

**Comment by Dev34** [comment]
Single Form Page (Field Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/1/forms/15
Single Project Page (Form Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/1
Main Projects Page (Project Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects

The 'Find a Form'/'Find a Project'/'Find a Field' search functions, as well as the filtering by Alphabetical, Custom[, Archived] are now removed when there are no cards on the respective pages.

**Comment by austintruchan** [comment]
Upon deleting all of the content on the single form you provided, the page errored out. 
Then editing the form inorder to delete it for the link you provided lead to an error page.

Anthony says you should go into your .env file and change debug to true.

Is there a specific branch I should look in for this issue?

**Comment by Dev34** [comment]
Thanks Austin, you discovered #141 which I was not aware of because I never tried to delete the page, only the field cards themselves.
This is on branch empty-state-60
