### ISSUE TITLE
Create Test Record Functionality

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#61]

**Comment by fritosxii** [comment]
Can be tested here: http://robbie-72.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/21/forms/165/edit

**Comment by austintruchan** [comment]
- [ ] For the modal, have the number input moved down a bit. Try to get the spacing around the submit button equal for top right bottom and left. 

- [ ]  Space  above and below the description will be the same too.

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42656064-12ff7896-85ec-11e8-8abe-c7525abd601d.png)
