### ISSUE TITLE
Delete All Record Files Functionality

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#62]
- [x] Functionality of deleting old test record files

- [x] IF no test record files exists, have the button faded, and have a tooltip on hover that says, "No old record files exist."

**Comment by fritosxii** [comment]
Just use any project besides Project Anf and the Test Form in Test Project

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42171833-58c105c2-7de8-11e8-84ac-07a9b9d2e6b7.png)
