### ISSUE TITLE
Delete All Test Records Functionality

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#64]
- [ ] Functionality of deleting all test records

- [ ] IF no test records exists, have the button faded, and have a tooltip on hover that says, "No test records exist."

**Comment by fritosxii** [comment]
Can be tested here: http://robbie-72.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/21/forms/165/edit

**Comment by austintruchan** [comment]
- [ ] have the delete test records button faded if no test records exists.
