### ISSUE TITLE
Text Field Options multiline

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#65]
If you update the field to be multilined, maybe this should change the default field in the field options to be a text box input, instead of remiaing the single line text input.

**Comment by suuuth** [comment]
on branch `suth-65`

**Comment by suuuth** [comment]
Works on my dev: [this](https://i.imgur.com/f06p428.jpg) vs [this](https://i.imgur.com/4N3QtCt.jpg).

investigating why this isn't working for you

**Comment by suuuth** [comment]
revised how this works on `field-show` page.  Verified this is still working on `field-create` page.

**Comment by austintruchan** [comment]
Okay! Seems to be working now.
