### ISSUE TITLE
Functionality for Scrollable modals, if the modal becomes too tall

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#66]
EG: http://dev2.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/1/forms/1/records/create

If you select create new event from the schedule field, and you're on mobile, disaster strikes. Modal is too tall and un scrollable, no way to submit an event

**Comment by suuuth** [comment]
on branch: suth-scrollable-modals-#66

**Comment by austintruchan** [comment]
Modals do in fact scroll now. However the top portion of the modal is cropped above the browser window, and I am unable to scroll up to the very top of the modal. I can scroll to the bottom of the modal though. Tested on safari and chrome.

**Comment by austintruchan** [comment]
Works!
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41677064-4787de86-7495-11e8-9f57-1f02115ec5ec.png)
