### ISSUE TITLE
Multiselect fields on mobile Solutions

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#67]
The chosen multiselect fields look very stock apple on iphone devices, Perhaps there is a way to make them look how the should, like they do on desktop.

They also tend to be very wide in some cases, causing for horizontal scrolling in some cases... like here, if you view on mobile on an iphone: http://dev2.matrix.msu.edu/~anthony.donofrio/Kora3/public/projects/1/forms/1/records/create

I have not tested chosen on other mobile devices, other than iphone.

**Comment by suuuth** [comment]
[desktop view](https://i.imgur.com/vqU1Hkr.jpg) vs. [mobile view](https://i.imgur.com/7yPDLY4.jpg)

seems not all elements are being rendered on mobile view

**Comment by suuuth** [comment]
on branch `suth-67`

**Comment by austintruchan** [comment]
This seems to work!
