### ISSUE TITLE
Add Modal warning for missing fields when changing pages during installation

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#68]

**Comment by austintruchan** [comment]
We can probably implement the same modal / UX that we did for #237, Allowing the user to jump between pages, but unable to submit until all the pages are completed properly.

**Comment by suuuth** [comment]
branch suth-68

**Comment by suuuth** [comment]
Validation modal has been added.  This modal looks and functions identically to the one made for #237

**Comment by austintruchan** [comment]
I don't need @fritosxii to check this out and show me when he does.

**Comment by austintruchan** [comment]
Ok, turns out I'll need @fritosxii to check this out and show me when he does.

**Comment by suuuth** [comment]
Hmm I just tested this and the modal is appearing for me.  Perhaps I added it to the wrong page?  The modal is on page `/install` and only appears when you click `finish kora initialization` on the Recaptcha tab

**Comment by fritosxii** [comment]
Ok, we got it to appear. The only thing left would be to add the orange boxes to the fields that are missing along with a 'Required' error message, similar to how other fields in Kora error out.

**Comment by suuuth** [comment]
Error state and error messages have now been added.  These show both on blur and on page/form submission

**Comment by austintruchan** [comment]
I'll need help from anthony to see these changes.

**Comment by austintruchan** [comment]
I'll need help from anthony to see these changes. Or better yet, @fritosxii go ahead and make sure the error messages are now in fact there during the kora installation.
