### ISSUE TITLE
Duplicate Record Layout Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#7]
https://projects.invisionapp.com/d/main#/console/11107725/241516751/preview

The duplicate page has been currently setup to have the duplicate functionality at the very bottom of the page. This should ideally be at the top of the page, and styled as shown in the comp (link provided above).

**Comment by suuuth** [comment]
can be seen on branch `suth-#7`

**Comment by austintruchan** [comment]
I'm unfortunately not seeing this. :(

**Comment by austintruchan** [comment]
- [ ] Are you able to update the styling for this duplicate record input to have the border as shown in the comps?

- [ ] Duplicate record submit button will be fixed and scroll with you.

**Comment by austintruchan** [comment]
Lol. The Big green submit button should be fixed. Not the duplicate record input! 
![austinapprovesdesignsealofdisapproval](https://user-images.githubusercontent.com/5408529/42172279-8d038886-7de9-11e8-801f-09e5f03c218d.png)

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/42243899-ccee71fc-7ee0-11e8-8696-3c02255ce8d7.png)
