### ISSUE TITLE
multi select records from record result pages inorder to delete multiples - This eliminates the need for subsets

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#70]
Basically each searched term query group is given a session. each session remembers what records selected. 

Ability to select all records in search, and deselect all records from search

Selecting a record, brings up options for deleting, and more.

On hold until design is made.

**Comment by fritosxii** [comment]
We also wanna be able to do other subset operations

**Comment by austintruchan** [comment]
Was all completed recently in #245
