### ISSUE TITLE
Update Page and Functionality

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#71]
https://projects.invisionapp.com/d/main#/console/11107725/242520400/preview

**Comment by suuuth** [comment]
on branch `suth-#71`

**Comment by suuuth** [comment]
http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/update

**Comment by fritosxii** [comment]
Don't worry about this for now. This will be one of the last things we do

**Comment by fritosxii** [comment]
Update functionality complete

**Comment by austintruchan** [comment]
yeah right dude
