### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by fritosxii** [matrix-msu/Kora3#73]
- [ ] Identify all forms that need validation

- [ ] Foreach form, create appropriate error messages

**Comment by fritosxii** [comment]
Only a few pages left:
- [ ] - user management
- [ ] - backups
- [ ] - exodus
- [ ] - project and form permission groups

Moving on to something else for now

**Comment by Dev34** [comment]
### User Management page
* Invite New User(s) modal now requires valid email before modal can be submitted. Added error message.

### Backup Management page
* Create New Backup File modal now requires a name and at least one of the Backup Options checkboxes to be selected before the modal can be submitted. Added error messages.

### Kora 2 Exodus page
* The first four fields are now required before the modal can be submitted. Added error messages.

### Project Permissions page
* Create New Permissions Group now requires a name and at least one of the permission checkboxes to be selected before the modal can be submitted.

### Form Permissions page
* Create New Permissions Group now requires a name and at least one of the permission checkboxes to be selected before the modal can be submitted.

This is on the form-validation-#73 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
- [ ] User management Invite modal: I see the validation text, but not the validation styling on the input.
<img width="811" alt="screen shot 2018-11-01 at 2 44 58 pm" src="https://user-images.githubusercontent.com/5408529/47872356-b6906b00-dde4-11e8-93e6-acffefa97781.png">

- [ ]  For all of these, I can see the validation text, but not the orange validation styling on the inputs themselves.

**Comment by Dev34** [comment]
Whoops. Just added the validation styling to all those inputs.

This is on the form-validation-#73 branch (pushed to GitHub)

**Comment by austintruchan** [comment]
Looking good!
