### ISSUE TITLE
z-index issue on User Profile Issue

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#76]
In edit user mode.  Scroll to the bottom of the page and delete button and Update Profile button stack on top of one another. 

Chrome (Version 66.0.3359.139), Mac

![screen](https://user-images.githubusercontent.com/109138/39498590-f56d1bba-4d76-11e8-9473-77013747bf9f.png)

**Comment by fritosxii** [comment]
@mikelsav Have you made any progress on this or could some other dev work on it?

**Comment by austintruchan** [comment]
Looks good!
