### ISSUE TITLE
Profile Won't Save After Adding Profile Image

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#77]
When editing profile, I drag and drop an profile image to replace the default (I hadn't added one yet).  Works fine and new profile image is displayed in drop area.  Hit the Update Profile button and nothing happens.  I've tested and confirmed the the profile updates fine as long as I haven't dropped a profile image in.  

Chrome Version 66.0.3359.139, Mac

**Comment by fritosxii** [comment]
This has to do with the drag & drop issue. Currently you'll need to manually select files

[https://github.com/matrix-msu/Kora3/projects/1#card-9409329](url)
