### ISSUE TITLE
Finish Sidebar (Sidebar Empty When Viewing Profile)

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#78]
When in View My Profile or Edit My Profile, sidebar/tray opens but is completely empty

**Comment by fritosxii** [comment]
Sidebar menus are being finished up.

**Comment by austintruchan** [comment]
This should be added for all management pages, User management, tokens, etc.

**Comment by fritosxii** [comment]
We need to confirm if this is done or not

**Comment by austintruchan** [comment]
The side bar is blank on the My user Permissions, and My Record History Pages

**Comment by suuuth** [comment]
will be on branch suth-sidebar

**Comment by austintruchan** [comment]
Seems to be good!
