### ISSUE TITLE
Solution for Long Card Titles, and longer card titles on mobile

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#8]
Example Attached.

For titles that are too long, we should have them cut off and turn to an ellipses (...). On hover, a tooltip will appear and display the full title.

<img width="353" alt="screen_shot_2018-02-01_at_2 34 48_pm" src="https://user-images.githubusercontent.com/5408529/36990919-18b9d386-2074-11e8-8949-5df74866f065.png">

**Comment by Dev34** [comment]
Main Projects Page: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects
Single Project Page: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5
Single Form Page with field cards: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5
Tokens Page: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/tokens

Made it less choppy.
Thanks for the tip, it was helpful.
Field cards break at window of width of ~378px due to chevron; to approximately what pixel value should these cards be responsive?
Also on Tokens page, having Search, Create, Edit, and Delete causes it to break at ~395px window width. Perhaps a solution for the chevron text at small widths would help here.

**Comment by austintruchan** [comment]
- [ ] On smaller widths, the length of the title becomes about half the size of the card, or smaller, and a lot of room is lost. Look into having the max width always being slightly shorter than the space provided for it.

- [ ] Be aware that the arrow for title moves on hover. I noticed in some cases that that the title was long enough to were the arrow pushed the chevron off the card.

What you have is fine for responsiveness. We will eventually work on the mobile responsiveness, especially for the single form page at a later date.

**Comment by Dev34** [comment]
Main Projects Page (Project Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects
Single Project Page (Form Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms
Single Form Page (Field Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields
Tokens Page (Token Cards): http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/tokens

Title length is now consistently maximized.
Hovering over shouldn't cause the chevron to get pushed off the card anymore.
Fixed bad chevron placement on page load.

**Comment by Dev34** [comment]
Links from last comment are still good.

Ellipses support added to different tabs. For example, project cards page has Custom, Alphabetical, and Archived tabs, and some of these tabs have additional elements inside of the card which have to be accounted for.

**Comment by austintruchan** [comment]
You'll have to let me know what branch to look in.

**Comment by Dev34** [comment]
This is on the branch named cardtitle-ellipsifying

**Comment by austintruchan** [comment]
Looks good, but noticed that the long card titles were still pushing the chevron to the right.

**Comment by Dev34** [comment]
@austintruchan Which type of card? (Project/Form/Field/Token)

**Comment by austintruchan** [comment]
Tested on project card

**Comment by Dev34** [comment]
Main Projects Page (Project Cards): http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects
Single Project Page (Form Cards): http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms
Single Form Page (Field Cards): http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields
Tokens Page (Token Cards): http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/tokens

branch: cardtitle-ellipsifying (pushed to GitHub)

Increased extra padding from 5 pixels to 10 pixels. Tested on Chrome, Firefox, & Edge. Also added small chevron fix for Token Cards.

**Comment by austintruchan** [comment]
This looks good!
