### ISSUE TITLE
Use First Name Instead of Username in User Dropdown Menu

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#80]
currently, username is displayed in user dropdown menu ("Hello, UseName!").  Consider changing to display user's first name - more personalized that way.

**Comment by austintruchan** [comment]
Excellent. Commit Changes for this, and close issue.

**Comment by Dev34** [comment]
Committed and closed

**Comment by fritosxii** [comment]
Please make a pull request for this code before closing the issue

**Comment by fritosxii** [comment]
Pull request accepted
