### ISSUE TITLE
Focus After You Hit Search Icon

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#81]
Currently, when you hit the search icon, the search tray opens prompting the use to "Start Typing to Search..."  Unfortunately, the focus doesn't automatically switch to search field...the user has to click in the search field, and then start searching.  If they are being told they can "Start Typing to Search..." the user should actually be able to immediately start typing.  They aren't being promoted to "First click in the search field, then start typing to search...."  Consider having focus to search field when they click on the search icon.

**Comment by austintruchan** [comment]
Yep. This is planned for in the design. Has yet to be implemented. I believe using command + K does auto-highlight though.

Search UX enhancements issue: https://github.com/matrix-msu/Kora3/issues/26
