### ISSUE TITLE
Move "browse/view" Records Link to Project Landing Page

### ISSUE THREAD

**Issue by watrall** [matrix-msu/Kora3#82]
Currently, the ability to browse a project's records are buried one level below the link to search a project's records.  Given that these types of interactions are similar (two different ways of interacting with existing records), they should be placed in the same place.  I would suggest adding "Browse Project Records" or "View Project Records" as a link next to "Search Project Records" on the project card in the all projects landing page

**Comment by watrall** [comment]
so, what is the mechanism by which a user browses records?

**Comment by watrall** [comment]
because forms ≠ records

Or am I being stupid and missing something.

**Comment by fritosxii** [comment]
The form is the core data piece in Kora. I.e. It is the schema that defines a record set. You would have to go into your form first, and then you can see view all records that belong to that schema

**Comment by watrall** [comment]
but the form is not the record itself...it is not data. It is the empty shell that defines the shape of the record, right?

**Comment by fritosxii** [comment]
Correct, it is your scheme that defines the data structure

**Comment by watrall** [comment]
so why do you have to go into the form to see records?  The form is not the core data piece...in the same way that an empty paper form is not a core data piece.  A form is just an empty bucket...the record is the result of combining the form and the user inputted data (and the structure of the form is determined by the schema)

**Comment by watrall** [comment]
this is a broader, philosophical design/architecture issue that *is not* going to be dealt with in this release.  Keep it open, but move it to "consider in future" category.

**Comment by fritosxii** [comment]
Moving this internally to clear up issue list
