### ISSUE TITLE
Universal Back Button Styling Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#84]
General styling can be found on any invision screen: https://projects.invisionapp.com/d/main#/console/11107725/234980082/inspect

Tips:

- [x] Will be 50px by 50px

- [x] will have a border radius of 5px for the bottom right corner

- [x] Will include same box shadow hover interaction as hovering a project card.

- [x] Arrow in back button will be the same size and opacity as the arrow icon in the project card.

- [x] Arrow will grow in size / animate the same way the project card arrow does on hover.

- [x]  Universal back button should be non existant on the mobile break point.

**Comment by austintruchan** [comment]
- [ ] Arrow should be same size, color, opacity, and hover effect as these arrows on the cards.
<img width="940" alt="screen shot 2018-05-18 at 2 06 51 pm" src="https://user-images.githubusercontent.com/5408529/40250599-bcadf1d8-5aa4-11e8-9950-12c9db961383.png">

- [ ] Only the arrow should increase in size on hover, not the surrounding box.

**Comment by suuuth** [comment]
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/191/forms/228/records/create

**Comment by austintruchan** [comment]
- [ ] Update border opacity to be .15

- [ ] Change the rounded edge to be the bottom right edge of the button

- [ ] Change font size of arrow icon to be 6

- [ ] Make the arrow icon color be color: #152730; but use whatever the variable is for that color.

**Comment by austintruchan** [comment]
couple more things

- [ ] Remove opacity from the button

- [ ] Update border opacity to be .10

- [ ] Change the class of the button to something more sensible, like back, and not rotate.

- [ ] When hovered, it looks like the arrow goes to full opacity (or I am crazy), But is it possible to only push it up to .8 opacity? Trying to make this as similar to the hover effect of the arrows in the project cards (minus the rotation part)
