### ISSUE TITLE
Jump to Project, Jump to Form Ordering

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#86]
Currently they are listed from oldest to newest, but lets update them so they are listed alphabetically.

**Comment by Dev34** [comment]
Should I also alphabetically sort _Jump to Field_?

**Comment by Dev34** [comment]
Sorted top navigation menu's *Jump to field* 
Sorted sidebar's *Jump to Project/Form/field*

All can be accessed from: http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields/6/options

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41739517-4a1ac9b4-7563-11e8-8db5-67829ad5b2b7.png)
