### ISSUE TITLE
Pagination Updates

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#87]
- [x] Next button / green circular button should have same hover effect that the submit buttons have.

- [x] Next Page, Previous Page, should just be "Next", and "Previous"

- [x] Remove hover underline for "next", "previous" text.

- [x] "Next", and "Previous" should be Ubuntu-Medium

- [x] Add subtle box shadow transition on hover to the active page number box. This can be the same as when hovering on a card.

- [x] When hovering on an inactive page number, change the number to be the accent green. Make sure this is a smooth hover transition.

- [x] When selecting the active page number to type in a page number, lets see if we can remove the default browser styling, and then have the box around the number have an accent green 2px border.

- [x] when selecting the active page number, to input your own page, and then immediately clicking off of it, the active page number should ideally re-appear. 

- [x] When only one page exists, I was able to enter a different number into the active page number. This allowed me to go to that according page I entered, which it should not.

**Comment by suuuth** [comment]
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/189/forms/227/records?page=1

**Comment by austintruchan** [comment]
- [ ] When you select the active pagination number, the borders grow in and shifts the entire page layout downward by a couple pixels. Perhaps you can have the border already applied, but just be invisible until activated. 

- [ ] THe green next button dropshadow seems to appear to the right of the circle, and not below it. Same with the previous button, where the green shadow appears to the left of it, and not below it. 

- [ ] "when selecting the active page number, to input your own page, and then immediately clicking off of it, the active page number should ideally re-appear." If the active page is 2, and I click on the 2, the page number turns to "1". Upon clicking off, it remains "1" (this seemed to only have happened when there was just 2 pages though.)(just figured it out, the last page number seems to always default back to "1"). 

- [ ] When there are enough pages to bring in the ellipses, allow the user to select the ellipses to jump to the next series of pages.

**Comment by suuuth** [comment]
`just figured it out, the last page number seems to always default back to "1"`

yes, the way this works is when the user clicks on the active page, we look to the next page button, get that page number value (if next page is page 3, we get the number 3) and subtract it by 1 to give us our current page number.  However, if no next page exists, the value defaults to 1.  Maybe looking to the previous page is a more practical solution here

**Comment by austintruchan** [comment]
Gotchya. I mean yeah, seems like a better solution. But i'm no expert.

**Comment by suuuth** [comment]
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/189/forms/227/records

**Comment by austintruchan** [comment]
Not seeing this, should I be looking in a specific branch?

**Comment by suuuth** [comment]
this should be re-implemented and working again now @austintruchan

**Comment by suuuth** [comment]
this one is on branch: `sutherland-pagination-#87`

**Comment by austintruchan** [comment]
Looking good.

- [ ] I would also have the number you hover on turn the accent green, and if its the active page number, have the boxes border turn green, and have the dropshadow grow a bit. Similar to other text inputs.

- [ ] If possible, I noticed that clicking on the active page number and then clicking off of it leaves the number at its placeholder styling. So if possible, have the placeholder styling be the ubuntu font, and also have the number return to full opacity if its no longer active.

**Comment by suuuth** [comment]
added ```
&::-webkit-input-placeholder,
&::-moz-placeholder,
&:-ms-input-placeholder,
&:-moz-placeholder {
  font-family: $ubuntu-medium;
  opacity: 1;
}
```
to style placeholder text.  Looks better, but still not exactly like a normal text character

**Comment by austintruchan** [comment]
Also need all numbers to have the hover effect, not just the active page.

For the active page input, see what you can do to remove the default browser blue outline that appears around the number on select.

Returning the active page number to full opacity after deselecting it, did not work. Anything else you can try?

**Comment by suuuth** [comment]
script now replaces the `<input>` element with the original page number text on blur

**Comment by austintruchan** [comment]
What does that even mean?

Still seeing default browser active input state.

Currently cannot change pagination number now from pagination number input.

**Comment by suuuth** [comment]
- [x] all page numbers have green hover effect with transition
- [x] current page number returns when clicking off pagi input
- [x] placeholder text has proper font, opacity
- [x] pagi input does not have default outline property
- [x] active page hover applies box shadow, border, transition effect
- [x] pagi input functionality works

This all works on my dev, and I can verify everything has been committed [here](https://github.com/matrix-msu/Kora3/compare/master...sutherland-pagination-%2387).  What part of this doesn't meet your standards?  What are you seeing?

**Comment by austintruchan** [comment]
Okay after retesting I think its looking good!

A few more things:

- [ ] Change working of next and previous page to just be "Next" and "Previous"

- [ ] Next and Previous text should be ubuntu medium

- [ ] Need hovereffect on the next / previous circle buttons, similar to the effect of hovering on a green submit button

- [ ] Have the non interactable cursor appear when hovering on next/previous when there is no next/previous pages. 

- [ ] On mobile, see what you can do to make the numbers closer together and compact as possible. Ideally numbers will always remain on the same line and won't wrap. We can try reducing the space between numbers, moving the next previous buttons below the numbers, or try reducing the amount of numbers that are shown on mobile.

**Comment by austintruchan** [comment]
- [ ] add in opacity change on green next / previous buttons for hover, similar to the submit button.

- [ ] for the mobile layout, I wouldn't remove all the numbers around the active page number, at the very least we need 1 ... 7 ... 111 (showing the first and last pages)

**Comment by austintruchan** [comment]
- [ ] Opacity change should flip, so it transitions to 1 opacity on hover.

- [ ] For the mobile layout, we still need to have "..." before and after the active page number. Unless the next page is the last page, or the previous page is the first page. 
<img width="300" alt="screen shot 2018-07-16 at 11 20 49 am" src="https://user-images.githubusercontent.com/5408529/42767205-63aa6908-88ea-11e8-8981-40fe2cc652f3.png">

**Comment by suuuth** [comment]
the dots still appear, you just need to have 3 pages or more between the current and first/last page for them to appear.  In you picture, if you went to page 5 you would see the previous-dots, but not the next-dots

**Comment by austintruchan** [comment]
I understand that. But there still needs to be indication that there are missing pages between 1 and 4. Otherwise I could assume that 1 was the previous page, even though 3 is. If this is too complicated, we could move the next, previous buttons below the numbers, and have the numbers act normally.

**Comment by austintruchan** [comment]
- [ ] You'll have to update the spacing of the pagination numbers so they are closer together or remove some page numbers on 375px and below: 
<img width="373" alt="screen shot 2018-07-18 at 11 26 56 am" src="https://user-images.githubusercontent.com/5408529/42891604-b95ef9c4-8a7d-11e8-976a-8a166ad1f44c.png">
<img width="315" alt="screen shot 2018-07-18 at 11 27 37 am" src="https://user-images.githubusercontent.com/5408529/42891607-bac84f18-8a7d-11e8-8ff5-ee74986a55ac.png">

- [ ] Also, when the buttons go to the next line, we can add the "Next" and "Previous" text back in since there is room for them.

**Comment by suuuth** [comment]
what is the lowest browser width that this should be working on?  320px?

**Comment by austintruchan** [comment]
320px, correct

**Comment by austintruchan** [comment]
Alrighty lets get this pushed!
