### ISSUE TITLE
Addition of Searched Term Summary and "Back to Search" Button on Record Result Pages

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#88]
<img width="559" alt="screen shot 2018-05-02 at 11 31 01 am" src="https://user-images.githubusercontent.com/5408529/39533451-15a7d524-4dfd-11e8-9cad-f356e7c3d263.png">

**Comment by suuuth** [comment]
implemented a tentative solution for the `global search results` page - if/once this this solution looks good then i'll go ahead and apply it to
- [ ] form results
- [ ] project results

Also how should the "Try Another Search" button look?  Like the "Search" button on the global search page, or like the "Create New Record" button on the single fields page?  Or like something else entirely?

**Comment by suuuth** [comment]
on branch `suth-88`

**Comment by austintruchan** [comment]
You'll want to have the search summary and back to search above the results as shown on the comps
https://projects.invisionapp.com/d/main#/console/11107725/236796010/preview

Try another search button is shown in those comps as well. This button, along wit the search button in the search summary will push the user to the search section at the top. 

Removing a search summery item will also remove it from the search query at the top, and the results will update accordingly.

**Comment by suuuth** [comment]
- keywords will show below 'Showing X of X Records', but above pagination, which is above the results
- removing a searched-term card will update search query, which will then update results
- added 'try another search' button which scrolls the user to the top of the page
- [ ] update styles of search cards and back-to-search button

**Comment by austintruchan** [comment]
- [ ] good, but include the white fill background on the back to search button as well.

- [ ] On mobile / when back to search becomes stacked, see what you can do to have the back to search button not be indented when placed on the next line, and to have proper spacing away from the search terms. 
<img width="429" alt="screen shot 2018-07-24 at 3 38 09 pm" src="https://user-images.githubusercontent.com/5408529/43162065-e85aa4d8-8f57-11e8-803c-bbd9febf23fd.png">

**Comment by austintruchan** [comment]
I'm not sure if this is a coincidence, but I'm no longer able to perform a global search in this branch. 

I was able to go to the master branch and perform a global search, though, then reload this branch, to see the styling updates, which look good. 

Are you having issues performing global search in this branch?

**Comment by suuuth** [comment]
I have never been able to use the search functions anywhere on this site on my dev - both global and form/record search has never worked for me here.  Everything else works, just not fetching and displaying results.

**Comment by suuuth** [comment]
- [ ] verify `try another search` button works on `Search Form Records`
- [ ] verify `try another search` only appears once a search is made

**Comment by suuuth** [comment]
the lower `try another search` button now only appears once a search has been made

**Comment by suuuth** [comment]
keywords and try-another-search

Shouldn't appear first visit with records (currently they don't) (good)
- [ ] Should appear after keyword search visit with records (currently they don't) (bad)
- [ ] Shouldn't appear first visit with 0 records (currently they do) (bad)

Should appear after keyword search visit with 0 records (currently they do) (good)

**Comment by austintruchan** [comment]
This seems good. The only thing I noticed is the sort options and pagination appear when there are no records. I don't know if that is taken care of in the other empty state issue or not though. My suggestion is we get this and the other empty state issue pushed, and revaluate them together, as it is hard to decipher these two very similar issues separately like this in different branches.
