### ISSUE TITLE
Address Layout styling issue when sidebar drawer is open on widths 980px -1170px

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#9]
Layout / Body content become cut off when the side menu is open during these widths.

**Comment by austintruchan** [comment]
This seems to be fixed by @bogdanpozderca on some pages, however, not all pages are working appropriately. The single field page seems to work well for reference, while the edit project page does not.

**Comment by suuuth** [comment]
on branch `suth-#9`

**Comment by austintruchan** [comment]
Looks like you have made it a lil better, however, the breaking of the widths of the inputs on the edit / create pages seems a little off. For example they break to different widths than the card elements do at different browser widths. I can show you what I mean when you get back to this.

**Comment by suuuth** [comment]
- align form content and header stuff, as is done on `view-projects` page

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41676705-54204d64-7494-11e8-89c9-73124cecc252.png)
