### ISSUE TITLE
Remove ":" colons from Labels

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#92]
For consistency, remove colons from labels. This is apparent on

- [ ] New field page

- [ ] Single field page

- [ ] New Record and Edit Record page

**Comment by Dev34** [comment]
New field page: http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields/create/7?

Single field page:
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/fields/5/options

New record page:
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/records/create

Edit record page:
http://dev2.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/5/forms/5/records/3/edit

**Comment by austintruchan** [comment]
New field

- [ ] Still see it on Field type page

Single Field

- [ ] Still see it on default and regex

- [ ] Make sure every field type advanced option fields do not include the colons.

New Record page:

- [ ] Still seeing the colons

Edit Record page:

- [ ] Still seeing the colons

**Comment by Dev34** [comment]
Purged colons from hundreds of input fields across the repository.

Deleted earlier comment because work couldn't be reviewed at that time due to Git branching situation.

**Comment by austintruchan** [comment]
Still seeing colons everywhere. Is there a branch I should look into?

**Comment by Dev34** [comment]
This is on the colonfix branch

**Comment by Dev34** [comment]
Moved to In Progress because I noticed New Record colons are still present

**Comment by Dev34** [comment]
All Single Field Cards: http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/7/forms/17
New Record page w/ all possible Field cards: http://robbie-72.matrix.msu.edu/~rainier.devolder/Kora3/public/projects/8/forms/16/records/create

branch: colon-purge-#92 (pushed to GitHub)

Hopefully those are all the colons

**Comment by austintruchan** [comment]
![austinapprovesdesignsealofapproval](https://user-images.githubusercontent.com/5408529/41726855-065fbbac-7541-11e8-8d98-3a10ce55da66.png)

**Comment by Dev34** [comment]
Hmm that's strange, that parenthesis is fixed with commit #152 #152
