### ISSUE TITLE
User cannot edit profile picture

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#94]

**Comment by suuuth** [comment]
`403 forbidden` errors on url to default admin picture
http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/public/app/profiles/1/img1.jpg
`storage/app/profiles` is empty as well

**Comment by suuuth** [comment]
trying to update profile pic to populate these files throws error:
```
Call to a member function getClientOriginalName() on string
```
trying to manually add a file with a new profile picture also throws permissions errors.  Chmodding does not affect this

**Comment by suuuth** [comment]
seems like there may be an issue with storing/accessing stored things in a root-level folder? 
https://stackoverflow.com/questions/44247272/laravel-5-4-forbidden-403-on-files-in-storage-with-public-visibility

**Comment by suuuth** [comment]
changing the img path from the symlink that points to `/public/app`, to a hardcoded path that points to `/public/app` causes the same error.  

changing this hardcoded link to one that points to `public/assets/images/` works without error

**Comment by suuuth** [comment]
hardcoding image src to be `http://robbie-72.matrix.msu.edu/~kevin.sutherland/Kora3/storage/app/profiles/1/profile_pic_for_kora.jpg` also works.  it seems only the `/public/app/` directory is causing this issue

**Comment by fritosxii** [comment]
However we do need to figure out why we cannot edit a profile pic

**Comment by suuuth** [comment]
Was changing things because this did not work on my dev, and the title of this ticket led me to believe that was the issue this ticket was made about. @fritosxii 

Editing profile image is fixed however, adding `enctype="multipart/form-data"` to the containing form fixed the issue for me.  Pushing to code review
