### ISSUE TITLE
Single Form Card - Action button misalignment when side bar is open at certain widths

### ISSUE THREAD

**Issue by austintruchan** [matrix-msu/Kora3#99]
It works normally when sidebar is closed.
<img width="640" alt="screen shot 2018-05-03 at 2 49 03 pm" src="https://user-images.githubusercontent.com/5408529/39596764-6dd165aa-4ee1-11e8-8c48-da7af6547b00.png">

**Comment by suuuth** [comment]
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/191/forms/230/fields#

action buttons misaligned when sidebar is opened between pixel widths 1155px and 870px

**Comment by suuuth** [comment]
http://dev2.matrix.msu.edu/~kevin.sutherland/Kora3/public/projects/191/forms/230/fields#

**Comment by suuuth** [comment]
Edited `navigation.js` and `_body.scss` in `scss/partials/form-show/page/_body.scss` for this

commenting to remind myself

**Comment by austintruchan** [comment]
Looking good jeremy
